# This notebook is a test play ground of how I will scrape the data and format to build the scraping script

In [1]:
import subprocess
import re
from fake_useragent import UserAgent
import undetected_chromedriver as uc
from  bs4 import BeautifulSoup
import requests
from curl_cffi import requests as curl_requests
import pandas as pd
import time 
import yaml

147

In [2]:
with open('../config.yaml', 'r') as f:
    config = yaml.safe_load(f)

### SmartScrapper Class:
   This class is made to be able to scrape any webpage even after if the website detected that I am a bot<br> But how? the idea is simple there are two approaches: 
   1. The normal request I make a normal http request using curl_requessts where it helps me provide:
      1. a normaler header that contain more information the most important part the referer the previous link before this request
      2. Impersonate option it acts like a specific chromedriver 120 in my case 
      3. After the response I check if it's a challenge or not if it is a challenge I go to option 2.
   2. Here I use selenium. It's simply a library that actually opens google chrome from my computer and act type the link so it can't be detected but this approach it's only downside it's slower than the normal request approach so this is why it's used as a fallback strategy

In [3]:
# I have trouble scrapping the website using requests, so I will use a smarter approach 


class SmartScraper:
    def __init__(self, config):
        
        self.session = curl_requests.Session()
        self.driver = None
        self.config = config
    

    def get_chrome_version(self):
        try:
            output = subprocess.check_output(
                r'reg query "HKEY_CURRENT_USER\Software\Google\Chrome\BLBeacon" /v version',
                shell=True
            ).decode()
            version = re.search(r'[\d.]+', output).group()
            print(f"Detected Chrome version: {version}")
            return int(version)  # just the major version
        except:
            return None
    
    def format_url(self, slug):
        if '.com' in slug:
            return slug
        return self.config['data_source']['realstate_website']['base_url'] + slug
        
    def get_realistic_headers(self, referer=None):
        """Generate complete, realistic browser headers"""
        headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.9,ar;q=0.8',
            'Accept-Encoding': 'gzip, deflate, br',
            'Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
            'Sec-Fetch-Dest': 'document',
            'Sec-Fetch-Mode': 'navigate',
            'Sec-Fetch-Site': 'same-origin' if referer else 'none',
            'Sec-Fetch-User': '?1',
            'sec-ch-ua': '"Not_A Brand";v="8", "Chromium";v="120"',
            'sec-ch-ua-mobile': '?0',
            'sec-ch-ua-platform': '"Windows"',
        }
        
        if referer:
            headers['Referer'] = referer
            
        return headers
        
    def try_requests_first(self, url, referer=None):
        """Try fast approach with realistic headers"""
        headers = self.get_realistic_headers(referer=referer)
        
        try:
            response = self.session.get(
                url, 
                headers=headers, 
                timeout=15,
                impersonate="chrome120"
                )
            print(f"Response status: {response.status_code}, length: {len(response.text)}")

            if (('humbucker' in response.text or
                'challenge' in response.text) and
                len(response.text) < 10000):
                return None
            if len(response.text) > 50000:
                print("Content looks valid, using requests response")
                return response.text
        
            return None
            
        except Exception as e:
            print(f"Request error: {e}")
            return None
    
    def use_selenium_fallback(self, url):
        """Fallback to Selenium if needed"""
        if not self.driver:
            version = self.get_chrome_version()
            options = uc.ChromeOptions()
            options.add_argument('--disable-blink-features=AutomationControlled')
            self.driver = uc.Chrome(options=options, version_main=version)
        
        self.driver.get(url)
        time.sleep(5)
        return self.driver.page_source
    
    def get_html(self, url, referer=None):
        """Smart approach: try fast method, fallback to slow"""
        print("Trying fast approach (requests)...")
        url = self.format_url(url)
        html = self.try_requests_first(url, referer=referer)
        
        if html:
            print("Success with requests!")
            return html
        
        print("Challenge detected. Using Selenium...")
        html = self.use_selenium_fallback(url)
        
        # Save cookies for next time
        if self.driver:
            cookies = self.driver.get_cookies()
            for cookie in cookies:
                self.session.cookies.set(
                    cookie['name'], 
                    cookie['value'],  
                    domain=cookie.get('domain', '')
                )
        
        return html
    def scrape_single_page(self, url):
        """Scrape a single page with smart approach"""
        html = self.get_html(url)
        
        soup = BeautifulSoup(html, 'lxml')
        # Your parsing code here
        
        return soup
    
    def scrape_multiple_pages(self, urls):
        """Scrape multiple pages efficiently"""
        results = []
        previous_url = None
        for i, url in enumerate(urls):
            print(f"\nPage {i+1}/{len(urls)}")
            html = self.get_html(url, referer=previous_url)
            
            soup = BeautifulSoup(html, 'lxml')
            # Your parsing code here
        
            results.append(soup)
            previous_url = self.format_url(url)
            time.sleep(2)  # Be nice to server
        
        return results
    
    def close(self):
        if self.driver:
            self.driver.quit()

In [4]:
def get_page_data(slug):
    scrapper = SmartScraper(config)
    try:
        
        page_soup = scrapper.scrape_single_page(slug)
       
    finally:    
        scrapper.close()
        print(f"Data extracted for {slug}")
        return page_soup

In [8]:
# get_page_data('apartments-duplex-for-sale/north-rehab-2/?page=5')

#### This is the main page that we are building our scrapping the location logic from 
##### The logic here we have 4 levels of locations:
1. City for now it will only be cairo
2. District like New Cairo, Zamelk, Nasr City
3. Areas each district may have more than on area like in new cairo there is 5th setlement, 1st setlment, ...etc
4. Neighborhood the lowest level <br>**Important note that there places like zamelk it doesn't have these sublevels or areas that doesn't have neihborhoods**<br>
so the following code will be to get this data and save it in the config file so I can fetch the data with structure afterward

In [6]:
soup = get_page_data('cairo')

Trying fast approach (requests)...
Response status: 200, length: 5549782
Content looks valid, using requests response
Success with requests!
Data extracted for cairo

In [14]:
# s = SmartScraper(config)
# x = s.format_url('some-page')
# print(x)

In [ ]:
# First we are going to construct our dataframe to hold our data evantullay 
# After some research I found how the data I will get will be structure
# The data will have the following fields: 
fields = config['data_source']['realstate_website']['fields']

In [24]:
print(f'Data fields to be collected: {len(fields)}')

Data fields to be collected: 33

In [4]:
# Here is a we will try to scrape a single listing page to test our selectors 
# So there are some information that we already know about the listing 
# 1. property type: apartment 2. sale/rent: sale 3. city: cairo 4. district: new cairo 5. area: fifth settlement 6. neighborhood: mountain view i city compound
# The third decision all urls will be typed in the config.yaml file which will not be shared publicly
url = config['data_source']['realstate_website']['base_url']+'cairo/'
headers = config['data_source']['realstate_website']['headers']
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'lxml')

In [6]:
if 'humbucker' in soup.text:
    print("Challenge detected, need to use Selenium or a smarter approach")

In [26]:
# for now we will just get the data and put in a dictonary then we will make the appending logic later
page_data = {}
page_title = soup.select_one(config['data_source']['realstate_website']['selectors']['title']).text.strip()
page_data['title'] = page_title
page_data['price'] = soup.select_one(config['data_source']['realstate_website']['selectors']['price']).text.strip()
page_data['listing_date'] = soup.select_one(config['data_source']['realstate_website']['selectors']['creation_date']).text.strip()
page_data['seller_name'] = soup.select_one(config['data_source']['realstate_website']['selectors']['seller_name']).text.strip()
for key, value in page_data.items():
    print(f"{key}: {value}")

title: Apartment for sale 160M prime location lowest price in mountain view i city
price: EGP 6,000,000
listing_date: 1 week ago
seller_name: Views Real Estate

In [33]:
def extract_date(date):
    if 'today' in date.lower() or 'just now' in date.lower():
        listing_date = pd.Timestamp.now()
    elif 'yesterday' in date.lower():
        listing_date = pd.Timestamp.now() - pd.Timedelta(days=1)
    elif 'day' in date:
        days_ago = int(date.split()[0])
        listing_date = pd.Timestamp.now() - pd.Timedelta(days=days_ago)
    elif 'week' in date:
        weeks_ago = int(date.split()[0])
        listing_date = pd.Timestamp.now() - pd.Timedelta(weeks=weeks_ago)
    elif 'month' in date:
        months_ago = int(date.split()[0])
        listing_date = pd.Timestamp.now() - pd.Timedelta(days=30*months_ago)
    elif 'year' in date:
        years_ago = int(date.split()[0])
        listing_date = pd.Timestamp.now() - pd.Timedelta(days=365*years_ago)
    else:
        listing_date = None  # Handle unexpected format
    if listing_date:
        page_data['listing_date'] = listing_date.strftime('%m-%d-%Y')
    return listing_date.strftime('%m-%d-%Y'), type(listing_date) if listing_date else None

In [34]:
date = page_data['listing_date']

print(f"Listing date: {extract_date(date)}")

Listing date: ('01-08-2026', <class 'pandas._libs.tslibs.timestamps.Timestamp'>)

In [35]:
# Here comes the tricky part of extracting the data for the highlihts, details and features sections
# First we will extract the highlights section
def highlights_extractor(highlit_container, page_data):
    #   outer items contains 
    outer_items = highlit_container.select(config['data_source']['realstate_website']['selectors']['higlight_items'])

    for item in outer_items:
        spans = item.find_all('span')
        if len(spans) >=2:
            key = spans[0].text.strip().lower()
            value = spans[1].text.strip()
            page_data[key] = value
            print(f"Highlight - {key}: {value}")
    return page_data

In [36]:
highlights_container = soup.select_one(config['data_source']['realstate_website']['selectors']['highlights_container'])
page_data = highlights_extractor(highlights_container, page_data)
page_data['property_subtype'] = page_data.pop('type', None)

Highlight - type: Apartment
Highlight - ownership: Resale
Highlight - area (m²): 160
Highlight - bedrooms: 3
Highlight - bathrooms: 3
Highlight - furnished: No

In [37]:
details_container = soup.select_one('div[aria-label="Details"]')
# print(details_container.prettify())
details_itemss = details_container.select(config['data_source']['realstate_website']['selectors']['details_items'])
for item in details_itemss:
    spans = item.find_all('span')
    key = spans[0].text.strip().lower()
    value = spans[1].text.strip().lower()
    page_data[key] = value
    print(f"Detail - {key}: {value}")

Detail - level: 1
Detail - payment option: cash
Detail - completion status: ready

In [38]:
features_container = soup.select_one(config['data_source']['realstate_website']['selectors']['features_container'])
features_items = features_container.select(config['data_source']['realstate_website']['selectors']['features_items'])

In [39]:
for item in features_items:
    spans = item.find_all('span')
    for span in spans:
        key = span.text.strip().lower()
        if key == 'see all':
            continue
        
        page_data[key] = True
        print(f"Feature - {key}: True")

Feature - balcony: True
Feature - built in kitchen appliances: True
Feature - security: True
Feature - covered parking: True
Feature - pets allowed: True
Feature - pool: True
Feature - electricity meter: True
Feature - elevator: True

In [40]:
for key, value in page_data.items():
    print(f'{key} : {value}')

title : Apartment for sale 160M prime location lowest price in mountain view i city
price : EGP 6,000,000
listing_date : 01-08-2026
seller_name : Views Real Estate
ownership : Resale
area (m²) : 160
bedrooms : 3
bathrooms : 3
furnished : No
property_subtype : Apartment
level : 1
payment option : cash
completion status : ready
balcony : True
built in kitchen appliances : True
security : True
covered parking : True
pets allowed : True
pool : True
electricity meter : True
elevator : True

##### Now we want to know how to get the data from each page so we inspect the page and start taking notes
##### then I will try to take one property and see how to get its data then I will from there build the logic 
##### but we need first to understand that each filter will change the url and the data we get
##### to get all data we need to loop over all filters and get the data from each page and be aware of dublicates but this problem will be solved later 
##### let's now try to get the data from one property 
#### for example this one will be in: 
1. Cairo as all the data we will be collecting
2. Apartment sale
3. In New Cairo
4. 5th setlment
5. mountain-view-icity-compound<br>
**Lastly All the data will be taken from the property page not like in the generlization some will be taken before entering the property page**

In [41]:
# Know we will have to append the data to the dataframe first for the first instance there are some information that we already know about it 
# After that we will get this information scrapped as well 
page_data['city'] = 'cairo'
page_data['district'] = 'new cairo'
page_data['area'] = 'fifth settlement'
page_data['neighborhood'] = 'mountain view i city compound'
page_data['property_type'] = 'apartment'
page_data['sale/rent'] = 'sale'

In [42]:
features = config['data_source']['realstate_website']['features_list']
for feature in features:
    if feature not in page_data:
        page_data[feature] = False
        print(f"Feature - {feature}: False")

Feature - water meter: False
Feature - natural gas: False
Feature - private garden: False
Feature - landline: False
Feature - maid room: False
Feature - built in kitchen: False
Feature - central a/c & heating: False

In [15]:
# apending the data will have some logic let's start with the simple appending logic 
# first mapping between the column data and the page data keys 
df_cols = df.columns.tolist()
for col in df_cols:
    if col not in page_data:
        page_data[col] = None
        print(f"Column {col} not found in page data, setting to None")

Column delivery time not found in page data, setting to None

In [43]:
rows = []
rows.append(page_data)
df = pd.DataFrame(rows, columns=fields)
df.head()

,title,property_type,sale/rent,city,district,area,neighborhood,property_subtype,ownership,electricity meter,...,furnished,level,bedrooms,bathrooms,payment option,delivery time,price,seller_name,area (m²),listing_date
0,Apartment for sale 160M prime location lowest ...,apartment,sale,cairo,new cairo,fifth settlement,mountain view i city compound,Apartment,Resale,True,...,No,1,3,3,cash,NaN,"EGP 6,000,000",Views Real Estate,160,01-08-2026

In [44]:
df .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  1 non-null      object
 1   property_type          1 non-null      object
 2   sale/rent              1 non-null      object
 3   city                   1 non-null      object
 4   district               1 non-null      object
 5   area                   1 non-null      object
 6   neighborhood           1 non-null      object
 7   property_subtype       1 non-null      object
 8   ownership              1 non-null      object
 9   electricity meter      1 non-null      bool
 10  water meter            1 non-null      bool
 11  covered parking        1 non-null      bool
 12  natural gas            1 non-null      bool
 13  security               1 non-null      bool
 14  pets allowed           1 non-null      bool
 15  balcony                1 non-null      bool
 16  private garden         1 non-null      bool
 17  pool                   1 non-null      bool
 18  landline               1 non-null      bool
 19  maid room              1 non-null      bool
 20  built in kitchen       1 non-null      bool
 21  elevator               1 non-null      bool
 22  central a/c & heating  1 non-null      bool
 23  furnished              1 non-null      object
 24  level                  1 non-null      object
 25  bedrooms               1 non-null      object
 26  bathrooms              1 non-null      object
 27  payment option         1 non-null      object
 28  delivery time          0 non-null      float64
 29  price                  1 non-null      object
 30  seller_name            1 non-null      object
 31  area (m²)              1 non-null      object
 32  listing_date           1 non-null      object
dtypes: bool(14), float64(1), object(18)
memory usage: 294.0+ bytes

### Starting from here we will work on getting the locations data 
1. We will start by getting the districts data then we will move to the areas and neighborhoods data

In [5]:
# The districts names are under a div with class "d36fe94e"
# each listing is is under a <a> tag containing a hyperlink to filter the properties with this district
# then under the a tag there is a span tag containing the district name and other span tag containing the count of properties in this district
districts_div = soup.find('div', class_='d36fe94e')
districts = districts_div.find_all('a')
districts_list = []
for district in districts:
    if len(district.findAll('span')) < 2:
        continue
    link = district['href']
    name = district.find_all('span')[0].text
    count = district.find_all('span')[1].text
    districts_list.append({'link': link, 'name': name, 'count': count})
print(f"Total districts found: {len(districts_list)}")
for d in districts_list:
    print(d)

NameError: name 'soup' is not defined

In [8]:
district_slugs = []
for district in districts_list:
    district_slugs.append(district['link'][15:-1])
    print(district_slugs[-1])

new-cairo
madinaty
mostakbal-city
new-capital-city
shorouk-city
nasr-city
katameya
new-heliopolis
maadi
sheraton
zahraa-al-maadi
mokattam
heliopolis
obour-city
badr-city
el-fostat
zamalek
new-nozha
ain-shams
hadayek-al-kobba
hadayeq-el-zeitoun
al-manial
gesr-al-suez
downtown-cairo
almazah
shubra
helmeyat-el-zaytoun
marg
helwan
nozha
salam-city
hadayek-helwan
abasiya
15-may-city
masr-al-kadema
matareya
rod-al-farag
boulaq-abo-el-ela
garden-city
basateen

In [5]:
def get_sub_locations(soup, neighborhood = True, number_of_districts=None, parent_location_name=None):
    # location_div = soup.find('div', class_='d36fe94e')
    # print(location_div.prettify())
    try:
        location_div = soup.find('div', class_='d36fe94e')
        locations = location_div.find_all('a')
    except Exception as e:
        print(f"Error finding location div: {e}")
        return []
    # print(f"Total locations found: {len(locations)}")
    # if len(locations) == number_of_districts:
    #     for location in locations:
    #         if len(location.findAll('span')) < 2:
    #             continue
    #         name = location.find_all('span')[0].text
    #         print(f"Checking if location {name} is the same as parent location {parent_location_name}")
    #         if name == parent_location_name:
    #             print(f"Locations list is the same as parent location {parent_location_name}, has no sub-locations")
    #             return None
           
    locations_list = []

    for location in locations:
        if len(location.findAll('span')) < 2:
            continue
        slug = location['href'][15:-1]
        name = location.find_all('span')[0].text
        count = location.find_all('span')[1].text
        # print(f'working on {name} data')
        if len(locations) >= number_of_districts and name == parent_location_name:
                # print(f"Locations list is the same as parent location {parent_location_name}, has no sub-locations")
                return []
        if neighborhood:
       
            # sub_soup = get_page_data(slug)
            # areas = get_sub_locations(sub_soup, neighborhood=False)
            # if len(areas) == len(locations) or not areas:  # Check if areas is an empty list or None
            #     areas = name
            #     print(f"No areas found for {name}")
            locations_list.append({'slug': slug, 'name': name, 'count': count, 'neighborhoods': None})
            
        else:
            locations_list.append({'slug': slug, 'name': name, 'count': count})
        # print(f'Finished working on {name}')
    return locations_list

In [6]:
mouintain_view_soup = get_page_data('mountain-view-3')

Trying fast approach (requests)...
Response status: 200, length: 6023018
Content looks valid, using requests response
Success with requests!
Data extracted for mountain-view-3

In [13]:
mv_sub_locations = get_sub_locations(
    mouintain_view_soup,
    neighborhood=False,
    number_of_districts=40,
    parent_location_name='Mountain View'
)
print(f"Sub-locations for Mountain View: {mv_sub_locations}")

Sub-locations for Mountain View: [{'slug': 'hyde-park-new-cairo-compound', 'name': 'Hyde Park New Cairo Compound', 'count': '(3440)'}, {'slug': 'mivida-compound', 'name': 'Mivida Compound', 'count': '(3255)'}, {'slug': 'mountain-view-icity-compound', 'name': 'Mountain View iCity Compound', 'count': '(2890)'}, {'slug': 'palm-hills-new-cairo-compound', 'name': 'Palm Hills New Cairo Compound', 'count': '(1906)'}, {'slug': 'fifth-square-compound', 'name': 'Fifth Square Compound', 'count': '(1889)'}, {'slug': 'mountain-view-hyde-park-compound', 'name': 'Mountain View Hyde Park Compound', 'count': '(1317)'}, {'slug': 'eastown-compound', 'name': 'Eastown Compound', 'count': '(1284)'}, {'slug': 'beit-al-watan-6', 'name': 'Beit Al Watan', 'count': '(1215)'}, {'slug': 'city-gate-compound', 'name': 'City Gate Compound', 'count': '(1188)'}, {'slug': 'lake-view-residence-compound', 'name': 'Lake view Residence Compound', 'count': '(1156)'}, {'slug': 'el-patio-oro-compound', 'name': 'EL Patio ORO Compound', 'count': '(1096)'}, {'slug': 'villette-compound', 'name': 'Villette Compound', 'count': '(1053)'}, {'slug': 'el-lotus-2', 'name': 'El Lotus', 'count': '(949)'}, {'slug': 'the-address-east-compound', 'name': 'The Address East Compound', 'count': '(831)'}, {'slug': 'al-andalous-2', 'name': 'Al Andalous', 'count': '(759)'}, {'slug': 'galleria-moon-valley-compound', 'name': 'Galleria Moon Valley Compound', 'count': '(756)'}, {'slug': 'cairo-festival-city-3', 'name': 'Cairo Festival City', 'count': '(670)'}, {'slug': 'mountain-view-1-1-2', 'name': 'Mountain View 1.1', 'count': '(660)'}, {'slug': 'creek-town-compound', 'name': 'Creek Town Compound', 'count': '(644)'}, {'slug': 'al-narges-2', 'name': 'Al Narges', 'count': '(633)'}, {'slug': 'district-5-compound-compound', 'name': 'District 5 Compound', 'count': '(585)'}, {'slug': 'north-90-street-2', 'name': 'North 90 Street', 'count': '(444)'}, {'slug': 'azzar-compound', 'name': 'Azzar Compound', 'count': '(402)'}, {'slug': 'south-90-street-2', 'name': 'South 90 Street', 'count': '(384)'}, {'slug': '90-avenue-compound', 'name': '90 Avenue Compound', 'count': '(380)'}, {'slug': 'lake-view-residence-2-2', 'name': 'Lake View Residence 2', 'count': '(369)'}, {'slug': 'the-square-compound', 'name': 'The Square Compound', 'count': '(336)'}, {'slug': 'south-of-academy-2', 'name': 'South of Academy', 'count': '(295)'}, {'slug': 'katameya-dunes-compound', 'name': 'Katameya Dunes Compound', 'count': '(294)'}, {'slug': 'the-icon-residence-compound', 'name': 'The Icon Residence Compound', 'count': '(289)'}, {'slug': 'the-waterway-compound-2', 'name': 'The Waterway Compound', 'count': '(277)'}, {'slug': 'palm-hills-katameya-compound', 'name': 'Palm Hills Katameya Compound', 'count': '(276)'}, {'slug': 'village-gate-compound', 'name': 'Village Gate Compound', 'count': '(275)'}, {'slug': 'banafsag-omarat-2', 'name': 'Banafsag Omarat', 'count': '(267)'}, {'slug': 'layan-compound', 'name': 'layan Compound', 'count': '(266)'}, {'slug': 'new-narges-2', 'name': 'New Narges', 'count': '(265)'}, {'slug': 'lake-view-compound', 'name': 'Lake View Compound', 'count': '(236)'}, {'slug': 'the-village-compound', 'name': 'The Village Compound', 'count': '(236)'}, {'slug': 'azad-compound', 'name': 'AZAD Compound', 'count': '(229)'}, {'slug': 'south-investors-2', 'name': 'South Investors', 'count': '(229)'}]

C:\Users\marwa\AppData\Local\Temp\ipykernel_28164\1727533725.py:24: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  if len(location.findAll('span')) < 2:

In [30]:
sub_locations = get_sub_locations(page_soup)

24

In [22]:
print(so.prettify())

<!DOCTYPE html>
<html>
 <body>
  <script type="text/javascript">
   !function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.Fingerprint=t():e.Fingerprint=t()}(self,(()=>(()=>{"use strict";var e={795:function(e,t,n){var r=this&&this.__assign||function(){return r=Object.assign||function(e){for(var t,n=1,r=arguments.length;n<r;n++)for(var i in t=arguments[n])Object.prototype.hasOwnProperty.call(t,i)&&(e[i]=t[i]);return e},r.apply(this,arguments)},i=this&&this.__awaiter||function(e,t,n,r){return new(n||(n=Promise))((function(i,o){function a(e){try{u(r.next(e))}catch(e){o(e)}}function c(e){try{u(r.throw(e))}catch(e){o(e)}}function u(e){var t;e.done?i(e.value):(t=e.value,t instanceof n?t:new n((function(e){e(t)}))).then(a,c)}u((r=r.apply(e,t||[])).next())}))},o=this&&this.__generator||function(e,t){var n,r,i,o,a={label:0,sent:function(){if(1&i[0])throw i[1];return i[1]},trys:[],ops:[]};return o={next:c(0),throw:c(1),return:c(2)},"function"==typeof Symbol&&(o[Symbol.iterator]=function(){return this}),o;function c(c){return function(u){return function(c){if(n)throw new TypeError("Generator is already executing.");for(;o&&(o=0,c[0]&&(a=0)),a;)try{if(n=1,r&&(i=2&c[0]?r.return:c[0]?r.throw||((i=r.return)&&i.call(r),0):r.next)&&!(i=i.call(r,c[1])).done)return i;switch(r=0,i&&(c=[2&c[0],i.value]),c[0]){case 0:case 1:i=c;break;case 4:return a.label++,{value:c[1],done:!1};case 5:a.label++,r=c[1],c=[0];continue;case 7:c=a.ops.pop(),a.trys.pop();continue;default:if(!((i=(i=a.trys).length>0&&i[i.length-1])||6!==c[0]&&2!==c[0])){a=0;continue}if(3===c[0]&&(!i||c[1]>i[0]&&c[1]<i[3])){a.label=c[1];break}if(6===c[0]&&a.label<i[1]){a.label=i[1],i=c;break}if(i&&a.label<i[2]){a.label=i[2],a.ops.push(c);break}i[2]&&a.ops.pop(),a.trys.pop();continue}c=t.call(e,a)}catch(e){c=[6,e],r=0}finally{n=i=0}if(5&c[0])throw c[1];return{value:c[0]?c[1]:void 0,done:!0}}([c,u])}}};Object.defineProperty(t,"__esModule",{value:!0}),t.validateFeatures=t.buildBrowserFeatureObject=t.videoCodecs=t.audioCodecs=t.deviceMemory=t.notificationPermissions=t.webdriver=t.headlessProperties=t.screenDesc=t.evalToString=t.navigatorPrototype=t.productSub=t.multimediaDevices=t.videoCard=t.touchScreen=t.screenProperties=t.languages=t.platform=t.mimeTypes=t.userAgent=void 0;var a=n(817),c=n(923);t.userAgent=function(){return navigator.userAgent},t.mimeTypes=function(){return Array.from(navigator.mimeTypes).map((function(e){return[e.description,e.type,e.suffixes].join("-")}))},t.platform=function(){return navigator.platform||null},t.languages=function(){return navigator.languages||null},t.screenProperties=function(){return{window:{innerHeight:window.innerHeight,outerHeight:window.outerHeight,innerWidth:window.innerWidth,outerWidth:window.outerWidth,screenX:window.screenX,screenY:window.screenY,pageXOffset:window.pageXOffset,pageYOffset:window.pageYOffset,devicePixelRation:window.devicePixelRatio},client:{width:document.body.clientWidth,height:document.body.clientHeight},screen:{width:screen.width,height:screen.height,availWidth:screen.availWidth,availHeight:screen.availHeight,colorDepth:screen.colorDepth,pixelDepth:screen.pixelDepth}}},t.touchScreen=function(){var e;try{document.createEvent("TouchEvent"),e=!0}catch(t){e=!1}return{maxTouchPoints:navigator.maxTouchPoints||navigator.msMaxTouchPoints||0,onTouchStart:"ontouchstart"in window,canHandleTouchEvents:e}},t.videoCard=function(){try{var e=document.createElement("canvas"),t=e.getContext("webgl")||e.getContext("experimental-webgl");if(!t)return{vendor:null,renderer:null};if(!("getSupportedExtensions"in t))return{vendor:null,renderer:null};if(!t.getSupportedExtensions())return{vendor:null,renderer:null};if(t.getSupportedExtensions().indexOf("WEBGL_debug_renderer_info")<0)return{vendor:null,renderer:null};var n=t.getExtension("WEBGL_debug_renderer_info");return n?{vendor:t.getParameter(n.UNMASKED_VENDOR_WEBGL),renderer:t.getParameter(n.UNMASKED_RENDERER_WEBGL)}:{vendor:null,renderer:null}}catch(e){return{vendor:null,renderer:null}}},t.multimediaDevices=function(){return i(void 0,void 0,void 0,(function(){return o(this,(function(e){switch(e.label){case 0:return navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices&&"enumerateDevices"===navigator.mediaDevices.enumerateDevices.name?[4,navigator.mediaDevices.enumerateDevices()]:[2,[]];case 1:return[2,e.sent().map((function(e){return e.toJSON()}))]}}))}))},t.productSub=function(){return navigator.productSub},t.navigatorPrototype=function(){var e=Object.getPrototypeOf(window.navigator),t=Object.getOwnPropertyNames(e),n={};return t.forEach((function(t){var r=Object.getOwnPropertyDescriptor(e,t);r?r.value?n[t]=r.value.toString():r.get?n[t]=r.get.toString():n[t]=null:n[t]=null})),n},t.evalToString=function(){return eval.toString().length},t.screenDesc=function(){try{return Object.getOwnPropertyDescriptor(Object.getPrototypeOf(screen),"width").get.toString()}catch(e){return null}},t.headlessProperties=function(){var e={};return["__nightmare","callPhantom","_phantom","phantom","webdriver","_Selenium_IDE_Recorder","callSelenium","_selenium","__webdriver_script_fn","__driver_evaluate","__webdriver_evaluate","__selenium_evaluate","__fxdriver_evaluate","__driver_unwrapped","__webdriver_unwrapped","__selenium_unwrapped","__fxdriver_unwrapped","__webdriver_script_func"].forEach((function(t){e[t]=t in window})),r(r({},e),{documentSelenium:null!==document.documentElement.getAttribute("selenium"),documentWebdriver:null!==document.documentElement.getAttribute("webdriver"),documentDriver:null!==document.documentElement.getAttribute("driver")})},t.webdriver=function(){return navigator.webdriver},t.notificationPermissions=function(){return i(void 0,void 0,void 0,(function(){var e;return o(this,(function(t){switch(t.label){case 0:return t.trys.push([0,2,,3]),[4,navigator.permissions.query({name:"notifications"})];case 1:return[2,{name:(e=t.sent()).name,state:e.state}];case 2:return t.sent(),[2,null];case 3:return[2]}}))}))},t.deviceMemory=function(){return navigator.deviceMemory},t.audioCodecs=function(){var e=document.createElement("audio");return e.canPlayType?{ogg:e.canPlayType('audio/ogg; codecs="vorbis"'),mp3:e.canPlayType("audio/mpeg;"),wav:e.canPlayType('audio/wav; codecs="1"'),m4a:e.canPlayType("audio/x-m4a;"),aac:e.canPlayType("audio/aac;")}:{ogg:null,mp3:null,wav:null,m4a:null,aac:null}},t.videoCodecs=function(){var e=document.createElement("video");return e.canPlayType?{ogg:e.canPlayType('video/ogg; codecs="theora"'),h264:e.canPlayType('video/mp4; codecs="avc1.42E01E"'),webm:e.canPlayType('video/webm; codecs="vp8, vorbis"')}:{ogg:null,h264:null,webm:null}},t.buildBrowserFeatureObject=function(e,t){return{userAgent:e[t.indexOf(a.Feature.USER_AGENT)],mimeTypes:e[t.indexOf(a.Feature.MIME_TYPES)],platform:e[t.indexOf(a.Feature.PLATFORM)],languages:e[t.indexOf(a.Feature.LANGUAGES)],screenProperties:e[t.indexOf(a.Feature.SCREEN_PROPERTIES)],touchScreen:e[t.indexOf(a.Feature.TOUCH_SCREEN)],videoCard:e[t.indexOf(a.Feature.VIDEO_CARD)],multimediaDevices:e[t.indexOf(a.Feature.MULTIMEDIA_DEVICES)],navigatorPrototype:e[t.indexOf(a.Feature.NAVIGATOR_PROTOTYPE)],evalToString:e[t.indexOf(a.Feature.EVAL_TO_STRING)],screenDesc:e[t.indexOf(a.Feature.SCREEN_DESC)],headlessProperties:e[t.indexOf(a.Feature.HEADLESS_PROPERTIES)],webdriver:e[t.indexOf(a.Feature.WEBDRIVER)],notificationPermissions:e[t.indexOf(a.Feature.NOTIFICATION_PERMISSIONS)],deviceMemory:e[t.indexOf(a.Feature.DEVICE_MEMORY)],audioCodecs:e[t.indexOf(a.Feature.AUDIO_CODECS)],videoCodecs:e[t.indexOf(a.Feature.VIDEO_CODECS)],canvasFingerprint:e[t.indexOf(a.Feature.CANVAS_FINGERPRINT)]}},t.validateFeatures=function(e){(0,c.featuresSchema)(e)}},740:function(e,t,n){var r=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(t,"__esModule",{value:!0}),t.canvasFingerprint=void 0;var i=r(n(202));t.canvasFingerprint=function(e){if(void 0===e&&(e=!0),!document)return console.error("Wrong environment"),Promise.resolve(null);var t=Math.floor(1e3*Math.random()),n="script-".concat(t),r="canvas-".concat(t),o="result-".concat(t),a=document.createElement("script"),c=document.createElement("canvas"),u=document.createElement("div");return u.id=o,a.id=n,c.id=r,c.width=200,c.height=40,a.text='\n        canvas = document.getElementById("'.concat(r,'");\n        result = document.getElementById("').concat(o,'");\n        script = document.getElementById("').concat(n,'");\n\n        ctx = canvas.getContext("2d");\n        \n        ctx.fillStyle = "rgb(255,0,255)";\n        ctx.beginPath();\n        ctx.rect(20, 20, 150, 100);\n        ctx.fill();\n        ctx.stroke();\n        ctx.closePath();\n        ctx.beginPath();\n        ctx.fillStyle = "rgb(0,255,255)";\n        ctx.arc(50, 50, 50, 0, Math.PI * 2, true);\n        ctx.fill();\n        ctx.stroke();\n        ctx.closePath();\n        \n        txt = \'abz190#$%^@Â£Ã©Ãº\';\n        ctx.textBaseline = "top";\n        ctx.font = \'17px "Arial 17"\';\n        ctx.textBaseline = "alphabetic";\n        ctx.fillStyle = "rgb(255,5,5)";\n        ctx.rotate(.03);\n        ctx.fillText(txt, 4, 17);\n        ctx.fillStyle = "rgb(155,255,5)";\n        ctx.shadowBlur=8;\n        ctx.shadowColor="red";\n        ctx.fillRect(20,12,100,5);\n        \n        // hashing function\n        src = canvas.toDataURL();\n        hash = 0;\n        \n        for (i = 0; i < src.length; i++) {\n            char = src.charCodeAt(i);\n            hash = ((hash<<5)-hash)+char;\n            hash = hash & hash;\n        }\n        \n        result.dataset.attribute = hash;\n    '),e&&(a.text="\n            ".concat(a.text,"\n\n            canvas.remove();\n            script.remove();\n        ")),document.documentElement.appendChild(u),document.documentElement.appendChild(c),document.documentElement.appendChild(a),(0,i.default)("#".concat(o)).then((function(e){return e.dataset.attribute}))}},817:(e,t)=>{var n;Object.defineProperty(t,"__esModule",{value:!0}),t.Feature=void 0,(n=t.Feature||(t.Feature={})).CANVAS_FINGERPRINT="Fingerprint.canvasFingerprint",n.USER_AGENT="Fingerprint.userAgent",n.MIME_TYPES="Fingerprint.mimeTypes",n.PLATFORM="Fingerprint.platform",n.LANGUAGES="Fingerprint.languages",n.SCREEN_PROPERTIES="Fingerprint.screenProperties",n.TOUCH_SCREEN="Fingerprint.touchScreen",n.MULTIMEDIA_DEVICES="Fingerprint.multimediaDevices",n.NAVIGATOR_PROTOTYPE="Fingerprint.navigatorPrototype",n.HEADLESS_PROPERTIES="Fingerprint.headlessProperties",n.NOTIFICATION_PERMISSIONS="Fingerprint.notificationPermissions",n.DEVICE_MEMORY="Fingerprint.deviceMemory",n.AUDIO_CODECS="Fingerprint.audioCodecs",n.VIDEO_CARD="Fingerprint.videoCard",n.VIDEO_CODECS="Fingerprint.videoCodecs",n.EVAL_TO_STRING="Fingerprint.evalToString",n.SCREEN_DESC="Fingerprint.screenDesc",n.WEBDRIVER="Fingerprint.webdriver"},325:(e,t)=>{Object.defineProperty(t,"__esModule",{value:!0}),t.default=function(e){var t=e.map((function(e){return"".concat(e,"()")})).join(",");return"\n        function onLibraryLoad(callback) {\n            if (Fingerprint) {\n                return callback();\n            }\n            \n            return setTimeout(onLibraryLoad, 500, callback);\n        }\n    \n        onLibraryLoad(() => Promise.all(\n            [".concat(t,"]\n        ))\n    ").replace(/([\t\n])/g,"").replace(/ +/g," ")}},997:function(e,t,n){var r=this&&this.__createBinding||(Object.create?function(e,t,n,r){void 0===r&&(r=n);var i=Object.getOwnPropertyDescriptor(t,n);i&&!("get"in i?!t.__esModule:i.writable||i.configurable)||(i={enumerable:!0,get:function(){return t[n]}}),Object.defineProperty(e,r,i)}:function(e,t,n,r){void 0===r&&(r=n),e[r]=t[n]}),i=this&&this.__exportStar||function(e,t){for(var n in e)"default"===n||Object.prototype.hasOwnProperty.call(t,n)||r(t,e,n)},o=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(t,"__esModule",{value:!0}),t.waitForElement=t.validate=t.gatherBrowserFeatures=t.Feature=t.canvasFingerprint=void 0,i(n(795),t);var a=n(740);Object.defineProperty(t,"canvasFingerprint",{enumerable:!0,get:function(){return a.canvasFingerprint}});var c=n(817);Object.defineProperty(t,"Feature",{enumerable:!0,get:function(){return c.Feature}});var u=n(325);Object.defineProperty(t,"gatherBrowserFeatures",{enumerable:!0,get:function(){return o(u).default}});var l=n(576);Object.defineProperty(t,"validate",{enumerable:!0,get:function(){return l.validate}});var s=n(202);Object.defineProperty(t,"waitForElement",{enumerable:!0,get:function(){return o(s).default}})},111:(e,t)=>{Object.defineProperty(t,"__esModule",{value:!0}),t.isHeadless=t.isHeadlessChrome=t.hasWebdriver=t.hasHeadlessProperties=t.isPhantomJS=void 0,t.isPhantomJS=function(e){return/PhantomJS/.test(e.userAgent)},t.hasHeadlessProperties=function(e){return Object.values(e.headlessProperties).some((function(e){return e}))},t.hasWebdriver=function(e){return e.webdriver},t.isHeadlessChrome=function(e){return/HeadlessChrome/.test(e.userAgent)},t.isHeadless=function(e){return!!((0,t.isPhantomJS)(e)||(0,t.hasHeadlessProperties)(e)||(0,t.hasWebdriver)(e)||(0,t.isHeadlessChrome)(e))}},923:function(e,t,n){var r=this&&this.__createBinding||(Object.create?function(e,t,n,r){void 0===r&&(r=n);var i=Object.getOwnPropertyDescriptor(t,n);i&&!("get"in i?!t.__esModule:i.writable||i.configurable)||(i={enumerable:!0,get:function(){return t[n]}}),Object.defineProperty(e,r,i)}:function(e,t,n,r){void 0===r&&(r=n),e[r]=t[n]}),i=this&&this.__setModuleDefault||(Object.create?function(e,t){Object.defineProperty(e,"default",{enumerable:!0,value:t})}:function(e,t){e.default=t}),o=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var t={};if(null!=e)for(var n in e)"default"!==n&&Object.prototype.hasOwnProperty.call(e,n)&&r(t,e,n);return i(t,e),t};Object.defineProperty(t,"__esModule",{value:!0}),t.featuresSchema=void 0;var a=o(n(62)),c=a.object({client:{height:a.number,width:a.number},screen:{availHeight:a.number,availWidth:a.number,colorDepth:a.number,height:a.number,pixelDepth:a.number,width:a.number},window:{devicePixelRation:a.number,innerHeight:a.number,innerWidth:a.number,outerHeight:a.number,outerWidth:a.number,pageXOffset:a.number,pageYOffset:a.number,screenX:a.number,screenY:a.number}}),u=a.object({canHandleTouchEvents:a.bool,maxTouchPoints:a.number,onTouchStart:a.bool}),l=a.object({deviceId:a.optional(a.string),groupId:a.optional(a.string),kind:a.optional(a.string),label:a.optional(a.string)}),s=a.object({name:a.optional(a.string),state:a.string}),d=a.object({aac:a.optional(a.string),m4a:a.optional(a.string),mp3:a.optional(a.string),ogg:a.optional(a.string),wav:a.optional(a.string)}),f=a.object({h264:a.optional(a.string),ogg:a.optional(a.string),webm:a.optional(a.string)}),p=a.object({renderer:a.optional(a.string),vendor:a.optional(a.string)});t.featuresSchema=a.object({canvasFingerprint:a.string,userAgent:a.string,mimeTypes:a.array(a.string),platform:a.string,languages:a.array(a.string),screenProperties:c,touchScreen:a.optional(u),multimediaDevices:a.optional(a.array(l)),navigatorPrototype:a.objectValues(a.string),headlessProperties:a.objectValues(a.bool),notificationPermissions:a.optional(s),deviceMemory:a.optional(a.number),audioCodecs:a.optional(d),videoCodecs:a.optional(f),videoCard:a.optional(p),evalToString:a.number,screenDesc:a.string,webdriver:a.optional(a.bool)})},576:(e,t,n)=>{Object.defineProperty(t,"__esModule",{value:!0}),t.validate=void 0;var r=n(795),i=n(111);t.validate=function(e,t,n){void 0===n&&(n=!0);var o=(0,r.buildBrowserFeatureObject)(e,t);return(0,r.validateFeatures)(o),!n||!(0,i.isHeadless)(o)}},62:function(e,t){var n,r=this&&this.__extends||(n=function(e,t){return n=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,t){e.__proto__=t}||function(e,t){for(var n in t)Object.prototype.hasOwnProperty.call(t,n)&&(e[n]=t[n])},n(e,t)},function(e,t){if("function"!=typeof t&&null!==t)throw new TypeError("Class extends value "+String(t)+" is not a constructor or null");function r(){this.constructor=e}n(e,t),e.prototype=null===t?Object.create(t):(r.prototype=t.prototype,new r)}),i=this&&this.__spreadArray||function(e,t,n){if(n||2===arguments.length)for(var r,i=0,o=t.length;i<o;i++)!r&&i in t||(r||(r=Array.prototype.slice.call(t,0,i)),r[i]=t[i]);return e.concat(r||Array.prototype.slice.call(t))};Object.defineProperty(t,"__esModule",{value:!0}),t.objectValues=t.object=t.array=t.number=t.string=t.bool=t.optional=void 0;var o=function(e){function t(t,n){var r=this,i=(null==n?void 0:n.length)?"[".concat(n.join("."),"]: ").concat(t):t;return(r=e.call(this,i)||this).path=n||[],r.error=t,r}return r(t,e),t}(Error),a=function(e,t){throw new o(e.error,i([t],e.path,!0))};t.optional=function(e){return function(t){null!=t&&""!==t&&e(t)}},t.bool=function(e){if("boolean"!=typeof e){if("string"==typeof e)throw new o("'".concat(e,"' is not a valid boolean"));throw new o("".concat(e," is not a valid boolean"))}},t.string=function(e){if("string"!=typeof e||""===e.trim())throw new o("".concat(e," is not a valid string"))},t.number=function(e){if("number"!=typeof e||isNaN(Number(e))){if("string"==typeof e)throw new o("'".concat(e,"' is not a valid number"));throw new o("".concat(e," is not a valid number"))}},t.array=function(e){return function(t){if(!Array.isArray(t))throw new o("".concat(t," is not a valid array"));t.forEach((function(t,n){try{e(t)}catch(e){a(e,"array[".concat(n.toString(),"]"))}}))}},t.object=function(e){return function(n){if(!n)throw new o("Not a valid object");Object.keys(e).forEach((function(r){if("object"!=typeof e[r])try{e[r](n[r])}catch(e){a(e,r)}else try{(0,t.object)(e[r])(n[r])}catch(e){a(e,r)}}))}},t.objectValues=function(e){return function(t){if(!t)throw new o("Not a valid object");if("object"!=typeof t||Array.isArray(t))throw new o("Not a valid object");Object.entries(t).forEach((function(t){var n=t[0],r=t[1];try{e(r)}catch(e){a(e,n)}}))}}},202:function(e,t){var n=this&&this.__awaiter||function(e,t,n,r){return new(n||(n=Promise))((function(i,o){function a(e){try{u(r.next(e))}catch(e){o(e)}}function c(e){try{u(r.throw(e))}catch(e){o(e)}}function u(e){var t;e.done?i(e.value):(t=e.value,t instanceof n?t:new n((function(e){e(t)}))).then(a,c)}u((r=r.apply(e,t||[])).next())}))},r=this&&this.__generator||function(e,t){var n,r,i,o,a={label:0,sent:function(){if(1&i[0])throw i[1];return i[1]},trys:[],ops:[]};return o={next:c(0),throw:c(1),return:c(2)},"function"==typeof Symbol&&(o[Symbol.iterator]=function(){return this}),o;function c(c){return function(u){return function(c){if(n)throw new TypeError("Generator is already executing.");for(;o&&(o=0,c[0]&&(a=0)),a;)try{if(n=1,r&&(i=2&c[0]?r.return:c[0]?r.throw||((i=r.return)&&i.call(r),0):r.next)&&!(i=i.call(r,c[1])).done)return i;switch(r=0,i&&(c=[2&c[0],i.value]),c[0]){case 0:case 1:i=c;break;case 4:return a.label++,{value:c[1],done:!1};case 5:a.label++,r=c[1],c=[0];continue;case 7:c=a.ops.pop(),a.trys.pop();continue;default:if(!((i=(i=a.trys).length>0&&i[i.length-1])||6!==c[0]&&2!==c[0])){a=0;continue}if(3===c[0]&&(!i||c[1]>i[0]&&c[1]<i[3])){a.label=c[1];break}if(6===c[0]&&a.label<i[1]){a.label=i[1],i=c;break}if(i&&a.label<i[2]){a.label=i[2],a.ops.push(c);break}i[2]&&a.ops.pop(),a.trys.pop();continue}c=t.call(e,a)}catch(e){c=[6,e],r=0}finally{n=i=0}if(5&c[0])throw c[1];return{value:c[0]?c[1]:void 0,done:!0}}([c,u])}}};Object.defineProperty(t,"__esModule",{value:!0}),t.default=function(e){return n(void 0,void 0,void 0,(function(){return r(this,(function(t){switch(t.label){case 0:return null!==document.querySelector(e)?[3,2]:[4,new Promise((function(e){return requestAnimationFrame(e)}))];case 1:return t.sent(),[3,0];case 2:return[2,document.querySelector(e)]}}))}))}}},t={};return function n(r){var i=t[r];if(void 0!==i)return i.exports;var o=t[r]={exports:{}};return e[r].call(o.exports,o,o.exports,n),o.exports}(997)})()));

In [29]:
if not areas:  # Check if areas is an empty list or None
    print(f"no area found for {s}")

no area found for mohammed-naguib-axis

In [9]:
# Trying to extract the areas from each the district pages 
try:
    scraper = SmartScraper(config)
    districts_soup = scraper.scrape_multiple_pages(district_slugs)

finally:
    scraper.close()

Page 1/40
Trying fast approach (requests)...
Response status: 200, length: 5563533
Content looks valid, using requests response
Success with requests!

Page 2/40
Trying fast approach (requests)...
Response status: 200, length: 5494115
Content looks valid, using requests response
Success with requests!

Page 3/40
Trying fast approach (requests)...
Response status: 200, length: 5555259
Content looks valid, using requests response
Success with requests!

Page 4/40
Trying fast approach (requests)...
Response status: 200, length: 5549962
Content looks valid, using requests response
Success with requests!

Page 5/40
Trying fast approach (requests)...
Response status: 200, length: 5530519
Content looks valid, using requests response
Success with requests!

Page 6/40
Trying fast approach (requests)...
Response status: 200, length: 5490368
Content looks valid, using requests response
Success with requests!

Page 7/40
Trying fast approach (requests)...
Response status: 200, length: 5560924
Content looks valid, using requests response
Success with requests!

Page 8/40
Trying fast approach (requests)...
Response status: 200, length: 5530042
Content looks valid, using requests response
Success with requests!

Page 9/40
Trying fast approach (requests)...
Response status: 200, length: 5503286
Content looks valid, using requests response
Success with requests!

Page 10/40
Trying fast approach (requests)...
Response status: 200, length: 5534469
Content looks valid, using requests response
Success with requests!

Page 11/40
Trying fast approach (requests)...
Response status: 200, length: 5487224
Content looks valid, using requests response
Success with requests!

Page 12/40
Trying fast approach (requests)...
Response status: 200, length: 5512239
Content looks valid, using requests response
Success with requests!

Page 13/40
Trying fast approach (requests)...
Response status: 200, length: 5455034
Content looks valid, using requests response
Success with requests!

Page 14/40
Trying fast approach (requests)...
Response status: 200, length: 5536526
Content looks valid, using requests response
Success with requests!

Page 15/40
Trying fast approach (requests)...
Response status: 200, length: 5456891
Content looks valid, using requests response
Success with requests!

Page 16/40
Trying fast approach (requests)...
Response status: 200, length: 5551677
Content looks valid, using requests response
Success with requests!

Page 17/40
Trying fast approach (requests)...
Response status: 200, length: 5488582
Content looks valid, using requests response
Success with requests!

Page 18/40
Trying fast approach (requests)...
Response status: 200, length: 5463547
Content looks valid, using requests response
Success with requests!

Page 19/40
Trying fast approach (requests)...
Response status: 200, length: 5438156
Content looks valid, using requests response
Success with requests!

Page 20/40
Trying fast approach (requests)...
Response status: 200, length: 5401761
Content looks valid, using requests response
Success with requests!

Page 21/40
Trying fast approach (requests)...
Response status: 200, length: 5423131
Content looks valid, using requests response
Success with requests!

Page 22/40
Trying fast approach (requests)...
Response status: 200, length: 5472034
Content looks valid, using requests response
Success with requests!

Page 23/40
Trying fast approach (requests)...
Response status: 200, length: 5405240
Content looks valid, using requests response
Success with requests!

Page 24/40
Trying fast approach (requests)...
Response status: 200, length: 5441859
Content looks valid, using requests response
Success with requests!

Page 25/40
Trying fast approach (requests)...
Response status: 200, length: 5417697
Content looks valid, using requests response
Success with requests!

Page 26/40
Trying fast approach (requests)...
Response status: 200, length: 5413716
Content looks valid, using requests response
Success with requests!

Page 27/40
Trying fast approach (requests)...
Response status: 200, length: 5460496
Content looks valid, using requests response
Success with requests!

Page 28/40
Trying fast approach (requests)...
Response status: 200, length: 5361656
Content looks valid, using requests response
Success with requests!

Page 29/40
Trying fast approach (requests)...
Response status: 200, length: 5411095
Content looks valid, using requests response
Success with requests!

Page 30/40
Trying fast approach (requests)...
Response status: 200, length: 5483412
Content looks valid, using requests response
Success with requests!

Page 31/40
Trying fast approach (requests)...
Response status: 200, length: 5418072
Content looks valid, using requests response
Success with requests!

Page 32/40
Trying fast approach (requests)...
Response status: 200, length: 5470255
Content looks valid, using requests response
Success with requests!

Page 33/40
Trying fast approach (requests)...
Response status: 200, length: 5418286
Content looks valid, using requests response
Success with requests!

Page 34/40
Trying fast approach (requests)...
Response status: 200, length: 5408498
Content looks valid, using requests response
Success with requests!

Page 35/40
Trying fast approach (requests)...
Response status: 200, length: 5483813
Content looks valid, using requests response
Success with requests!

Page 36/40
Trying fast approach (requests)...
Response status: 200, length: 5436441
Content looks valid, using requests response
Success with requests!

Page 37/40
Trying fast approach (requests)...
Response status: 200, length: 5437585
Content looks valid, using requests response
Success with requests!

Page 38/40
Trying fast approach (requests)...
Response status: 200, length: 5500080
Content looks valid, using requests response
Success with requests!

Page 39/40
Trying fast approach (requests)...
Response status: 200, length: 5488253
Content looks valid, using requests response
Success with requests!

Page 40/40
Trying fast approach (requests)...
Response status: 200, length: 5474197
Content looks valid, using requests response
Success with requests!

In [14]:
for i, district in enumerate(districts_list):
    district['soup'] = districts_soup[i]

In [15]:
len(districts_soup)

40

In [36]:
len(districts_list)

40

In [16]:
locations = []
number_of_districts = len(districts_list)
for district in districts_list:
    district_slug = district['link'][15:-1]
    district_name = district['name']
    soup2 = district['soup']
    areas_list = get_sub_locations(
        soup2, neighborhood=True, 
        number_of_districts = number_of_districts,  
        parent_location_name=district_name
        )
    
    locations.append({'district': district_name, 'slug': district_slug, 'areas': areas_list})
    print(f'Finished extracting areas for district {district_name}')

C:\Users\marwa\AppData\Local\Temp\ipykernel_28164\1727533725.py:24: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  if len(location.findAll('span')) < 2:

Finished extracting areas for district New Cairo
Finished extracting areas for district Madinaty
Finished extracting areas for district Mostakbal City
Finished extracting areas for district New Capital City
Finished extracting areas for district Shorouk City
Finished extracting areas for district Nasr City
Finished extracting areas for district Katameya
Finished extracting areas for district New Heliopolis
Finished extracting areas for district Maadi
Finished extracting areas for district Sheraton
Finished extracting areas for district Zahraa Al Maadi
Finished extracting areas for district Mokattam
Finished extracting areas for district Heliopolis
Finished extracting areas for district Obour City
Finished extracting areas for district Badr City
Finished extracting areas for district El Fostat
Finished extracting areas for district Zamalek
Finished extracting areas for district New Nozha
Finished extracting areas for district Ain Shams
Finished extracting areas for district Hadayek al-Kobba
Finished extracting areas for district Hadayeq El Zeitoun
Finished extracting areas for district Al Manial
Finished extracting areas for district Gesr Al Suez
Finished extracting areas for district Downtown Cairo
Finished extracting areas for district Almazah
Finished extracting areas for district Shubra
Finished extracting areas for district Helmeyat El Zaytoun
Finished extracting areas for district Marg
Finished extracting areas for district Helwan
Finished extracting areas for district Nozha
Finished extracting areas for district Salam City
Finished extracting areas for district Hadayek Helwan
Finished extracting areas for district Abasiya
Finished extracting areas for district 15 May City
Finished extracting areas for district Masr al-Kadema
Finished extracting areas for district Matareya
Finished extracting areas for district Rod al-Farag
Finished extracting areas for district Boulaq Abo El Ela
Finished extracting areas for district Garden City
Finished extracting areas for district Basateen

[{'district': 'New Cairo', 'slug': 'new-cairo', 'areas': [{'slug': '5th-settlement', 'name': '5th Settlement', 'count': '(44621)', 'neighborhoods': None}, {'slug': '1st-settlement', 'name': '1st Settlement', 'count': '(5840)', 'neighborhoods': None}, {'slug': 'rehab-city', 'name': 'Rehab City', 'count': '(5145)', 'neighborhoods': None}, {'slug': '6th-settlement', 'name': '6th Settlement', 'count': '(1562)', 'neighborhoods': None}, {'slug': '3rd-settlement', 'name': '3rd Settlement', 'count': '(362)', 'neighborhoods': None}, {'slug': 'hyde-park-central', 'name': 'Hyde Park Central', 'count': '(202)', 'neighborhoods': None}, {'slug': 'ozone-medical-center', 'name': 'Ozone Medical Center', 'count': '(58)', 'neighborhoods': None}, {'slug': 'mohammed-naguib-axis', 'name': 'Mohammed Naguib Axis', 'count': '(53)', 'neighborhoods': None}, {'slug': 'gamal-abd-al-nasser-axis', 'name': 'Gamal Abd Al-Nasser Axis', 'count': '(42)', 'neighborhoods': None}, {'slug': 'dijar', 'name': 'Dijar', 'count': '(36)', 'neighborhoods': None}, {'slug': 'el-patio-vida', 'name': 'El Patio Vida', 'count': '(27)', 'neighborhoods': None}, {'slug': 'mall-top-90', 'name': 'Mall Top 90', 'count': '(23)', 'neighborhoods': None}, {'slug': 'town-residence', 'name': 'Town Residence', 'count': '(23)', 'neighborhoods': None}, {'slug': 'the-mornings', 'name': 'The Mornings', 'count': '(14)', 'neighborhoods': None}, {'slug': 'w-signature', 'name': 'W Signature', 'count': '(13)', 'neighborhoods': None}, {'slug': 'loaloa', 'name': 'Loaloa', 'count': '(11)', 'neighborhoods': None}, {'slug': 'top-view', 'name': 'Top view', 'count': '(11)', 'neighborhoods': None}, {'slug': 'lotus-compound', 'name': 'Lotus Compound', 'count': '(9)', 'neighborhoods': None}, {'slug': 'prk-vie', 'name': 'Prk Vie', 'count': '(5)', 'neighborhoods': None}, {'slug': 'green-house', 'name': 'Green House', 'count': '(4)', 'neighborhoods': None}, {'slug': 'kemet', 'name': 'Kemet', 'count': '(3)', 'neighborhoods': None}]}, {'district': 'Madinaty', 'slug': 'madinaty', 'areas': [{'slug': 'privado', 'name': 'Privado', 'count': '(616)', 'neighborhoods': None}]}, {'district': 'Mostakbal City', 'slug': 'mostakbal-city', 'areas': [{'slug': 'sarai', 'name': 'Sarai', 'count': '(2535)', 'neighborhoods': None}, {'slug': 'bloomfields', 'name': 'Bloomfields', 'count': '(847)', 'neighborhoods': None}, {'slug': 'l-avenir', 'name': 'L’Avenir', 'count': '(358)', 'neighborhoods': None}, {'slug': 'haptown', 'name': 'Haptown', 'count': '(215)', 'neighborhoods': None}, {'slug': 'monte-napoleon', 'name': 'Monte Napoleon', 'count': '(198)', 'neighborhoods': None}, {'slug': 'aliva-mostakbal-city', 'name': 'Aliva mostakbal city', 'count': '(194)', 'neighborhoods': None}, {'slug': 'green-square', 'name': 'Green Square', 'count': '(193)', 'neighborhoods': None}, {'slug': 'capital-gardens', 'name': 'Capital Gardens', 'count': '(173)', 'neighborhoods': None}, {'slug': 'the-butterfly', 'name': 'The Butterfly', 'count': '(162)', 'neighborhoods': None}, {'slug': 'park-central', 'name': 'Park Central', 'count': '(121)', 'neighborhoods': None}, {'slug': 'the-wonder-marq', 'name': 'The Wonder MarQ', 'count': '(91)', 'neighborhoods': None}, {'slug': 'zizinia-el-mostakbal', 'name': 'Zizinia El Mostakbal', 'count': '(80)', 'neighborhoods': None}, {'slug': 'la-mirada-2', 'name': 'La Mirada', 'count': '(66)', 'neighborhoods': None}, {'slug': 'the-valleys', 'name': 'The Valleys', 'count': '(62)', 'neighborhoods': None}, {'slug': 'east-vale-sodic', 'name': 'East vale sodic', 'count': '(58)', 'neighborhoods': None}, {'slug': 'il-bosco-city', 'name': 'IL Bosco City', 'count': '(55)', 'neighborhoods': None}, {'slug': 'beta-greens', 'name': 'Beta Greens', 'count': '(53)', 'neighborhoods': None}, {'slug': 'scenes', 'name': 'Scenes', 'count': '(40)', 'neighborhoods': None}, {'slug': 'cityzen', 'name': 'CityZen', 'count': '(38)', 'neighborhoods': None}, {'slug': 'mountain-view-5', 'name': 'Mountain View', 'count': '(32)', 'neighborhoods': None}, {'slug': 'talda-mostakbal-city', 'name': 'Talda Mostakbal City', 'count': '(30)', 'neighborhoods': None}, {'slug': 'neopolis', 'name': 'Neopolis', 'count': '(25)', 'neighborhoods': None}, {'slug': 'nyoum-mostakbal-city', 'name': 'Nyoum Mostakbal City', 'count': '(21)', 'neighborhoods': None}, {'slug': 'rosail-city', 'name': 'Rosail City', 'count': '(19)', 'neighborhoods': None}, {'slug': 'at-east', 'name': 'At East', 'count': '(19)', 'neighborhoods': None}, {'slug': 'the-101', 'name': 'The 101', 'count': '(12)', 'neighborhoods': None}, {'slug': 'monark-residence', 'name': 'Monark Residence', 'count': '(11)', 'neighborhoods': None}, {'slug': 'kukun', 'name': 'Kukun', 'count': '(11)', 'neighborhoods': None}, {'slug': 'elaia', 'name': 'Elaia', 'count': '(9)', 'neighborhoods': None}, {'slug': 'odyssia', 'name': 'Odyssia', 'count': '(8)', 'neighborhoods': None}, {'slug': 'isola-quattro', 'name': 'Isola Quattro', 'count': '(7)', 'neighborhoods': None}, {'slug': 'rare', 'name': 'Rare', 'count': '(6)', 'neighborhoods': None}, {'slug': 'neo-gardens', 'name': 'Neo Gardens', 'count': '(5)', 'neighborhoods': None}, {'slug': 'the-ridge', 'name': 'The Ridge', 'count': '(4)', 'neighborhoods': None}, {'slug': 'alaire', 'name': 'Alaire', 'count': '(3)', 'neighborhoods': None}, {'slug': 'aria-2', 'name': 'Aria Compound', 'count': '(3)', 'neighborhoods': None}, {'slug': 'red', 'name': 'Red', 'count': '(2)', 'neighborhoods': None}, {'slug': 'the-marquette-mostakbal-city', 'name': 'The Marquette', 'count': '(1)', 'neighborhoods': None}]}, {'district': 'New Capital City', 'slug': 'new-capital-city', 'areas': [{'slug': 'la-vista-city', 'name': 'La Vista City', 'count': '(735)', 'neighborhoods': None}, {'slug': 'al-maqsad', 'name': 'Al Maqsad', 'count': '(660)', 'neighborhoods': None}, {'slug': 'noor-city-2', 'name': 'Noor City', 'count': '(618)', 'neighborhoods': None}, {'slug': 'r8', 'name': 'R8', 'count': '(310)', 'neighborhoods': None}, {'slug': 'new-garden-city', 'name': 'New Garden City', 'count': '(243)', 'neighborhoods': None}, {'slug': 'il-bosco', 'name': 'IL Bosco', 'count': '(167)', 'neighborhoods': None}, {'slug': 'r3', 'name': 'R3', 'count': '(113)', 'neighborhoods': None}, {'slug': 'celia', 'name': 'Celia', 'count': '(108)', 'neighborhoods': None}, {'slug': 'r7', 'name': 'R7', 'count': '(96)', 'neighborhoods': None}, {'slug': 'r4', 'name': 'R4', 'count': '(91)', 'neighborhoods': None}, {'slug': 'taj-tower', 'name': 'Taj Tower', 'count': '(87)', 'neighborhoods': None}, {'slug': 'pyramids-mall', 'name': 'Pyramids Mall', 'count': '(63)', 'neighborhoods': None}, {'slug': 'de-joya', 'name': 'De Joya 1', 'count': '(62)', 'neighborhoods': None}, {'slug': 'granville', 'name': 'Granville', 'count': '(55)', 'neighborhoods': None}, {'slug': 'oia', 'name': 'OIA', 'count': '(54)', 'neighborhoods': None}, {'slug': 'sage-lakes', 'name': 'Sage Lakes', 'count': '(50)', 'neighborhoods': None}, {'slug': 'capital-gardens-2', 'name': 'Capital Gardens', 'count': '(43)', 'neighborhoods': None}, {'slug': 'blue-vert', 'name': 'Blue Vert', 'count': '(43)', 'neighborhoods': None}, {'slug': 'rivan', 'name': 'Rivan', 'count': '(43)', 'neighborhoods': None}, {'slug': 'armonia', 'name': 'Armonia', 'count': '(42)', 'neighborhoods': None}, {'slug': 'la-capital', 'name': 'La Capital', 'count': '(40)', 'neighborhoods': None}, {'slug': 'vinci', 'name': 'Vinci', 'count': '(39)', 'neighborhoods': None}, {'slug': 'financial-district', 'name': 'Financial District', 'count': '(36)', 'neighborhoods': None}, {'slug': 'mu23', 'name': 'MU23', 'count': '(31)', 'neighborhoods': None}, {'slug': 'mountain-view-3', 'name': 'Mountain View', 'count': '(30)', 'neighborhoods': None}, {'slug': 'hava', 'name': 'Hava', 'count': '(30)', 'neighborhoods': None}, {'slug': 'palm-hills-new-capital', 'name': 'Palm Hills New Capital', 'count': '(28)', 'neighborhoods': None}, {'slug': 'the-capital-way', 'name': 'The Capital Way', 'count': '(27)', 'neighborhoods': None}, {'slug': 'downtown-2', 'name': 'Downtown', 'count': '(26)', 'neighborhoods': None}, {'slug': 'midtown-sky', 'name': 'Midtown Sky', 'count': '(24)', 'neighborhoods': None}, {'slug': 'scenario', 'name': 'Scenario', 'count': '(24)', 'neighborhoods': None}, {'slug': 'golden-tower', 'name': 'Golden Tower', 'count': '(21)', 'neighborhoods': None}, {'slug': 'canyon-8', 'name': 'Canyon 8', 'count': '(17)', 'neighborhoods': None}, {'slug': 'midtown-condo', 'name': 'Midtown Condo', 'count': '(17)', 'neighborhoods': None}, {'slug': 'lumia-residence', 'name': 'Lumia Residence', 'count': '(16)', 'neighborhoods': None}, {'slug': 'scene-7', 'name': 'Scene 7', 'count': '(16)', 'neighborhoods': None}, {'slug': 'venia', 'name': 'Venia', 'count': '(16)', 'neighborhoods': None}, {'slug': 'government-district', 'name': 'Government District', 'count': '(15)', 'neighborhoods': None}, {'slug': 'la-reva', 'name': 'La Reva', 'count': '(15)', 'neighborhoods': None}, {'slug': 'catalan', 'name': 'Catalan', 'count': '(14)', 'neighborhoods': None}]}, {'district': 'Shorouk City', 'slug': 'shorouk-city', 'areas': [{'slug': 'al-burouj', 'name': 'Al Burouj', 'count': '(1108)', 'neighborhoods': None}, {'slug': 'wesal', 'name': 'Wesal', 'count': '(508)', 'neighborhoods': None}, {'slug': 'maadi-view', 'name': 'Maadi View', 'count': '(252)', 'neighborhoods': None}, {'slug': 'el-patio-sola', 'name': 'El Patio Sola', 'count': '(119)', 'neighborhoods': None}, {'slug': 'el-patio-5', 'name': 'EL Patio 5', 'count': '(111)', 'neighborhoods': None}, {'slug': 'aljar-2', 'name': 'Aljar', 'count': '(90)', 'neighborhoods': None}, {'slug': 'el-patio-prime', 'name': 'EL Patio Prime', 'count': '(85)', 'neighborhoods': None}, {'slug': 'el-patio-casa', 'name': 'EL Patio Casa', 'count': '(78)', 'neighborhoods': None}, {'slug': 'divina-gardens', 'name': 'Divina Gardens', 'count': '(63)', 'neighborhoods': None}, {'slug': 'cleopatra-palace', 'name': 'Cleopatra Palace', 'count': '(55)', 'neighborhoods': None}, {'slug': 'el-shorouk-2000', 'name': 'El Shorouk 2000', 'count': '(52)', 'neighborhoods': None}, {'slug': 'palm-island', 'name': 'Palm Island', 'count': '(36)', 'neighborhoods': None}, {'slug': 'granda-alshorouk', 'name': 'Granda Alshorouk', 'count': '(27)', 'neighborhoods': None}, {'slug': 'palencia', 'name': 'Palencia', 'count': '(22)', 'neighborhoods': None}, {'slug': 'granda-life', 'name': 'Granda Life', 'count': '(22)', 'neighborhoods': None}, {'slug': 'town-center-el-shorouk-mall', 'name': 'Town Center El-Shorouk Mall', 'count': '(20)', 'neighborhoods': None}, {'slug': 'ivy-residence', 'name': 'Ivy Residence', 'count': '(19)', 'neighborhoods': None}, {'slug': 'palm-capital', 'name': 'Palm Capital', 'count': '(16)', 'neighborhoods': None}, {'slug': 'mercado-mall', 'name': 'Mercado Mall', 'count': '(13)', 'neighborhoods': None}, {'slug': 'el-shorouk-springs', 'name': 'El Shorouk Springs', 'count': '(13)', 'neighborhoods': None}, {'slug': 'shorouk-gardens', 'name': 'Shorouk Gardens', 'count': '(13)', 'neighborhoods': None}, {'slug': 'dar-misr-6', 'name': 'Dar Misr', 'count': '(12)', 'neighborhoods': None}, {'slug': 'panorama-el-shorouk', 'name': 'Panorama El Shorouk', 'count': '(11)', 'neighborhoods': None}, {'slug': 'arena-mall', 'name': 'Arena Mall', 'count': '(11)', 'neighborhoods': None}, {'slug': 'heliopolis-residence', 'name': 'Heliopolis Residence', 'count': '(10)', 'neighborhoods': None}, {'slug': 'moon-yard-mall', 'name': 'Moon Yard Mall', 'count': '(10)', 'neighborhoods': None}, {'slug': 'meraki-residence', 'name': 'Meraki Residence', 'count': '(9)', 'neighborhoods': None}, {'slug': 'may-fair-2', 'name': 'May Fair', 'count': '(9)', 'neighborhoods': None}, {'slug': 'el-shorouk-resort', 'name': 'El Shorouk Resort', 'count': '(8)', 'neighborhoods': None}, {'slug': 'beverly-hills-2', 'name': 'Beverly Hills', 'count': '(7)', 'neighborhoods': None}, {'slug': 'hayah-residence-2', 'name': 'Hayah Residence Compound', 'count': '(7)', 'neighborhoods': None}, {'slug': 'el-patio-4', 'name': 'EL Patio 4', 'count': '(6)', 'neighborhoods': None}, {'slug': 'stella-heliopolis', 'name': 'Stella Heliopolis', 'count': '(6)', 'neighborhoods': None}, {'slug': 'nakheel-residence', 'name': 'Nakheel Residence', 'count': '(5)', 'neighborhoods': None}, {'slug': 'janna-5', 'name': 'Janna', 'count': '(5)', 'neighborhoods': None}, {'slug': '1st-district-shorouk-city', 'name': '1st District', 'count': '(5)', 'neighborhoods': None}, {'slug': 'vivens', 'name': 'VIVENS', 'count': '(4)', 'neighborhoods': None}, {'slug': '5th-district-shorouk-city', 'name': '5th District', 'count': '(4)', 'neighborhoods': None}, {'slug': 'life-view', 'name': 'Life View', 'count': '(4)', 'neighborhoods': None}, {'slug': '6th-zone-shorouk-city', 'name': '6th Zone', 'count': '(3)', 'neighborhoods': None}]}, {'district': 'Nasr City', 'slug': 'nasr-city', 'areas': [{'slug': 'gardenia', 'name': 'Gardenia Compound', 'count': '(195)', 'neighborhoods': None}, {'slug': 'zahraa-madinat-nasr', 'name': 'Zahraa Madinat Nasr', 'count': '(64)', 'neighborhoods': None}, {'slug': 'al-waha-city', 'name': 'Al Waha City', 'count': '(47)', 'neighborhoods': None}, {'slug': 'tag-sultan-2', 'name': 'Tag Sultan', 'count': '(44)', 'neighborhoods': None}, {'slug': 'degla-landmark', 'name': 'Degla Landmark Compound', 'count': '(43)', 'neighborhoods': None}, {'slug': '8th-district-3', 'name': '8th District', 'count': '(35)', 'neighborhoods': None}, {'slug': 'makram-ebeid-st-nasr-city', 'name': 'Makram Ebeid St.', 'count': '(18)', 'neighborhoods': None}, {'slug': 'al-sefarat-district', 'name': 'Al Sefarat District', 'count': '(11)', 'neighborhoods': None}, {'slug': '1st-zone-nasr-city', 'name': '1st Zone', 'count': '(11)', 'neighborhoods': None}, {'slug': 'degla-towers', 'name': 'Degla Towers Compound', 'count': '(10)', 'neighborhoods': None}, {'slug': '10th-district-3', 'name': '10th District', 'count': '(9)', 'neighborhoods': None}, {'slug': 'true', 'name': 'True', 'count': '(6)', 'neighborhoods': None}, {'slug': '6th-district-nasr-city', 'name': '6th District', 'count': '(5)', 'neighborhoods': None}, {'slug': '7th-district-nasr-city', 'name': '7th District', 'count': '(5)', 'neighborhoods': None}, {'slug': 'capital-east-residence', 'name': 'Capital East Residence', 'count': '(4)', 'neighborhoods': None}, {'slug': '8th-zone-nasr-city', 'name': '8th Zone', 'count': '(3)', 'neighborhoods': None}, {'slug': '9th-zone-nasr-city', 'name': '9th Zone', 'count': '(3)', 'neighborhoods': None}, {'slug': 'shalya', 'name': 'Shalya', 'count': '(2)', 'neighborhoods': None}, {'slug': 'el-estad-nasr-city', 'name': 'El Estad', 'count': '(2)', 'neighborhoods': None}, {'slug': 'rabaa-al-adaweyah-nasr-city', 'name': 'Rabaa Al Adaweyah', 'count': '(2)', 'neighborhoods': None}, {'slug': 'al-nadi-al-ahly-nasr-city', 'name': 'Al Nadi Al Ahly', 'count': '(2)', 'neighborhoods': None}, {'slug': 'nasr-city-towers-nasr-city', 'name': 'Nasr City Towers', 'count': '(2)', 'neighborhoods': None}, {'slug': 'al-tayaran-st-nasr-city', 'name': 'Al Tayaran St.', 'count': '(2)', 'neighborhoods': None}, {'slug': 'cairo-town', 'name': 'Cairo Town Compound', 'count': '(1)', 'neighborhoods': None}, {'slug': 'al-saaa-square-nasr-city', 'name': 'Al Saaa Square', 'count': '(1)', 'neighborhoods': None}]}, {'district': 'Katameya', 'slug': 'katameya', 'areas': [{'slug': 'stone-residence-compound', 'name': 'Stone Residence Compound', 'count': '(611)', 'neighborhoods': None}, {'slug': 'stone-park-compound', 'name': 'Stone Park Compound', 'count': '(333)', 'neighborhoods': None}, {'slug': 'one-kattameya', 'name': 'One Katameya', 'count': '(294)', 'neighborhoods': None}, {'slug': 'katameya-heights-compound', 'name': 'Katameya Heights Compound', 'count': '(186)', 'neighborhoods': None}, {'slug': 'cairo-festival-city', 'name': 'Cairo Festival City Compound', 'count': '(180)', 'neighborhoods': None}, {'slug': 'the-brooks', 'name': 'The Brooks', 'count': '(93)', 'neighborhoods': None}, {'slug': 'gharb-golf', 'name': 'West Golf Compound', 'count': '(55)', 'neighborhoods': None}, {'slug': 'sama', 'name': 'Sama', 'count': '(48)', 'neighborhoods': None}, {'slug': 'kattameya-gate', 'name': 'Katameya Gate', 'count': '(34)', 'neighborhoods': None}, {'slug': 'gharb-golf-extension-compound', 'name': 'Gharb Golf & Extension Compound', 'count': '(22)', 'neighborhoods': None}, {'slug': 'palm-city', 'name': 'Palm City', 'count': '(14)', 'neighborhoods': None}, {'slug': 'knights', 'name': 'Knights', 'count': '(13)', 'neighborhoods': None}, {'slug': 'business-one', 'name': 'Business one', 'count': '(12)', 'neighborhoods': None}, {'slug': 'maadi-gardens', 'name': 'Maadi Gardens', 'count': '(11)', 'neighborhoods': None}, {'slug': 'sarayat-el-kattameya', 'name': 'Sarayat El Katameya', 'count': '(10)', 'neighborhoods': None}, {'slug': 'lereve', 'name': 'Lereve', 'count': '(4)', 'neighborhoods': None}, {'slug': 'the-brooks-compound', 'name': 'The Brooks Compound', 'count': '(1)', 'neighborhoods': None}, {'slug': 'arabella-park', 'name': 'Arabella Park Compound', 'count': '(1)', 'neighborhoods': None}]}, {'district': 'New Heliopolis', 'slug': 'new-heliopolis', 'areas': [{'slug': 'sodic-east', 'name': 'Sodic East', 'count': '(1018)', 'neighborhoods': None}, {'slug': 'talala', 'name': 'Talala', 'count': '(545)', 'neighborhoods': None}, {'slug': 'stella-compounds-2', 'name': 'Stella Compounds', 'count': '(28)', 'neighborhoods': None}, {'slug': 'new-kairo', 'name': 'New kairo', 'count': '(11)', 'neighborhoods': None}, {'slug': 'helioeye', 'name': 'Helioeye', 'count': '(8)', 'neighborhoods': None}, {'slug': 'korba-heights', 'name': 'Korba Heights', 'count': '(6)', 'neighborhoods': None}, {'slug': '6th-district-new-heliopolis', 'name': '6th District', 'count': '(4)', 'neighborhoods': None}, {'slug': 'jewels', 'name': 'Jewels', 'count': '(4)', 'neighborhoods': None}, {'slug': 'rock-white', 'name': 'Rock White', 'count': '(2)', 'neighborhoods': None}, {'slug': '1st-district-new-heliopolis', 'name': '1st District', 'count': '(2)', 'neighborhoods': None}, {'slug': '2nd-district-new-heliopolis', 'name': '2nd District', 'count': '(2)', 'neighborhoods': None}, {'slug': '9th-district-new-heliopolis', 'name': '9th District', 'count': '(1)', 'neighborhoods': None}, {'slug': 'al-gamea-square-new-heliopolis', 'name': 'Al Gamea Square', 'count': '(1)', 'neighborhoods': None}, {'slug': 'la-vida', 'name': 'La Vida', 'count': '(1)', 'neighborhoods': None}, {'slug': 'lavida', 'name': 'Lavida', 'count': '(1)', 'neighborhoods': None}]}, {'district': 'Maadi', 'slug': 'maadi', 'areas': [{'slug': 'new-maadi', 'name': 'New Maadi', 'count': '(263)', 'neighborhoods': None}, {'slug': 'corniche-el-maadi', 'name': 'Corniche El Maadi', 'count': '(261)', 'neighborhoods': None}, {'slug': 'sarayat-el-maadi', 'name': 'Sarayat El Maadi', 'count': '(183)', 'neighborhoods': None}, {'slug': 'degla', 'name': 'Degla', 'count': '(173)', 'neighborhoods': None}, {'slug': 'reve-du-nil', 'name': 'Reve du nil', 'count': '(95)', 'neighborhoods': None}, {'slug': 'baron-city-2', 'name': 'Baron City', 'count': '(46)', 'neighborhoods': None}, {'slug': 'al-lasilki', 'name': 'Al Lasilki', 'count': '(25)', 'neighborhoods': None}, {'slug': 'hayat-degla', 'name': 'Hayat Degla', 'count': '(18)', 'neighborhoods': None}, {'slug': 'nerko-al-maadi', 'name': 'Nerko Al Maadi', 'count': '(17)', 'neighborhoods': None}, {'slug': 'hadayek-el-maadi', 'name': 'Hadayek El Maadi', 'count': '(12)', 'neighborhoods': None}]}, {'district': 'Sheraton', 'slug': 'sheraton', 'areas': [{'slug': 'stoda-residence', 'name': 'Stoda Residence', 'count': '(551)', 'neighborhoods': None}, {'slug': 'isola-2', 'name': 'Isola', 'count': '(178)', 'neighborhoods': None}, {'slug': 'valore-sheraton', 'name': 'Valore Sheraton', 'count': '(136)', 'neighborhoods': None}, {'slug': 'aljar', 'name': 'Aljar', 'count': '(45)', 'neighborhoods': None}, {'slug': 'rock-yard', 'name': 'Rock Yard', 'count': '(43)', 'neighborhoods': None}, {'slug': 'sheraton-residence', 'name': 'Sheraton Residence', 'count': '(43)', 'ne

In [17]:
number_of_areas = 0
for location in locations:
   # print(f"{location['district']} has {len(location['areas'])} areas")
   if len(location['areas']) == 40 or len(location['areas']) == 1:
       print(f"district {location['district']} has {len(location['areas'])} areas")
       print(location['areas'])

   number_of_areas += len(location['areas'])
#    print("--------------------")
print(f"Total number of areas: {number_of_areas}")

district Madinaty has 1 areas
[{'slug': 'privado', 'name': 'Privado', 'count': '(603)', 'neighborhoods': None}]
district New Capital City has 40 areas
[{'slug': 'la-vista-city', 'name': 'La Vista City', 'count': '(702)', 'neighborhoods': None}, {'slug': 'al-maqsad', 'name': 'Al Maqsad', 'count': '(628)', 'neighborhoods': None}, {'slug': 'noor-city-2', 'name': 'Noor City', 'count': '(604)', 'neighborhoods': None}, {'slug': 'r8', 'name': 'R8', 'count': '(289)', 'neighborhoods': None}, {'slug': 'new-garden-city', 'name': 'New Garden City', 'count': '(249)', 'neighborhoods': None}, {'slug': 'il-bosco', 'name': 'IL Bosco', 'count': '(159)', 'neighborhoods': None}, {'slug': 'r3', 'name': 'R3', 'count': '(111)', 'neighborhoods': None}, {'slug': 'celia', 'name': 'Celia', 'count': '(106)', 'neighborhoods': None}, {'slug': 'r4', 'name': 'R4', 'count': '(101)', 'neighborhoods': None}, {'slug': 'r7', 'name': 'R7', 'count': '(97)', 'neighborhoods': None}, {'slug': 'taj-tower', 'name': 'Taj Tower', 'count': '(88)', 'neighborhoods': None}, {'slug': 'pyramids-mall', 'name': 'Pyramids Mall', 'count': '(59)', 'neighborhoods': None}, {'slug': 'de-joya', 'name': 'De Joya 1', 'count': '(57)', 'neighborhoods': None}, {'slug': 'granville', 'name': 'Granville', 'count': '(54)', 'neighborhoods': None}, {'slug': 'oia', 'name': 'OIA', 'count': '(52)', 'neighborhoods': None}, {'slug': 'blue-vert', 'name': 'Blue Vert', 'count': '(51)', 'neighborhoods': None}, {'slug': 'sage-lakes', 'name': 'Sage Lakes', 'count': '(44)', 'neighborhoods': None}, {'slug': 'capital-gardens-2', 'name': 'Capital Gardens', 'count': '(43)', 'neighborhoods': None}, {'slug': 'rivan', 'name': 'Rivan', 'count': '(41)', 'neighborhoods': None}, {'slug': 'armonia', 'name': 'Armonia', 'count': '(39)', 'neighborhoods': None}, {'slug': 'vinci', 'name': 'Vinci', 'count': '(38)', 'neighborhoods': None}, {'slug': 'palm-hills-new-capital', 'name': 'Palm Hills New Capital', 'count': '(38)', 'neighborhoods': None}, {'slug': 'financial-district', 'name': 'Financial District', 'count': '(33)', 'neighborhoods': None}, {'slug': 'mu23', 'name': 'MU23', 'count': '(33)', 'neighborhoods': None}, {'slug': 'la-capital', 'name': 'La Capital', 'count': '(33)', 'neighborhoods': None}, {'slug': 'hava', 'name': 'Hava', 'count': '(30)', 'neighborhoods': None}, {'slug': 'mountain-view-3', 'name': 'Mountain View', 'count': '(28)', 'neighborhoods': None}, {'slug': 'the-capital-way', 'name': 'The Capital Way', 'count': '(27)', 'neighborhoods': None}, {'slug': 'downtown-2', 'name': 'Downtown', 'count': '(25)', 'neighborhoods': None}, {'slug': 'scenario', 'name': 'Scenario', 'count': '(22)', 'neighborhoods': None}, {'slug': 'golden-tower', 'name': 'Golden Tower', 'count': '(21)', 'neighborhoods': None}, {'slug': 'midtown-condo', 'name': 'Midtown Condo', 'count': '(21)', 'neighborhoods': None}, {'slug': 'midtown-sky', 'name': 'Midtown Sky', 'count': '(21)', 'neighborhoods': None}, {'slug': 'canyon-8', 'name': 'Canyon 8', 'count': '(18)', 'neighborhoods': None}, {'slug': 'lumia-residence', 'name': 'Lumia Residence', 'count': '(16)', 'neighborhoods': None}, {'slug': 'scene-7', 'name': 'Scene 7', 'count': '(16)', 'neighborhoods': None}, {'slug': 'venia', 'name': 'Venia', 'count': '(16)', 'neighborhoods': None}, {'slug': 'government-district', 'name': 'Government District', 'count': '(15)', 'neighborhoods': None}, {'slug': 'la-reva', 'name': 'La Reva', 'count': '(15)', 'neighborhoods': None}, {'slug': 'nile-business-city', 'name': 'Nile Business City', 'count': '(14)', 'neighborhoods': None}]
district Shorouk City has 40 areas
[{'slug': 'al-burouj', 'name': 'Al Burouj', 'count': '(1102)', 'neighborhoods': None}, {'slug': 'wesal', 'name': 'Wesal', 'count': '(491)', 'neighborhoods': None}, {'slug': 'maadi-view', 'name': 'Maadi View', 'count': '(245)', 'neighborhoods': None}, {'slug': 'el-patio-sola', 'name': 'El Patio Sola', 'count': '(124)', 'neighborhoods': None}, {'slug': 'el-patio-5', 'name': 'EL Patio 5', 'count': '(113)', 'neighborhoods': None}, {'slug': 'aljar-2', 'name': 'Aljar', 'count': '(86)', 'neighborhoods': None}, {'slug': 'el-patio-prime', 'name': 'EL Patio Prime', 'count': '(86)', 'neighborhoods': None}, {'slug': 'el-patio-casa', 'name': 'EL Patio Casa', 'count': '(78)', 'neighborhoods': None}, {'slug': 'divina-gardens', 'name': 'Divina Gardens', 'count': '(59)', 'neighborhoods': None}, {'slug': 'cleopatra-palace', 'name': 'Cleopatra Palace', 'count': '(54)', 'neighborhoods': None}, {'slug': 'el-shorouk-2000', 'name': 'El Shorouk 2000', 'count': '(52)', 'neighborhoods': None}, {'slug': 'palm-island', 'name': 'Palm Island', 'count': '(36)', 'neighborhoods': None}, {'slug': 'granda-alshorouk', 'name': 'Granda Alshorouk', 'count': '(29)', 'neighborhoods': None}, {'slug': 'granda-life', 'name': 'Granda Life', 'count': '(24)', 'neighborhoods': None}, {'slug': 'palencia', 'name': 'Palencia', 'count': '(22)', 'neighborhoods': None}, {'slug': 'town-center-el-shorouk-mall', 'name': 'Town Center El-Shorouk Mall', 'count': '(22)', 'neighborhoods': None}, {'slug': 'ivy-residence', 'name': 'Ivy Residence', 'count': '(18)', 'neighborhoods': None}, {'slug': 'palm-capital', 'name': 'Palm Capital', 'count': '(15)', 'neighborhoods': None}, {'slug': 'mercado-mall', 'name': 'Mercado Mall', 'count': '(15)', 'neighborhoods': None}, {'slug': 'el-shorouk-springs', 'name': 'El Shorouk Springs', 'count': '(14)', 'neighborhoods': None}, {'slug': 'dar-misr-6', 'name': 'Dar Misr', 'count': '(12)', 'neighborhoods': None}, {'slug': 'arena-mall', 'name': 'Arena Mall', 'count': '(12)', 'neighborhoods': None}, {'slug': 'shorouk-gardens', 'name': 'Shorouk Gardens', 'count': '(12)', 'neighborhoods': None}, {'slug': 'panorama-el-shorouk', 'name': 'Panorama El Shorouk', 'count': '(11)', 'neighborhoods': None}, {'slug': 'heliopolis-residence', 'name': 'Heliopolis Residence', 'count': '(10)', 'neighborhoods': None}, {'slug': 'may-fair-2', 'name': 'May Fair', 'count': '(10)', 'neighborhoods': None}, {'slug': 'moon-yard-mall', 'name': 'Moon Yard Mall', 'count': '(10)', 'neighborhoods': None}, {'slug': 'el-shorouk-resort', 'name': 'El Shorouk Resort', 'count': '(9)', 'neighborhoods': None}, {'slug': 'meraki-residence', 'name': 'Meraki Residence', 'count': '(8)', 'neighborhoods': None}, {'slug': 'beverly-hills-2', 'name': 'Beverly Hills', 'count': '(7)', 'neighborhoods': None}, {'slug': 'hayah-residence-2', 'name': 'Hayah Residence Compound', 'count': '(7)', 'neighborhoods': None}, {'slug': 'el-patio-4', 'name': 'EL Patio 4', 'count': '(6)', 'neighborhoods': None}, {'slug': 'stella-heliopolis', 'name': 'Stella Heliopolis', 'count': '(6)', 'neighborhoods': None}, {'slug': '1st-district-shorouk-city', 'name': '1st District', 'count': '(5)', 'neighborhoods': None}, {'slug': 'vivens', 'name': 'VIVENS', 'count': '(4)', 'neighborhoods': None}, {'slug': 'nakheel-residence', 'name': 'Nakheel Residence', 'count': '(4)', 'neighborhoods': None}, {'slug': 'janna-5', 'name': 'Janna', 'count': '(4)', 'neighborhoods': None}, {'slug': '2nd-district-shorouk-city', 'name': '2nd District', 'count': '(4)', 'neighborhoods': None}, {'slug': '5th-district-shorouk-city', 'name': '5th District', 'count': '(4)', 'neighborhoods': None}, {'slug': 'el-nady-district-shorouk-city', 'name': 'El Nady District', 'count': '(4)', 'neighborhoods': None}]
district El Fostat has 1 areas
[{'slug': 'arabesque', 'name': 'Arabesque', 'count': '(96)', 'neighborhoods': None}]
district Ain Shams has 1 areas
[{'slug': 'al-sheikh-ebeid-st-ain-shams', 'name': 'Al Sheikh Ebeid St.', 'count': '(1)', 'neighborhoods': None}]
district Al Manial has 1 areas
[{'slug': 'el-roda-al-manial', 'name': 'El Roda', 'count': '(1)', 'neighborhoods': None}]
district Shubra has 1 areas
[{'slug': 'el-sahel-shubra', 'name': 'El Sahel', 'count': '(1)', 'neighborhoods': None}]
district Marg has 1 areas
[{'slug': 'kafr-abu-seer-marg', 'name': 'Kafr Abu Seer', 'count': '(2)', 'neighborhoods': None}]
district Salam City has 1 areas
[{'slug': 'el-herafeen-salam-city', 'name': 'El Herafeen', 'count': '(1)', 'neighborhoods': None}]
district Abasiya has 1 areas
[{'slug': 'etlalah', 'name': 'Etlalah', 'count': '(2)', 'neighborhoods': None}]
district Matareya has 1 areas
[{'slug': 'al-matareyah-al-gharbeyah-matareya', 'name': 'Al Matareyah Al Gharbeyah', 'count': '(1)', 'neighborhoods': None}]
district Basateen has 1 areas
[{'slug': 'ezbet-fahmy-basateen', 'name': 'Ezbet Fahmy', 'count': '(1)', 'neighborhoods': None}]
Total number of areas: 329

In [7]:
def get_multiple_pages(slugs):
    scrapper = SmartScraper(config)
    try:
        pages_soup = scrapper.scrape_multiple_pages(slugs)
    finally:
        scrapper.close()
    return pages_soup

In [8]:
for i, location in enumerate(locations):
    location_slugs = []
    if len(location['areas']) >0:
        for area in location['areas']:
            location_slugs.append(area['slug'])
    else:
        continue
    if len(location_slugs) == 0:
        print(f"No areas found for district {location['district']}, skipping soup extraction")
        locations[i]['areas_soups'] = []
        continue
    neigbhorhood_soups = get_multiple_pages(location_slugs)
    locations[i]['areas_soups'] = neigbhorhood_soups
    print(f'Finished extracting areas soups for district {location["district"]}')

NameError: name 'locations' is not defined

In [76]:
print(f"{locations[0]['district']}  area 1 is {locations[0]['areas'][0]['name']} and has {len(locations[0]['neighborhood_soups'])} neighborhood soups")

New Cairo  area 1 is 5th Settlement and has 21 neighborhood soups

conditionied stasfied

In [22]:
for location in locations:
    try:
        if len(location['areas_soups']) == 0:
            continue
        for i, so in enumerate(location['areas_soups']):
            if so and location['areas'][i]['name'] != 'Mountain View': # Check if soup and area exist
                # print(f"Processing neighborhood soup for {location['district']} - in area {location['areas'][i]['name']}")
                number_of_areas = len(location['areas'])
                neigbhorhoods = get_sub_locations(
                    so, 
                    neighborhood=False, 
                    number_of_districts=number_of_areas, 
                    parent_location_name=location['areas'][i]['name'])
                location['areas'][i]['neighborhoods'] = neigbhorhoods
                if(len(neigbhorhoods) > 0):
                    print(f"Finished processing neighborhood district {location['district']} in area {location['areas'][i]['name']} with {len(neigbhorhoods)} neighborhoods")
                if len(neigbhorhoods) >= 40:
                    print(f"district {location['district']} in area {location['areas'][i]['name']} first neighboroods is {neigbhorhoods[0]} and last neighborhood is {neigbhorhoods[-1]}")
    except Exception as e:
        print(f"Error processing neighborhood soups for {location['district']}: {e}")

C:\Users\marwa\AppData\Local\Temp\ipykernel_28164\1727533725.py:24: DeprecationWarning: Call to deprecated method findAll. (Replaced by find_all) -- Deprecated since version 4.0.0.
  if len(location.findAll('span')) < 2:

Finished processing neighborhood district New Cairo in area 5th Settlement with 40 neighborhoods
district New Cairo in area 5th Settlement first neighboroods is {'slug': 'hyde-park-new-cairo-compound', 'name': 'Hyde Park New Cairo Compound', 'count': '(3463)'} and last neighborhood is {'slug': 'south-investors-2', 'name': 'South Investors', 'count': '(230)'}
Finished processing neighborhood district New Cairo in area 1st Settlement with 40 neighborhoods
district New Cairo in area 1st Settlement first neighboroods is {'slug': 'taj-city-compound', 'name': 'Taj City Compound', 'count': '(1665)'} and last neighborhood is {'slug': 'el-masrawia-compound-2', 'name': 'El Masrawia Compound', 'count': '(25)'}
Finished processing neighborhood district New Cairo in area Rehab City with 2 neighborhoods
Finished processing neighborhood district New Cairo in area 6th Settlement with 17 neighborhoods
Finished processing neighborhood district New Cairo in area 3rd Settlement with 3 neighborhoods
Finished processing neighborhood district New Capital City in area R8 with 5 neighborhoods
Finished processing neighborhood district New Capital City in area R3 with 2 neighborhoods
Finished processing neighborhood district New Capital City in area R4 with 1 neighborhoods
Finished processing neighborhood district New Capital City in area R7 with 1 neighborhoods
Finished processing neighborhood district New Capital City in area Financial District with 1 neighborhoods
Finished processing neighborhood district Shorouk City in area 5th District with 1 neighborhoods
Finished processing neighborhood district Nasr City in area Zahraa Madinat Nasr with 2 neighborhoods
Finished processing neighborhood district Nasr City in area 1st Zone with 1 neighborhoods
Finished processing neighborhood district Mokattam in area Uptown Cairo with 2 neighborhoods
Finished processing neighborhood district Mokattam in area Al Hadaba Al Wosta with 1 neighborhoods
Finished processing neighborhood district Mokattam in area Al Hadaba Al Olya with 1 neighborhoods
Error processing neighborhood soups for Zamalek: 'areas_soups'
Error processing neighborhood soups for Hadayeq El Zeitoun: 'areas_soups'
Error processing neighborhood soups for Gesr Al Suez: 'areas_soups'
Error processing neighborhood soups for Almazah: 'areas_soups'
Finished processing neighborhood district Shubra in area El Sahel with 1 neighborhoods
Error processing neighborhood soups for Helmeyat El Zaytoun: 'areas_soups'
Finished processing neighborhood district Marg in area Kafr Abu Seer with 1 neighborhoods
Error processing neighborhood soups for Hadayek Helwan: 'areas_soups'
Error processing neighborhood soups for 15 May City: 'areas_soups'
Error processing neighborhood soups for Rod al-Farag: 'areas_soups'
Error processing neighborhood soups for Boulaq Abo El Ela: 'areas_soups'
Error processing neighborhood soups for Garden City: 'areas_soups'

In [23]:
for location in locations:
    # deleting the areas soup safely
    location.pop('areas_soups', None)

In [9]:
import yaml

# Load
locs = config['locations']

# Rebuild each district with correct key order
for district in locs:
    # Create new ordered dict
    ordered = {
        'district': district['district'],
        'slug': district['slug'],
        'areas': district.get('areas', [])
    }
    
    # Also fix area order
    for area in ordered['areas']:
        # Reorder area keys in place
        temp = {
            'name': area['name'],
            'slug': area['slug'],
            'count': area.get('count'),
            'neighborhoods': area.get('neighborhoods', [])
        }
        area.clear()
        area.update(temp)
    
    # Update original dict
    district.clear()
    district.update(ordered)

# Save back
# with open('locations.yaml', 'w') as f:
#     yaml.dump(data, f, default_flow_style=False, sort_keys=False, indent=2)

# print("✅ Fixed!")

In [10]:
print("Data being written:")
print(yaml.dump({'locations': locs}, default_flow_style=False, sort_keys=False, indent=2, allow_unicode=True))

Data being written:
locations:
- district: New Cairo
  slug: new-cairo
  areas:
  - name: 5th Settlement
    slug: 5th-settlement
    count: (43805)
    neighborhoods:
    - count: (3463)
      name: Hyde Park New Cairo Compound
      slug: hyde-park-new-cairo-compound
    - count: (3280)
      name: Mivida Compound
      slug: mivida-compound
    - count: (2916)
      name: Mountain View iCity Compound
      slug: mountain-view-icity-compound
    - count: (1925)
      name: Palm Hills New Cairo Compound
      slug: palm-hills-new-cairo-compound
    - count: (1907)
      name: Fifth Square Compound
      slug: fifth-square-compound
    - count: (1323)
      name: Mountain View Hyde Park Compound
      slug: mountain-view-hyde-park-compound
    - count: (1293)
      name: Eastown Compound
      slug: eastown-compound
    - count: (1226)
      name: Beit Al Watan
      slug: beit-al-watan-6
    - count: (1192)
      name: City Gate Compound
      slug: city-gate-compound
    - count: (1162)
      name: Lake view Residence Compound
      slug: lake-view-residence-compound
    - count: (1100)
      name: EL Patio ORO Compound
      slug: el-patio-oro-compound
    - count: (1060)
      name: Villette Compound
      slug: villette-compound
    - count: (960)
      name: El Lotus
      slug: el-lotus-2
    - count: (838)
      name: The Address East Compound
      slug: the-address-east-compound
    - count: (773)
      name: Al Andalous
      slug: al-andalous-2
    - count: (759)
      name: Galleria Moon Valley Compound
      slug: galleria-moon-valley-compound
    - count: (685)
      name: Cairo Festival City
      slug: cairo-festival-city-3
    - count: (662)
      name: Mountain View 1.1
      slug: mountain-view-1-1-2
    - count: (646)
      name: Al Narges
      slug: al-narges-2
    - count: (644)
      name: Creek Town Compound
      slug: creek-town-compound
    - count: (586)
      name: District 5 Compound
      slug: district-5-compound-compound
    - count: (447)
      name: North 90 Street
      slug: north-90-street-2
    - count: (402)
      name: Azzar Compound
      slug: azzar-compound
    - count: (385)
      name: South 90 Street
      slug: south-90-street-2
    - count: (383)
      name: 90 Avenue Compound
      slug: 90-avenue-compound
    - count: (376)
      name: Lake View Residence 2
      slug: lake-view-residence-2-2
    - count: (337)
      name: The Square Compound
      slug: the-square-compound
    - count: (296)
      name: South of Academy
      slug: south-of-academy-2
    - count: (294)
      name: Katameya Dunes Compound
      slug: katameya-dunes-compound
    - count: (289)
      name: The Icon Residence Compound
      slug: the-icon-residence-compound
    - count: (278)
      name: Palm Hills Katameya Compound
      slug: palm-hills-katameya-compound
    - count: (278)
      name: The Waterway Compound
      slug: the-waterway-compound-2
    - count: (276)
      name: Village Gate Compound
      slug: village-gate-compound
    - count: (274)
      name: Banafsag Omarat
      slug: banafsag-omarat-2
    - count: (265)
      name: layan Compound
      slug: layan-compound
    - count: (265)
      name: New Narges
      slug: new-narges-2
    - count: (237)
      name: Lake View Compound
      slug: lake-view-compound
    - count: (237)
      name: The Village Compound
      slug: the-village-compound
    - count: (230)
      name: AZAD Compound
      slug: azad-compound
    - count: (230)
      name: South Investors
      slug: south-investors-2
  - name: 1st Settlement
    slug: 1st-settlement
    count: (5681)
    neighborhoods:
    - count: (1665)
      name: Taj City Compound
      slug: taj-city-compound
    - count: (478)
      name: Swan Lake Residences
      slug: swan-lake-residences-2
    - count: (312)
      name: Saada Compound
      slug: saada-compound
    - count: (230)
      name: North Rehab
      slug: north-rehab-2
    - count: (214)
      name: Dar Misr
      slug: dar-misr-9
    - count: (136)
      name: Stei8ht Compound
      slug: stei8ht-compound
    - count: (123)
      name: El Koronfel
      slug: el-koronfel-2
    - count: (97)
      name: Mountain View 1 Compound
      slug: mountain-view-1-compound
    - count: (94)
      name: Tag Sultan Compound
      slug: tag-sultan-compound-2
    - count: (89)
      name: Cairo Business Park
      slug: cairo-business-park-2
    - count: (86)
      name: El Banafseg 1
      slug: el-banafseg-1-2
    - count: (73)
      name: Park View Compound
      slug: park-view-compound
    - count: (68)
      name: El Banafseg 7
      slug: el-banafseg-7-2
    - count: (66)
      name: El Yasmeen 3
      slug: el-yasmeen-3-2
    - count: (63)
      name: Villino Compound
      slug: villino-compound
    - count: (60)
      name: El Banafseg 6
      slug: el-banafseg-6-2
    - count: (60)
      name: El Yasmeen 2
      slug: el-yasmeen-2-2
    - count: (58)
      name: El Yasmeen 4
      slug: el-yasmeen-4-2
    - count: (57)
      name: El Banafseg 10
      slug: el-banafseg-10-2
    - count: (57)
      name: El Yasmeen 6
      slug: el-yasmeen-6-2
    - count: (57)
      name: East of Academy
      slug: east-of-academy-2
    - count: (53)
      name: Nakheel Compound
      slug: nakheel-compound
    - count: (53)
      name: El Banafseg 12
      slug: el-banafseg-12-2
    - count: (51)
      name: El Banafseg 11
      slug: el-banafseg-11-2
    - count: (50)
      name: El Banafseg 9
      slug: el-banafseg-9-2
    - count: (50)
      name: El Yasmeen 1
      slug: el-yasmeen-1-2
    - count: (46)
      name: El Banafseg 2
      slug: el-banafseg-2-2
    - count: (42)
      name: North Investors
      slug: north-investors-2
    - count: (40)
      name: Rehab Mall 1
      slug: rehab-mall-1-2
    - count: (39)
      name: Katameya Residence Compound
      slug: kattameya-residence-compound
    - count: (37)
      name: El Banafseg 8
      slug: el-banafseg-8-2
    - count: (35)
      name: El Yasmeen 5
      slug: el-yasmeen-5-2
    - count: (34)
      name: El Banafseg 4
      slug: el-banafseg-4-2
    - count: (33)
      name: El Banafseg 3
      slug: el-banafseg-3-2
    - count: (31)
      name: Avelin Compound
      slug: avelin-compound
    - count: (31)
      name: El Banafseg 5
      slug: el-banafseg-5-2
    - count: (28)
      name: Rivali Compound
      slug: rivali-compound
    - count: (26)
      name: Katameya Plaza Compound
      slug: katameya-plaza-compound
    - count: (26)
      name: Swan Lake Katameya Compound
      slug: swan-lake-katameya-compound
    - count: (25)
      name: El Masrawia Compound
      slug: el-masrawia-compound-2
  - name: Rehab City
    slug: rehab-city
    count: (4990)
    neighborhoods:
    - count: (2)
      name: Third Phase
      slug: third-phase-rehab-city
    - count: (1)
      name: Fifth Phase
      slug: fifth-phase-rehab-city
  - name: 6th Settlement
    slug: 6th-settlement
    count: (1449)
    neighborhoods:
    - count: (328)
      name: Zed East Compound
      slug: zed-east-compound
    - count: (214)
      name: Jiwar Compound
      slug: jewar-compound
    - count: (193)
      name: Golf Town
      slug: golf-town
    - count: (103)
      name: Crescent Walk
      slug: crescent-walk-2
    - count: (94)
      name: Notion Compound
      slug: notion-compound
    - count: (70)
      name: El Patio Jade
      slug: el-patio-jade
    - count: (56)
      name: Tierra
      slug: tierra
    - count: (54)
      name: Glen
      slug: glen-2
    - count: (50)
      name: EL Patio Riva
      slug: el-patio-riva
    - count: (41)
      name: Noll
      slug: noll-2
    - count: (40)
      name: Maliv
      slug: maliv-2
    - count: (34)
      name: Ever Compound
      slug: ever-compound
    - count: (15)
      name: Nest Cairo Compound
      slug: nest-cairo-compound
    - count: (12)
      name: Lusail Residence
      slug: lusail-residence-2
    - count: (12)
      name: Grand lane
      slug: grand-lane
    - count: (9)
      name: Cairova
      slug: cairova
    - count: (3)
      name: Alca New Cairo Compound
      slug: alca-new-cairo-compound
  - name: 3rd Settlement
    slug: 3rd-settlement
    count: (353)
    neighborhoods:
    - count: (49)
      name: West Arabella Compound
      slug: west-arabella-compound
    - count: (23)
      name: Sakan Masr
      slug: sakan-masr-8
    - count: (8)
      name: Arabella Compound
      slug: arabella-compound
  - name: Hyde Park Central
    slug: hyde-park-central
    count: (189)
    neighborhoods: []
  - name: Ozone Medical Center
    slug: ozone-medical-center
    count: (60)
    neighborhoods: []
  - name: Mohammed Naguib Axis
    slug: mohammed-naguib-axis
    count: (56)
    neighborhoods: []
  - name: Gamal Abd Al-Nasser Axis
    slug: gamal-abd-al-nasser-axis
    count: (44)
    neighborhoods: []
  - name: Dijar
    slug: dijar
    count: (40)
    neighborhoods: []
  - name: El Patio Vida
    slug: el-patio-vida
    count: (31)
    neighborhoods: []
  - name: Mall Top 90
    slug: mall-top-90
    count: (23)
    neighborhoods: []
  - name: Town Residence
    slug: town-residence
    count: (23)
    neighborhoods: []
  - name: W Signature
    slug: w-signature
    count: (15)
    neighborhoods: []
  - name: The Mornings
    slug: the-mornings
    count: (14)
    neighborhoods: []
  - name: Loaloa
    slug: loaloa
    count: (11)
    neighborhoods: []
  - name: Top view
    slug: top-view
    count: (11)
    neighborhoods: []
  - name: Lotus Compound
    slug: lotus-compound
    count: (9)
    neighborhoods: []
  - name: Prk Vie
    slug: prk-vie
    count: (5)
    neighborhoods: []
  - name: Green House
    slug: green-house
    count: (4)
    neighborhoods: []
  - name: Kemet
    slug: kemet
    count: (3)
    neighborhoods: []
- district: Madinaty
  slug: madinaty
  areas:
  - name: Privado
    slug: privado
    count: (603)
    neighborhoods: []
- district: Mostakbal City
  slug: mostakbal-city
  areas:
  - name: Sarai
    slug: sarai
    count: (2475)
    neighborhoods: []
  - name: Bloomfields
    slug: bloomfields
    count: (841)
    neighborhoods: []
  - name: L’Avenir
    slug: l-avenir
    count: (365)
    neighborhoods: []
  - name: Haptown
    slug: haptown
    count: (215)
    neighborhoods: []
  - name: Monte Napoleon
    slug: monte-napoleon
    count: (200)
    neighborhoods: []
  - name: Aliva mostakbal city
    slug: aliva-mostakbal-city
    count: (199)
    neighborhoods: []
  - name: Green Square
    slug: green-square
    count: (196)
    neighborhoods: []
  - name: Capital Gardens
    slug: capital-gardens
    count: (186)
    neighborhoods: []
  - name: The Butterfly
    slug: the-butterfly
    count: (166)
    neighborhoods: []
  - name: Park Central
    slug: park-central
    count: (139)
    neighborhoods: []
  - name: The Wonder MarQ
    slug: the-wonder-marq
    count: (89)
    neighborhoods: []
  - name: Zizinia El Mostakbal
    slug: zizinia-el-mostakbal
    count: (69)
    neighborhoods: []
  - name: La Mirada
    slug: la-mirada-2
    count: (68)
    neighborhoods: []
  - name: The Valleys
    slug: the-valleys
    count: (62)
    neighborhoods: []
  - name: East vale sodic
    slug: east-vale-sodic
    count: (55)
    neighborhoods: []
  - name: IL Bosco City
    slug: il-bosco-city
    count: (55)
    neighborhoods: []
  - name: Beta Greens
    slug: beta-greens
    count: (54)
    neighborhoods: []
  - name: Scenes
    slug: scenes
    count: (40)
    neighborhoods: []
  - name: CityZen
    slug: cityzen
    count: (40)
    neighborhoods: []
  - name: Mountain View
    slug: mountain-view-5
    count: (32)
    neighborhoods: null
  - name: Talda Mostakbal City
    slug: talda-mostakbal-city
    count: (30)
    neighborhoods: []
  - name: Neopolis
    slug: neopolis
    count: (23)
    neighborhoods: []
  - name: Rosail City
    slug: rosail-city
    count: (19)
    neighborhoods: []
  - name: At East
    slug: at-east
    count: (18)
    neighborhoods: []
  - name: Nyoum Mostakbal City
    slug: nyoum-mostakbal-city
    count: (16)
    neighborhoods: []
  - name: The 101
    slug: the-101
    count: (12)
    neighborhoods: []
  - name: Kukun
    slug: kukun
    count: (11)
    neighborhoods: []
  - name: Monark Residence
    slug: monark-residence
    count: (10)
    neighborhoods: []
  - name: Elaia
    slug: elaia
    count: (8)
    neighborhoods: []
  - name: Isola Quattro
    slug: isola-quattro
    count: (7)
    neighborhoods: []
  - name: Odyssia
    slug: odyssia
    count: (7)
    neighborhoods: []
  - name: Rare
    slug: rare
    count: (6)
    neighborhoods: []
  - name: Neo Gardens
    slug: neo-gardens
    count: (5)
    neighborhoods: []
  - name: Aria Compound
    slug: aria-2
    count: (4)
    neighborhoods: []
  - name: The Ridge
    slug: the-ridge
    count: (4)
    neighborhoods: []
  - name: Alaire
    slug: alaire
    count: (3)
    neighborhoods: []
  - name: Red
    slug: red
    count: (2)
    neighborhoods: []
  - name: The Marquette
    slug: the-marquette-mostakbal-city
    count: (1)
    neighborhoods: []
- district: New Capital City
  slug: new-capital-city
  areas:
  - name: La Vista City
    slug: la-vista-city
    count: (702)
    neighborhoods: []
  - name: Al Maqsad
    slug: al-maqsad
    count: (628)
    neighborhoods: []
  - name: Noor City
    slug: noor-city-2
    count: (604)
    neighborhoods: []
  - name: R8
    slug: r8
    count: (289)
    neighborhoods:
    - count: (82)
      name: De Joya 4
      slug: de-joya-4
    - count: (22)
      name: Lagoons
      slug: lagoons-3
    - count: (9)
      name: De Joya 2
      slug: de-joya-2-2
    - count: (8)
      name: Defaf
      slug: defaf
    - count: (3)
      name: Winter Park
      slug: winter-park
  - name: New Garden City
    slug: new-garden-city
    count: (249)
    neighborhoods: []
  - name: IL Bosco
    slug: il-bosco
    count: (159)
    neighborhoods: []
  - name: R3
    slug: r3
    count: (111)
    neighborhoods:
    - count: (3)
      name: Linq 30
      slug: linq-30-r3
    - count: (2)
      name: Jade Park
      slug: jade-park-r3
  - name: Celia
    slug: celia
    count: (106)
    neighborhoods: []
  - name: R4
    slug: r4
    count: (101)
    neighborhoods:
    - count: (80)
      name: Village de la Capitale
      slug: village-de-la-capitale
  - name: R7
    slug: r7
    count: (97)
    neighborhoods:
    - count: (65)
      name: De Joya 3
      slug: de-joya-3
  - name: Taj Tower
    slug: taj-tower
    count: (88)
    neighborhoods: []
  - name: Pyramids Mall
    slug: pyramids-mall
    count: (59)
    neighborhoods: []
  - name: De Joya 1
    slug: de-joya
    count: (57)
    neighborhoods: []
  - name: Granville
    slug: granville
    count: (54)
    neighborhoods: []
  - name: OIA
    slug: oia
    count: (52)
    neighborhoods: []
  - name: Blue Vert
    slug: blue-vert
    count: (51)
    neighborhoods: []
  - name: Sage Lakes
    slug: sage-lakes
    count: (44)
    neighborhoods: []
  - name: Capital Gardens
    slug: capital-gardens-2
    count: (43)
    neighborhoods: []
  - name: Rivan
    slug: rivan
    count: (41)
    neighborhoods: []
  - name: Armonia
    slug: armonia
    count: (39)
    neighborhoods: []
  - name: Vinci
    slug: vinci
    count: (38)
    neighborhoods: []
  - name: Palm Hills New Capital
    slug: palm-hills-new-capital
    count: (38)
    neighborhoods: []
  - name: Financial District
    slug: financial-district
    count: (33)
    neighborhoods:
    - count: (1)
      name: 6ixty iconic tower
      slug: 6ixty-iconic-tower-financial-district
  - name: MU23
    slug: mu23
    count: (33)
    neighborhoods: []
  - name: La Capital
    slug: la-capital
    count: (33)
    neighborhoods: []
  - name: Hava
    slug: hava
    count: (30)
    neighborhoods: []
  - name: Mountain View
    slug: mountain-view-3
    count: (28)
    neighborhoods: null
  - name: The Capital Way
    slug: the-capital-way
    count: (27)
    neighborhoods: []
  - name: Downtown
    slug: downtown-2
    count: (25)
    neighborhoods: []
  - name: Scenario
    slug: scenario
    count: (22)
    neighborhoods: []
  - name: Golden Tower
    slug: golden-tower
    count: (21)
    neighborhoods: []
  - name: Midtown Condo
    slug: midtown-condo
    count: (21)
    neighborhoods: []
  - name: Midtown Sky
    slug: midtown-sky
    count: (21)
    neighborhoods: []
  - name: Canyon 8
    slug: canyon-8
    count: (18)
    neighborhoods: []
  - name: Lumia Residence
    slug: lumia-residence
    count: (16)
    neighborhoods: []
  - name: Scene 7
    slug: scene-7
    count: (16)
    neighborhoods: []
  - name: Venia
    slug: venia
    count: (16)
    neighborhoods: []
  - name: Government District
    slug: government-district
    count: (15)
    neighborhoods: []
  - name: La Reva
    slug: la-reva
    count: (15)
    neighborhoods: []
  - name: Nile Business City
    slug: nile-business-city
    count: (14)
    neighborhoods: []
- district: Shorouk City
  slug: shorouk-city
  areas:
  - name: Al Burouj
    slug: al-burouj
    count: (1102)
    neighborhoods: []
  - name: Wesal
    slug: wesal
    count: (491)
    neighborhoods: []
  - name: Maadi View
    slug: maadi-view
    count: (245)
    neighborhoods: []
  - name: El Patio Sola
    slug: el-patio-sola
    count: (124)
    neighborhoods: []
  - name: EL Patio 5
    slug: el-patio-5
    count: (113)
    neighborhoods: []
  - name: Aljar
    slug: aljar-2
    count: (86)
    neighborhoods: []
  - name: EL Patio Prime
    slug: el-patio-prime
    count: (86)
    neighborhoods: []
  - name: EL Patio Casa
    slug: el-patio-casa
    count: (78)
    neighborhoods: []
  - name: Divina Gardens
    slug: divina-gardens
    count: (59)
    neighborhoods: []
  - name: Cleopatra Palace
    slug: cleopatra-palace
    count: (54)
    neighborhoods: []
  - name: El Shorouk 2000
    slug: el-shorouk-2000
    count: (52)
    neighborhoods: []
  - name: Palm Island
    slug: palm-island
    count: (36)
    neighborhoods: []
  - name: Granda Alshorouk
    slug: granda-alshorouk
    count: (29)
    neighborhoods: []
  - name: Granda Life
    slug: granda-life
    count: (24)
    neighborhoods: []
  - name: Palencia
    slug: palencia
    count: (22)
    neighborhoods: []
  - name: Town Center El-Shorouk Mall
    slug: town-center-el-shorouk-mall
    count: (22)
    neighborhoods: []
  - name: Ivy Residence
    slug: ivy-residence
    count: (18)
    neighborhoods: []
  - name: Palm Capital
    slug: palm-capital
    count: (15)
    neighborhoods: []
  - name: Mercado Mall
    slug: mercado-mall
    count: (15)
    neighborhoods: []
  - name: El Shorouk Springs
    slug: el-shorouk-springs
    count: (14)
    neighborhoods: []
  - name: Dar Misr
    slug: dar-misr-6
    count: (12)
    neighborhoods: []
  - name: Arena Mall
    slug: arena-mall
    count: (12)
    neighborhoods: []
  - name: Shorouk Gardens
    slug: shorouk-gardens
    count: (12)
    neighborhoods: []
  - name: Panorama El Shorouk
    slug: panorama-el-shorouk
    count: (11)
    neighborhoods: []
  - name: Heliopolis Residence
    slug: heliopolis-residence
    count: (10)
    neighborhoods: []
  - name: May Fair
    slug: may-fair-2
    count: (10)
    neighborhoods: []
  - name: Moon Yard Mall
    slug: moon-yard-mall
    count: (10)
    neighborhoods: []
  - name: El Shorouk Resort
    slug: el-shorouk-resort
    count: (9)
    neighborhoods: []
  - name: Meraki Residence
    slug: meraki-residence
    count: (8)
    neighborhoods: []
  - name: Beverly Hills
    slug: beverly-hills-2
    count: (7)
    neighborhoods: []
  - name: Hayah Residence Compound
    slug: hayah-residence-2
    count: (7)
    neighborhoods: []
  - name: EL Patio 4
    slug: el-patio-4
    count: (6)
    neighborhoods: []
  - name: Stella Heliopolis
    slug: stella-heliopolis
    count: (6)
    neighborhoods: []
  - name: 1st District

In [11]:
len(locs)

40

In [12]:
# Write the location in config file 
config['locations'] = locs

In [13]:
# Updating the config file with the new locations data 
# Write back to file
with open('../config.yaml', 'w') as f:
    yaml.dump(config, f, default_flow_style=False, sort_keys=False, indent=2, allow_unicode=True)

In [29]:
for location in locations:
    print(location)
    break

{'district': 'New Cairo', 'slug': 'new-cairo', 'areas': [{'slug': '5th-settlement', 'name': '5th Settlement', 'count': '(43805)', 'neighborhoods': [{'slug': 'hyde-park-new-cairo-compound', 'name': 'Hyde Park New Cairo Compound', 'count': '(3463)'}, {'slug': 'mivida-compound', 'name': 'Mivida Compound', 'count': '(3280)'}, {'slug': 'mountain-view-icity-compound', 'name': 'Mountain View iCity Compound', 'count': '(2916)'}, {'slug': 'palm-hills-new-cairo-compound', 'name': 'Palm Hills New Cairo Compound', 'count': '(1925)'}, {'slug': 'fifth-square-compound', 'name': 'Fifth Square Compound', 'count': '(1907)'}, {'slug': 'mountain-view-hyde-park-compound', 'name': 'Mountain View Hyde Park Compound', 'count': '(1323)'}, {'slug': 'eastown-compound', 'name': 'Eastown Compound', 'count': '(1293)'}, {'slug': 'beit-al-watan-6', 'name': 'Beit Al Watan', 'count': '(1226)'}, {'slug': 'city-gate-compound', 'name': 'City Gate Compound', 'count': '(1192)'}, {'slug': 'lake-view-residence-compound', 'name': 'Lake view Residence Compound', 'count': '(1162)'}, {'slug': 'el-patio-oro-compound', 'name': 'EL Patio ORO Compound', 'count': '(1100)'}, {'slug': 'villette-compound', 'name': 'Villette Compound', 'count': '(1060)'}, {'slug': 'el-lotus-2', 'name': 'El Lotus', 'count': '(960)'}, {'slug': 'the-address-east-compound', 'name': 'The Address East Compound', 'count': '(838)'}, {'slug': 'al-andalous-2', 'name': 'Al Andalous', 'count': '(773)'}, {'slug': 'galleria-moon-valley-compound', 'name': 'Galleria Moon Valley Compound', 'count': '(759)'}, {'slug': 'cairo-festival-city-3', 'name': 'Cairo Festival City', 'count': '(685)'}, {'slug': 'mountain-view-1-1-2', 'name': 'Mountain View 1.1', 'count': '(662)'}, {'slug': 'al-narges-2', 'name': 'Al Narges', 'count': '(646)'}, {'slug': 'creek-town-compound', 'name': 'Creek Town Compound', 'count': '(644)'}, {'slug': 'district-5-compound-compound', 'name': 'District 5 Compound', 'count': '(586)'}, {'slug': 'north-90-street-2', 'name': 'North 90 Street', 'count': '(447)'}, {'slug': 'azzar-compound', 'name': 'Azzar Compound', 'count': '(402)'}, {'slug': 'south-90-street-2', 'name': 'South 90 Street', 'count': '(385)'}, {'slug': '90-avenue-compound', 'name': '90 Avenue Compound', 'count': '(383)'}, {'slug': 'lake-view-residence-2-2', 'name': 'Lake View Residence 2', 'count': '(376)'}, {'slug': 'the-square-compound', 'name': 'The Square Compound', 'count': '(337)'}, {'slug': 'south-of-academy-2', 'name': 'South of Academy', 'count': '(296)'}, {'slug': 'katameya-dunes-compound', 'name': 'Katameya Dunes Compound', 'count': '(294)'}, {'slug': 'the-icon-residence-compound', 'name': 'The Icon Residence Compound', 'count': '(289)'}, {'slug': 'palm-hills-katameya-compound', 'name': 'Palm Hills Katameya Compound', 'count': '(278)'}, {'slug': 'the-waterway-compound-2', 'name': 'The Waterway Compound', 'count': '(278)'}, {'slug': 'village-gate-compound', 'name': 'Village Gate Compound', 'count': '(276)'}, {'slug': 'banafsag-omarat-2', 'name': 'Banafsag Omarat', 'count': '(274)'}, {'slug': 'layan-compound', 'name': 'layan Compound', 'count': '(265)'}, {'slug': 'new-narges-2', 'name': 'New Narges', 'count': '(265)'}, {'slug': 'lake-view-compound', 'name': 'Lake View Compound', 'count': '(237)'}, {'slug': 'the-village-compound', 'name': 'The Village Compound', 'count': '(237)'}, {'slug': 'azad-compound', 'name': 'AZAD Compound', 'count': '(230)'}, {'slug': 'south-investors-2', 'name': 'South Investors', 'count': '(230)'}]}, {'slug': '1st-settlement', 'name': '1st Settlement', 'count': '(5681)', 'neighborhoods': [{'slug': 'taj-city-compound', 'name': 'Taj City Compound', 'count': '(1665)'}, {'slug': 'swan-lake-residences-2', 'name': 'Swan Lake Residences', 'count': '(478)'}, {'slug': 'saada-compound', 'name': 'Saada Compound', 'count': '(312)'}, {'slug': 'north-rehab-2', 'name': 'North Rehab', 'count': '(230)'}, {'slug': 'dar-misr-9', 'name': 'Dar Misr', 'count': '(214)'}, {'slug': 'stei8ht-compound', 'name': 'Stei8ht Compound', 'count': '(136)'}, {'slug': 'el-koronfel-2', 'name': 'El Koronfel', 'count': '(123)'}, {'slug': 'mountain-view-1-compound', 'name': 'Mountain View 1 Compound', 'count': '(97)'}, {'slug': 'tag-sultan-compound-2', 'name': 'Tag Sultan Compound', 'count': '(94)'}, {'slug': 'cairo-business-park-2', 'name': 'Cairo Business Park', 'count': '(89)'}, {'slug': 'el-banafseg-1-2', 'name': 'El Banafseg 1', 'count': '(86)'}, {'slug': 'park-view-compound', 'name': 'Park View Compound', 'count': '(73)'}, {'slug': 'el-banafseg-7-2', 'name': 'El Banafseg 7', 'count': '(68)'}, {'slug': 'el-yasmeen-3-2', 'name': 'El Yasmeen 3', 'count': '(66)'}, {'slug': 'villino-compound', 'name': 'Villino Compound', 'count': '(63)'}, {'slug': 'el-banafseg-6-2', 'name': 'El Banafseg 6', 'count': '(60)'}, {'slug': 'el-yasmeen-2-2', 'name': 'El Yasmeen 2', 'count': '(60)'}, {'slug': 'el-yasmeen-4-2', 'name': 'El Yasmeen 4', 'count': '(58)'}, {'slug': 'el-banafseg-10-2', 'name': 'El Banafseg 10', 'count': '(57)'}, {'slug': 'el-yasmeen-6-2', 'name': 'El Yasmeen 6', 'count': '(57)'}, {'slug': 'east-of-academy-2', 'name': 'East of Academy', 'count': '(57)'}, {'slug': 'nakheel-compound', 'name': 'Nakheel Compound', 'count': '(53)'}, {'slug': 'el-banafseg-12-2', 'name': 'El Banafseg 12', 'count': '(53)'}, {'slug': 'el-banafseg-11-2', 'name': 'El Banafseg 11', 'count': '(51)'}, {'slug': 'el-banafseg-9-2', 'name': 'El Banafseg 9', 'count': '(50)'}, {'slug': 'el-yasmeen-1-2', 'name': 'El Yasmeen 1', 'count': '(50)'}, {'slug': 'el-banafseg-2-2', 'name': 'El Banafseg 2', 'count': '(46)'}, {'slug': 'north-investors-2', 'name': 'North Investors', 'count': '(42)'}, {'slug': 'rehab-mall-1-2', 'name': 'Rehab Mall 1', 'count': '(40)'}, {'slug': 'kattameya-residence-compound', 'name': 'Katameya Residence Compound', 'count': '(39)'}, {'slug': 'el-banafseg-8-2', 'name': 'El Banafseg 8', 'count': '(37)'}, {'slug': 'el-yasmeen-5-2', 'name': 'El Yasmeen 5', 'count': '(35)'}, {'slug': 'el-banafseg-4-2', 'name': 'El Banafseg 4', 'count': '(34)'}, {'slug': 'el-banafseg-3-2', 'name': 'El Banafseg 3', 'count': '(33)'}, {'slug': 'avelin-compound', 'name': 'Avelin Compound', 'count': '(31)'}, {'slug': 'el-banafseg-5-2', 'name': 'El Banafseg 5', 'count': '(31)'}, {'slug': 'rivali-compound', 'name': 'Rivali Compound', 'count': '(28)'}, {'slug': 'katameya-plaza-compound', 'name': 'Katameya Plaza Compound', 'count': '(26)'}, {'slug': 'swan-lake-katameya-compound', 'name': 'Swan Lake Katameya Compound', 'count': '(26)'}, {'slug': 'el-masrawia-compound-2', 'name': 'El Masrawia Compound', 'count': '(25)'}]}, {'slug': 'rehab-city', 'name': 'Rehab City', 'count': '(4990)', 'neighborhoods': [{'slug': 'third-phase-rehab-city', 'name': 'Third Phase', 'count': '(2)'}, {'slug': 'fifth-phase-rehab-city', 'name': 'Fifth Phase', 'count': '(1)'}]}, {'slug': '6th-settlement', 'name': '6th Settlement', 'count': '(1449)', 'neighborhoods': [{'slug': 'zed-east-compound', 'name': 'Zed East Compound', 'count': '(328)'}, {'slug': 'jewar-compound', 'name': 'Jiwar Compound', 'count': '(214)'}, {'slug': 'golf-town', 'name': 'Golf Town', 'count': '(193)'}, {'slug': 'crescent-walk-2', 'name': 'Crescent Walk', 'count': '(103)'}, {'slug': 'notion-compound', 'name': 'Notion Compound', 'count': '(94)'}, {'slug': 'el-patio-jade', 'name': 'El Patio Jade', 'count': '(70)'}, {'slug': 'tierra', 'name': 'Tierra', 'count': '(56)'}, {'slug': 'glen-2', 'name': 'Glen', 'count': '(54)'}, {'slug': 'el-patio-riva', 'name': 'EL Patio Riva', 'count': '(50)'}, {'slug': 'noll-2', 'name': 'Noll', 'count': '(41)'}, {'slug': 'maliv-2', 'name': 'Maliv', 'count': '(40)'}, {'slug': 'ever-compound', 'name': 'Ever Compound', 'count': '(34)'}, {'slug': 'nest-cairo-compound', 'name': 'Nest Cairo Compound', 'count': '(15)'}, {'slug': 'lusail-residence-2', 'name': 'Lusail Residence', 'count': '(12)'}, {'slug': 'grand-lane', 'name': 'Grand lane', 'count': '(12)'}, {'slug': 'cairova', 'name': 'Cairova', 'count': '(9)'}, {'slug': 'alca-new-cairo-compound', 'name': 'Alca New Cairo Compound', 'count': '(3)'}]}, {'slug': '3rd-settlement', 'name': '3rd Settlement', 'count': '(353)', 'neighborhoods': [{'slug': 'west-arabella-compound', 'name': 'West Arabella Compound', 'count': '(49)'}, {'slug': 'sakan-masr-8', 'name': 'Sakan Masr', 'count': '(23)'}, {'slug': 'arabella-compound', 'name': 'Arabella Compound', 'count': '(8)'}]}, {'slug': 'hyde-park-central', 'name': 'Hyde Park Central', 'count': '(189)', 'neighborhoods': []}, {'slug': 'ozone-medical-center', 'name': 'Ozone Medical Center', 'count': '(60)', 'neighborhoods': []}, {'slug': 'mohammed-naguib-axis', 'name': 'Mohammed Naguib Axis', 'count': '(56)', 'neighborhoods': []}, {'slug': 'gamal-abd-al-nasser-axis', 'name': 'Gamal Abd Al-Nasser Axis', 'count': '(44)', 'neighborhoods': []}, {'slug': 'dijar', 'name': 'Dijar', 'count': '(40)', 'neighborhoods': []}, {'slug': 'el-patio-vida', 'name': 'El Patio Vida', 'count': '(31)', 'neighborhoods': []}, {'slug': 'mall-top-90', 'name': 'Mall Top 90', 'count': '(23)', 'neighborhoods': []}, {'slug': 'town-residence', 'name': 'Town Residence', 'count': '(23)', 'neighborhoods': []}, {'slug': 'w-signature', 'name': 'W Signature', 'count': '(15)', 'neighborhoods': []}, {'slug': 'the-mornings', 'name': 'The Mornings', 'count': '(14)', 'neighborhoods': []}, {'slug': 'loaloa', 'name': 'Loaloa', 'count': '(11)', 'neighborhoods': []}, {'slug': 'top-view', 'name': 'Top view', 'count': '(11)', 'neighborhoods': []}, {'slug': 'lotus-compound', 'name': 'Lotus Compound', 'count': '(9)', 'neighborhoods': []}, {'slug': 'prk-vie', 'name': 'Prk Vie', 'count': '(5)', 'neighborhoods': []}, {'slug': 'green-house', 'name': 'Green House', 'count': '(4)', 'neighborhoods': []}, {'slug': 'kemet', 'name': 'Kemet', 'count': '(3)', 'neighborhoods': []}]}

In [30]:
print(locations[0].keys())

dict_keys(['district', 'slug', 'areas'])

In [31]:
print("Data being written:")
print(yaml.dump({'locations': locations}, default_flow_style=False, allow_unicode=True))

Data being written:
locations:
- areas:
  - count: (43805)
    name: 5th Settlement
    neighborhoods:
    - count: (3463)
      name: Hyde Park New Cairo Compound
      slug: hyde-park-new-cairo-compound
    - count: (3280)
      name: Mivida Compound
      slug: mivida-compound
    - count: (2916)
      name: Mountain View iCity Compound
      slug: mountain-view-icity-compound
    - count: (1925)
      name: Palm Hills New Cairo Compound
      slug: palm-hills-new-cairo-compound
    - count: (1907)
      name: Fifth Square Compound
      slug: fifth-square-compound
    - count: (1323)
      name: Mountain View Hyde Park Compound
      slug: mountain-view-hyde-park-compound
    - count: (1293)
      name: Eastown Compound
      slug: eastown-compound
    - count: (1226)
      name: Beit Al Watan
      slug: beit-al-watan-6
    - count: (1192)
      name: City Gate Compound
      slug: city-gate-compound
    - count: (1162)
      name: Lake view Residence Compound
      slug: lake-view-residence-compound
    - count: (1100)
      name: EL Patio ORO Compound
      slug: el-patio-oro-compound
    - count: (1060)
      name: Villette Compound
      slug: villette-compound
    - count: (960)
      name: El Lotus
      slug: el-lotus-2
    - count: (838)
      name: The Address East Compound
      slug: the-address-east-compound
    - count: (773)
      name: Al Andalous
      slug: al-andalous-2
    - count: (759)
      name: Galleria Moon Valley Compound
      slug: galleria-moon-valley-compound
    - count: (685)
      name: Cairo Festival City
      slug: cairo-festival-city-3
    - count: (662)
      name: Mountain View 1.1
      slug: mountain-view-1-1-2
    - count: (646)
      name: Al Narges
      slug: al-narges-2
    - count: (644)
      name: Creek Town Compound
      slug: creek-town-compound
    - count: (586)
      name: District 5 Compound
      slug: district-5-compound-compound
    - count: (447)
      name: North 90 Street
      slug: north-90-street-2
    - count: (402)
      name: Azzar Compound
      slug: azzar-compound
    - count: (385)
      name: South 90 Street
      slug: south-90-street-2
    - count: (383)
      name: 90 Avenue Compound
      slug: 90-avenue-compound
    - count: (376)
      name: Lake View Residence 2
      slug: lake-view-residence-2-2
    - count: (337)
      name: The Square Compound
      slug: the-square-compound
    - count: (296)
      name: South of Academy
      slug: south-of-academy-2
    - count: (294)
      name: Katameya Dunes Compound
      slug: katameya-dunes-compound
    - count: (289)
      name: The Icon Residence Compound
      slug: the-icon-residence-compound
    - count: (278)
      name: Palm Hills Katameya Compound
      slug: palm-hills-katameya-compound
    - count: (278)
      name: The Waterway Compound
      slug: the-waterway-compound-2
    - count: (276)
      name: Village Gate Compound
      slug: village-gate-compound
    - count: (274)
      name: Banafsag Omarat
      slug: banafsag-omarat-2
    - count: (265)
      name: layan Compound
      slug: layan-compound
    - count: (265)
      name: New Narges
      slug: new-narges-2
    - count: (237)
      name: Lake View Compound
      slug: lake-view-compound
    - count: (237)
      name: The Village Compound
      slug: the-village-compound
    - count: (230)
      name: AZAD Compound
      slug: azad-compound
    - count: (230)
      name: South Investors
      slug: south-investors-2
    slug: 5th-settlement
  - count: (5681)
    name: 1st Settlement
    neighborhoods:
    - count: (1665)
      name: Taj City Compound
      slug: taj-city-compound
    - count: (478)
      name: Swan Lake Residences
      slug: swan-lake-residences-2
    - count: (312)
      name: Saada Compound
      slug: saada-compound
    - count: (230)
      name: North Rehab
      slug: north-rehab-2
    - count: (214)
      name: Dar Misr
      slug: dar-misr-9
    - count: (136)
      name: Stei8ht Compound
      slug: stei8ht-compound
    - count: (123)
      name: El Koronfel
      slug: el-koronfel-2
    - count: (97)
      name: Mountain View 1 Compound
      slug: mountain-view-1-compound
    - count: (94)
      name: Tag Sultan Compound
      slug: tag-sultan-compound-2
    - count: (89)
      name: Cairo Business Park
      slug: cairo-business-park-2
    - count: (86)
      name: El Banafseg 1
      slug: el-banafseg-1-2
    - count: (73)
      name: Park View Compound
      slug: park-view-compound
    - count: (68)
      name: El Banafseg 7
      slug: el-banafseg-7-2
    - count: (66)
      name: El Yasmeen 3
      slug: el-yasmeen-3-2
    - count: (63)
      name: Villino Compound
      slug: villino-compound
    - count: (60)
      name: El Banafseg 6
      slug: el-banafseg-6-2
    - count: (60)
      name: El Yasmeen 2
      slug: el-yasmeen-2-2
    - count: (58)
      name: El Yasmeen 4
      slug: el-yasmeen-4-2
    - count: (57)
      name: El Banafseg 10
      slug: el-banafseg-10-2
    - count: (57)
      name: El Yasmeen 6
      slug: el-yasmeen-6-2
    - count: (57)
      name: East of Academy
      slug: east-of-academy-2
    - count: (53)
      name: Nakheel Compound
      slug: nakheel-compound
    - count: (53)
      name: El Banafseg 12
      slug: el-banafseg-12-2
    - count: (51)
      name: El Banafseg 11
      slug: el-banafseg-11-2
    - count: (50)
      name: El Banafseg 9
      slug: el-banafseg-9-2
    - count: (50)
      name: El Yasmeen 1
      slug: el-yasmeen-1-2
    - count: (46)
      name: El Banafseg 2
      slug: el-banafseg-2-2
    - count: (42)
      name: North Investors
      slug: north-investors-2
    - count: (40)
      name: Rehab Mall 1
      slug: rehab-mall-1-2
    - count: (39)
      name: Katameya Residence Compound
      slug: kattameya-residence-compound
    - count: (37)
      name: El Banafseg 8
      slug: el-banafseg-8-2
    - count: (35)
      name: El Yasmeen 5
      slug: el-yasmeen-5-2
    - count: (34)
      name: El Banafseg 4
      slug: el-banafseg-4-2
    - count: (33)
      name: El Banafseg 3
      slug: el-banafseg-3-2
    - count: (31)
      name: Avelin Compound
      slug: avelin-compound
    - count: (31)
      name: El Banafseg 5
      slug: el-banafseg-5-2
    - count: (28)
      name: Rivali Compound
      slug: rivali-compound
    - count: (26)
      name: Katameya Plaza Compound
      slug: katameya-plaza-compound
    - count: (26)
      name: Swan Lake Katameya Compound
      slug: swan-lake-katameya-compound
    - count: (25)
      name: El Masrawia Compound
      slug: el-masrawia-compound-2
    slug: 1st-settlement
  - count: (4990)
    name: Rehab City
    neighborhoods:
    - count: (2)
      name: Third Phase
      slug: third-phase-rehab-city
    - count: (1)
      name: Fifth Phase
      slug: fifth-phase-rehab-city
    slug: rehab-city
  - count: (1449)
    name: 6th Settlement
    neighborhoods:
    - count: (328)
      name: Zed East Compound
      slug: zed-east-compound
    - count: (214)
      name: Jiwar Compound
      slug: jewar-compound
    - count: (193)
      name: Golf Town
      slug: golf-town
    - count: (103)
      name: Crescent Walk
      slug: crescent-walk-2
    - count: (94)
      name: Notion Compound
      slug: notion-compound
    - count: (70)
      name: El Patio Jade
      slug: el-patio-jade
    - count: (56)
      name: Tierra
      slug: tierra
    - count: (54)
      name: Glen
      slug: glen-2
    - count: (50)
      name: EL Patio Riva
      slug: el-patio-riva
    - count: (41)
      name: Noll
      slug: noll-2
    - count: (40)
      name: Maliv
      slug: maliv-2
    - count: (34)
      name: Ever Compound
      slug: ever-compound
    - count: (15)
      name: Nest Cairo Compound
      slug: nest-cairo-compound
    - count: (12)
      name: Lusail Residence
      slug: lusail-residence-2
    - count: (12)
      name: Grand lane
      slug: grand-lane
    - count: (9)
      name: Cairova
      slug: cairova
    - count: (3)
      name: Alca New Cairo Compound
      slug: alca-new-cairo-compound
    slug: 6th-settlement
  - count: (353)
    name: 3rd Settlement
    neighborhoods:
    - count: (49)
      name: West Arabella Compound
      slug: west-arabella-compound
    - count: (23)
      name: Sakan Masr
      slug: sakan-masr-8
    - count: (8)
      name: Arabella Compound
      slug: arabella-compound
    slug: 3rd-settlement
  - count: (189)
    name: Hyde Park Central
    neighborhoods: []
    slug: hyde-park-central
  - count: (60)
    name: Ozone Medical Center
    neighborhoods: []
    slug: ozone-medical-center
  - count: (56)
    name: Mohammed Naguib Axis
    neighborhoods: []
    slug: mohammed-naguib-axis
  - count: (44)
    name: Gamal Abd Al-Nasser Axis
    neighborhoods: []
    slug: gamal-abd-al-nasser-axis
  - count: (40)
    name: Dijar
    neighborhoods: []
    slug: dijar
  - count: (31)
    name: El Patio Vida
    neighborhoods: []
    slug: el-patio-vida
  - count: (23)
    name: Mall Top 90
    neighborhoods: []
    slug: mall-top-90
  - count: (23)
    name: Town Residence
    neighborhoods: []
    slug: town-residence
  - count: (15)
    name: W Signature
    neighborhoods: []
    slug: w-signature
  - count: (14)
    name: The Mornings
    neighborhoods: []
    slug: the-mornings
  - count: (11)
    name: Loaloa
    neighborhoods: []
    slug: loaloa
  - count: (11)
    name: Top view
    neighborhoods: []
    slug: top-view
  - count: (9)
    name: Lotus Compound
    neighborhoods: []
    slug: lotus-compound
  - count: (5)
    name: Prk Vie
    neighborhoods: []
    slug: prk-vie
  - count: (4)
    name: Green House
    neighborhoods: []
    slug: green-house
  - count: (3)
    name: Kemet
    neighborhoods: []
    slug: kemet
  district: New Cairo
  slug: new-cairo
- areas:
  - count: (603)
    name: Privado
    neighborhoods: []
    slug: privado
  district: Madinaty
  slug: madinaty
- areas:
  - count: (2475)
    name: Sarai
    neighborhoods: []
    slug: sarai
  - count: (841)
    name: Bloomfields
    neighborhoods: []
    slug: bloomfields
  - count: (365)
    name: L’Avenir
    neighborhoods: []
    slug: l-avenir
  - count: (215)
    name: Haptown
    neighborhoods: []
    slug: haptown
  - count: (200)
    name: Monte Napoleon
    neighborhoods: []
    slug: monte-napoleon
  - count: (199)
    name: Aliva mostakbal city
    neighborhoods: []
    slug: aliva-mostakbal-city
  - count: (196)
    name: Green Square
    neighborhoods: []
    slug: green-square
  - count: (186)
    name: Capital Gardens
    neighborhoods: []
    slug: capital-gardens
  - count: (166)
    name: The Butterfly
    neighborhoods: []
    slug: the-butterfly
  - count: (139)
    name: Park Central
    neighborhoods: []
    slug: park-central
  - count: (89)
    name: The Wonder MarQ
    neighborhoods: []
    slug: the-wonder-marq
  - count: (69)
    name: Zizinia El Mostakbal
    neighborhoods: []
    slug: zizinia-el-mostakbal
  - count: (68)
    name: La Mirada
    neighborhoods: []
    slug: la-mirada-2
  - count: (62)
    name: The Valleys
    neighborhoods: []
    slug: the-valleys
  - count: (55)
    name: East vale sodic
    neighborhoods: []
    slug: east-vale-sodic
  - count: (55)
    name: IL Bosco City
    neighborhoods: []
    slug: il-bosco-city
  - count: (54)
    name: Beta Greens
    neighborhoods: []
    slug: beta-greens
  - count: (40)
    name: Scenes
    neighborhoods: []
    slug: scenes
  - count: (40)
    name: CityZen
    neighborhoods: []
    slug: cityzen
  - count: (32)
    name: Mountain View
    neighborhoods: null
    slug: mountain-view-5
  - count: (30)
    name: Talda Mostakbal City
    neighborhoods: []
    slug: talda-mostakbal-city
  - count: (23)
    name: Neopolis
    neighborhoods: []
    slug: neopolis
  - count: (19)
    name: Rosail City
    neighborhoods: []
    slug: rosail-city
  - count: (18)
    name: At East
    neighborhoods: []
    slug: at-east
  - count: (16)
    name: Nyoum Mostakbal City
    neighborhoods: []
    slug: nyoum-mostakbal-city
  - count: (12)
    name: The 101
    neighborhoods: []
    slug: the-101
  - count: (11)
    name: Kukun
    neighborhoods: []
    slug: kukun
  - count: (10)
    name: Monark Residence
    neighborhoods: []
    slug: monark-residence
  - count: (8)
    name: Elaia
    neighborhoods: []
    slug: elaia
  - count: (7)
    name: Isola Quattro
    neighborhoods: []
    slug: isola-quattro
  - count: (7)
    name: Odyssia
    neighborhoods: []
    slug: odyssia
  - count: (6)
    name: Rare
    neighborhoods: []
    slug: rare
  - count: (5)
    name: Neo Gardens
    neighborhoods: []
    slug: neo-gardens
  - count: (4)
    name: Aria Compound
    neighborhoods: []
    slug: aria-2
  - count: (4)
    name: The Ridge
    neighborhoods: []
    slug: the-ridge
  - count: (3)
    name: Alaire
    neighborhoods: []
    slug: alaire
  - count: (2)
    name: Red
    neighborhoods: []
    slug: red
  - count: (1)
    name: The Marquette
    neighborhoods: []
    slug: the-marquette-mostakbal-city
  district: Mostakbal City
  slug: mostakbal-city
- areas:
  - count: (702)
    name: La Vista City
    neighborhoods: []
    slug: la-vista-city
  - count: (628)
    name: Al Maqsad
    neighborhoods: []
    slug: al-maqsad
  - count: (604)
    name: Noor City
    neighborhoods: []
    slug: noor-city-2
  - count: (289)
    name: R8
    neighborhoods:
    - count: (82)
      name: De Joya 4
      slug: de-joya-4
    - count: (22)
      name: Lagoons
      slug: lagoons-3
    - count: (9)
      name: De Joya 2
      slug: de-joya-2-2
    - count: (8)
      name: Defaf
      slug: defaf
    - count: (3)
      name: Winter Park
      slug: winter-park
    slug: r8
  - count: (249)
    name: New Garden City
    neighborhoods: []
    slug: new-garden-city
  - count: (159)
    name: IL Bosco
    neighborhoods: []
    slug: il-bosco
  - count: (111)
    name: R3
    neighborhoods:
    - count: (3)
      name: Linq 30
      slug: linq-30-r3
    - count: (2)
      name: Jade Park
      slug: jade-park-r3
    slug: r3
  - count: (106)
    name: Celia
    neighborhoods: []
    slug: celia
  - count: (101)
    name: R4
    neighborhoods:
    - count: (80)
      name: Village de la Capitale
      slug: village-de-la-capitale
    slug: r4
  - count: (97)
    name: R7
    neighborhoods:
    - count: (65)
      name: De Joya 3
      slug: de-joya-3
    slug: r7
  - count: (88)
    name: Taj Tower
    neighborhoods: []
    slug: taj-tower
  - count: (59)
    name: Pyramids Mall
    neighborhoods: []
    slug: pyramids-mall
  - count: (57)
    name: De Joya 1
    neighborhoods: []
    slug: de-joya
  - count: (54)
    name: Granville
    neighborhoods: []
    slug: granville
  - count: (52)
    name: OIA
    neighborhoods: []
    slug: oia
  - count: (51)
    name: Blue Vert
    neighborhoods: []
    slug: blue-vert
  - count: (44)
    name: Sage Lakes
    neighborhoods: []
    slug: sage-lakes
  - count: (43)
    name: Capital Gardens
    neighborhoods: []
    slug: capital-gardens-2
  - count: (41)
    name: Rivan
    neighborhoods: []
    slug: rivan
  - count: (39)
    name: Armonia
    neighborhoods: []
    slug: armonia
  - count: (38)
    name: Vinci
    neighborhoods: []
    slug: vinci
  - count: (38)
    name: Palm Hills New Capital
    neighborhoods: []
    slug: palm-hills-new-capital
  - count: (33)
    name: Financial District
    neighborhoods:
    - count: (1)
      name: 6ixty iconic tower
      slug: 6ixty-iconic-tower-financial-district
    slug: financial-district
  - count: (33)
    name: MU23
    neighborhoods: []
    slug: mu23
  - count: (33)
    name: La Capital
    neighborhoods: []
    slug: la-capital
  - count: (30)
    name: Hava
    neighborhoods: []
    slug: hava
  - count: (28)
    name: Mountain View
    neighborhoods: null
    slug: mountain-view-3
  - count: (27)
    name: The Capital Way
    neighborhoods: []
    slug: the-capital-way
  - count: (25)
    name: Downtown
    neighborhoods: []
    slug: downtown-2
  - count: (22)
    name: Scenario
    neighborhoods: []
    slug: scenario
  - count: (21)
    name: Golden Tower
    neighborhoods: []
    slug: golden-tower
  - count: (21)
    name: Midtown Condo
    neighborhoods: []
    slug: midtown-condo
  - count: (21)
    name: Midtown Sky
    neighborhoods: []
    slug: midtown-sky
  - count: (18)
    name: Canyon 8
    neighborhoods: []
    slug: canyon-8
  - count: (16)
    name: Lumia Residence
    neighborhoods: []
    slug: lumia-residence
  - count: (16)
    name: Scene 7
    neighborhoods: []
    slug: scene-7
  - count: (16)
    name: Venia
    neighborhoods: []
    slug: venia
  - count: (15)
    name: Government District
    neighborhoods: []
    slug: government-district
  - count: (15)
    name: La Reva
    neighborhoods: []
    slug: la-reva
  - count: (14)
    name: Nile Business City
    neighborhoods: []
    slug: nile-business-city
  district: New Capital City
  slug: new-capital-city
- areas:
  - count: (1102)
    name: Al Burouj
    neighborhoods: []
    slug: al-burouj
  - count: (491)
    name: Wesal
    neighborhoods: []
    slug: wesal
  - count: (245)
    name: Maadi View
    neighborhoods: []
    slug: maadi-view
  - count: (124)
    name: El Patio Sola
    neighborhoods: []
    slug: el-patio-sola
  - count: (113)
    name: EL Patio 5
    neighborhoods: []
    slug: el-patio-5
  - count: (86)
    name: Aljar
    neighborhoods: []
    slug: aljar-2
  - count: (86)
    name: EL Patio Prime
    neighborhoods: []
    slug: el-patio-prime
  - count: (78)
    name: EL Patio Casa
    neighborhoods: []
    slug: el-patio-casa
  - count: (59)
    name: Divina Gardens
    neighborhoods: []
    slug: divina-gardens
  - count: (54)
    name: Cleopatra Palace
    neighborhoods: []
    slug: cleopatra-palace
  - count: (52)
    name: El Shorouk 2000
    neighborhoods: []
    slug: el-shorouk-2000
  - count: (36)
    name: Palm Island
    neighborhoods: []
    slug: palm-island
  - count: (29)
    name: Granda Alshorouk
    neighborhoods: []
    slug: granda-alshorouk
  - count: (24)
    name: Granda Life
    neighborhoods: []
    slug: granda-life
  - count: (22)
    name: Palencia
    neighborhoods: []
    slug: palencia
  - count: (22)
    name: Town Center El-Shorouk Mall
    neighborhoods: []
    slug: town-center-el-shorouk-mall
  - count: (18)
    name: Ivy Residence
    neighborhoods: []
    slug: ivy-residence
  - count: (15)
    name: Palm Capital
    neighborhoods: []
    slug: palm-capital
  - count: (15)
    name: Mercado Mall
    neighborhoods: []
    slug: mercado-mall
  - count: (14)
    name: El Shorouk Springs
    neighborhoods: []
    slug: el-shorouk-springs
  - count: (12)
    name: Dar Misr
    neighborhoods: []
    slug: dar-misr-6
  - count: (12)
    name: Arena Mall
    neighborhoods: []
    slug: arena-mall
  - count: (12)
    name: Shorouk Gardens
    neighborhoods: []
    slug: shorouk-gardens
  - count: (11)
    name: Panorama El Shorouk
    neighborhoods: []
    slug: panorama-el-shorouk
  - count: (10)
    name: Heliopolis Residence
    neighborhoods: []
    slug: heliopolis-residence
  - count: (10)
    name: May Fair
    neighborhoods: []
    slug: may-fair-2
  - count: (10)
    name: Moon Yard Mall
    neighborhoods: []
    slug: moon-yard-mall
  - count: (9)
    name: El Shorouk Resort
    neighborhoods: []
    slug: el-shorouk-resort
  - count: (8)
    name: Meraki Residence
    neighborhoods: []
    slug: meraki-residence
  - count: (7)
    name: Beverly Hills
    neighborhoods: []
    slug: beverly-hills-2
  - count: (7)
    name: Hayah Residence Compound
    neighborhoods: []
    slug: hayah-residence-2
  - count: (6)
    name: EL Patio 4
    neighborhoods: []
    slug: el-patio-4
  - count: (6)
    name: Stella Heliopolis
    neighborhoods: []
    slug: stella-heliopolis
  - count: (5)
    name: 1st District
    neighborhoods: []

In [32]:
# Check the actual values
print(f"District value: {locations[0]['district']}")
print(f"Slug value: {locations[0]['slug']}")
print(f"Full first location: {locations[0]}")

District value: New Cairo
Slug value: new-cairo
Full first location: {'district': 'New Cairo', 'slug': 'new-cairo', 'areas': [{'slug': '5th-settlement', 'name': '5th Settlement', 'count': '(43805)', 'neighborhoods': [{'slug': 'hyde-park-new-cairo-compound', 'name': 'Hyde Park New Cairo Compound', 'count': '(3463)'}, {'slug': 'mivida-compound', 'name': 'Mivida Compound', 'count': '(3280)'}, {'slug': 'mountain-view-icity-compound', 'name': 'Mountain View iCity Compound', 'count': '(2916)'}, {'slug': 'palm-hills-new-cairo-compound', 'name': 'Palm Hills New Cairo Compound', 'count': '(1925)'}, {'slug': 'fifth-square-compound', 'name': 'Fifth Square Compound', 'count': '(1907)'}, {'slug': 'mountain-view-hyde-park-compound', 'name': 'Mountain View Hyde Park Compound', 'count': '(1323)'}, {'slug': 'eastown-compound', 'name': 'Eastown Compound', 'count': '(1293)'}, {'slug': 'beit-al-watan-6', 'name': 'Beit Al Watan', 'count': '(1226)'}, {'slug': 'city-gate-compound', 'name': 'City Gate Compound', 'count': '(1192)'}, {'slug': 'lake-view-residence-compound', 'name': 'Lake view Residence Compound', 'count': '(1162)'}, {'slug': 'el-patio-oro-compound', 'name': 'EL Patio ORO Compound', 'count': '(1100)'}, {'slug': 'villette-compound', 'name': 'Villette Compound', 'count': '(1060)'}, {'slug': 'el-lotus-2', 'name': 'El Lotus', 'count': '(960)'}, {'slug': 'the-address-east-compound', 'name': 'The Address East Compound', 'count': '(838)'}, {'slug': 'al-andalous-2', 'name': 'Al Andalous', 'count': '(773)'}, {'slug': 'galleria-moon-valley-compound', 'name': 'Galleria Moon Valley Compound', 'count': '(759)'}, {'slug': 'cairo-festival-city-3', 'name': 'Cairo Festival City', 'count': '(685)'}, {'slug': 'mountain-view-1-1-2', 'name': 'Mountain View 1.1', 'count': '(662)'}, {'slug': 'al-narges-2', 'name': 'Al Narges', 'count': '(646)'}, {'slug': 'creek-town-compound', 'name': 'Creek Town Compound', 'count': '(644)'}, {'slug': 'district-5-compound-compound', 'name': 'District 5 Compound', 'count': '(586)'}, {'slug': 'north-90-street-2', 'name': 'North 90 Street', 'count': '(447)'}, {'slug': 'azzar-compound', 'name': 'Azzar Compound', 'count': '(402)'}, {'slug': 'south-90-street-2', 'name': 'South 90 Street', 'count': '(385)'}, {'slug': '90-avenue-compound', 'name': '90 Avenue Compound', 'count': '(383)'}, {'slug': 'lake-view-residence-2-2', 'name': 'Lake View Residence 2', 'count': '(376)'}, {'slug': 'the-square-compound', 'name': 'The Square Compound', 'count': '(337)'}, {'slug': 'south-of-academy-2', 'name': 'South of Academy', 'count': '(296)'}, {'slug': 'katameya-dunes-compound', 'name': 'Katameya Dunes Compound', 'count': '(294)'}, {'slug': 'the-icon-residence-compound', 'name': 'The Icon Residence Compound', 'count': '(289)'}, {'slug': 'palm-hills-katameya-compound', 'name': 'Palm Hills Katameya Compound', 'count': '(278)'}, {'slug': 'the-waterway-compound-2', 'name': 'The Waterway Compound', 'count': '(278)'}, {'slug': 'village-gate-compound', 'name': 'Village Gate Compound', 'count': '(276)'}, {'slug': 'banafsag-omarat-2', 'name': 'Banafsag Omarat', 'count': '(274)'}, {'slug': 'layan-compound', 'name': 'layan Compound', 'count': '(265)'}, {'slug': 'new-narges-2', 'name': 'New Narges', 'count': '(265)'}, {'slug': 'lake-view-compound', 'name': 'Lake View Compound', 'count': '(237)'}, {'slug': 'the-village-compound', 'name': 'The Village Compound', 'count': '(237)'}, {'slug': 'azad-compound', 'name': 'AZAD Compound', 'count': '(230)'}, {'slug': 'south-investors-2', 'name': 'South Investors', 'count': '(230)'}]}, {'slug': '1st-settlement', 'name': '1st Settlement', 'count': '(5681)', 'neighborhoods': [{'slug': 'taj-city-compound', 'name': 'Taj City Compound', 'count': '(1665)'}, {'slug': 'swan-lake-residences-2', 'name': 'Swan Lake Residences', 'count': '(478)'}, {'slug': 'saada-compound', 'name': 'Saada Compound', 'count': '(312)'}, {'slug': 'north-rehab-2', 'name': 'North Rehab', 'count': '(230)'}, {'slug': 'dar-misr-9', 'name': 'Dar Misr', 'count': '(214)'}, {'slug': 'stei8ht-compound', 'name': 'Stei8ht Compound', 'count': '(136)'}, {'slug': 'el-koronfel-2', 'name': 'El Koronfel', 'count': '(123)'}, {'slug': 'mountain-view-1-compound', 'name': 'Mountain View 1 Compound', 'count': '(97)'}, {'slug': 'tag-sultan-compound-2', 'name': 'Tag Sultan Compound', 'count': '(94)'}, {'slug': 'cairo-business-park-2', 'name': 'Cairo Business Park', 'count': '(89)'}, {'slug': 'el-banafseg-1-2', 'name': 'El Banafseg 1', 'count': '(86)'}, {'slug': 'park-view-compound', 'name': 'Park View Compound', 'count': '(73)'}, {'slug': 'el-banafseg-7-2', 'name': 'El Banafseg 7', 'count': '(68)'}, {'slug': 'el-yasmeen-3-2', 'name': 'El Yasmeen 3', 'count': '(66)'}, {'slug': 'villino-compound', 'name': 'Villino Compound', 'count': '(63)'}, {'slug': 'el-banafseg-6-2', 'name': 'El Banafseg 6', 'count': '(60)'}, {'slug': 'el-yasmeen-2-2', 'name': 'El Yasmeen 2', 'count': '(60)'}, {'slug': 'el-yasmeen-4-2', 'name': 'El Yasmeen 4', 'count': '(58)'}, {'slug': 'el-banafseg-10-2', 'name': 'El Banafseg 10', 'count': '(57)'}, {'slug': 'el-yasmeen-6-2', 'name': 'El Yasmeen 6', 'count': '(57)'}, {'slug': 'east-of-academy-2', 'name': 'East of Academy', 'count': '(57)'}, {'slug': 'nakheel-compound', 'name': 'Nakheel Compound', 'count': '(53)'}, {'slug': 'el-banafseg-12-2', 'name': 'El Banafseg 12', 'count': '(53)'}, {'slug': 'el-banafseg-11-2', 'name': 'El Banafseg 11', 'count': '(51)'}, {'slug': 'el-banafseg-9-2', 'name': 'El Banafseg 9', 'count': '(50)'}, {'slug': 'el-yasmeen-1-2', 'name': 'El Yasmeen 1', 'count': '(50)'}, {'slug': 'el-banafseg-2-2', 'name': 'El Banafseg 2', 'count': '(46)'}, {'slug': 'north-investors-2', 'name': 'North Investors', 'count': '(42)'}, {'slug': 'rehab-mall-1-2', 'name': 'Rehab Mall 1', 'count': '(40)'}, {'slug': 'kattameya-residence-compound', 'name': 'Katameya Residence Compound', 'count': '(39)'}, {'slug': 'el-banafseg-8-2', 'name': 'El Banafseg 8', 'count': '(37)'}, {'slug': 'el-yasmeen-5-2', 'name': 'El Yasmeen 5', 'count': '(35)'}, {'slug': 'el-banafseg-4-2', 'name': 'El Banafseg 4', 'count': '(34)'}, {'slug': 'el-banafseg-3-2', 'name': 'El Banafseg 3', 'count': '(33)'}, {'slug': 'avelin-compound', 'name': 'Avelin Compound', 'count': '(31)'}, {'slug': 'el-banafseg-5-2', 'name': 'El Banafseg 5', 'count': '(31)'}, {'slug': 'rivali-compound', 'name': 'Rivali Compound', 'count': '(28)'}, {'slug': 'katameya-plaza-compound', 'name': 'Katameya Plaza Compound', 'count': '(26)'}, {'slug': 'swan-lake-katameya-compound', 'name': 'Swan Lake Katameya Compound', 'count': '(26)'}, {'slug': 'el-masrawia-compound-2', 'name': 'El Masrawia Compound', 'count': '(25)'}]}, {'slug': 'rehab-city', 'name': 'Rehab City', 'count': '(4990)', 'neighborhoods': [{'slug': 'third-phase-rehab-city', 'name': 'Third Phase', 'count': '(2)'}, {'slug': 'fifth-phase-rehab-city', 'name': 'Fifth Phase', 'count': '(1)'}]}, {'slug': '6th-settlement', 'name': '6th Settlement', 'count': '(1449)', 'neighborhoods': [{'slug': 'zed-east-compound', 'name': 'Zed East Compound', 'count': '(328)'}, {'slug': 'jewar-compound', 'name': 'Jiwar Compound', 'count': '(214)'}, {'slug': 'golf-town', 'name': 'Golf Town', 'count': '(193)'}, {'slug': 'crescent-walk-2', 'name': 'Crescent Walk', 'count': '(103)'}, {'slug': 'notion-compound', 'name': 'Notion Compound', 'count': '(94)'}, {'slug': 'el-patio-jade', 'name': 'El Patio Jade', 'count': '(70)'}, {'slug': 'tierra', 'name': 'Tierra', 'count': '(56)'}, {'slug': 'glen-2', 'name': 'Glen', 'count': '(54)'}, {'slug': 'el-patio-riva', 'name': 'EL Patio Riva', 'count': '(50)'}, {'slug': 'noll-2', 'name': 'Noll', 'count': '(41)'}, {'slug': 'maliv-2', 'name': 'Maliv', 'count': '(40)'}, {'slug': 'ever-compound', 'name': 'Ever Compound', 'count': '(34)'}, {'slug': 'nest-cairo-compound', 'name': 'Nest Cairo Compound', 'count': '(15)'}, {'slug': 'lusail-residence-2', 'name': 'Lusail Residence', 'count': '(12)'}, {'slug': 'grand-lane', 'name': 'Grand lane', 'count': '(12)'}, {'slug': 'cairova', 'name': 'Cairova', 'count': '(9)'}, {'slug': 'alca-new-cairo-compound', 'name': 'Alca New Cairo Compound', 'count': '(3)'}]}, {'slug': '3rd-settlement', 'name': '3rd Settlement', 'count': '(353)', 'neighborhoods': [{'slug': 'west-arabella-compound', 'name': 'West Arabella Compound', 'count': '(49)'}, {'slug': 'sakan-masr-8', 'name': 'Sakan Masr', 'count': '(23)'}, {'slug': 'arabella-compound', 'name': 'Arabella Compound', 'count': '(8)'}]}, {'slug': 'hyde-park-central', 'name': 'Hyde Park Central', 'count': '(189)', 'neighborhoods': []}, {'slug': 'ozone-medical-center', 'name': 'Ozone Medical Center', 'count': '(60)', 'neighborhoods': []}, {'slug': 'mohammed-naguib-axis', 'name': 'Mohammed Naguib Axis', 'count': '(56)', 'neighborhoods': []}, {'slug': 'gamal-abd-al-nasser-axis', 'name': 'Gamal Abd Al-Nasser Axis', 'count': '(44)', 'neighborhoods': []}, {'slug': 'dijar', 'name': 'Dijar', 'count': '(40)', 'neighborhoods': []}, {'slug': 'el-patio-vida', 'name': 'El Patio Vida', 'count': '(31)', 'neighborhoods': []}, {'slug': 'mall-top-90', 'name': 'Mall Top 90', 'count': '(23)', 'neighborhoods': []}, {'slug': 'town-residence', 'name': 'Town Residence', 'count': '(23)', 'neighborhoods': []}, {'slug': 'w-signature', 'name': 'W Signature', 'count': '(15)', 'neighborhoods': []}, {'slug': 'the-mornings', 'name': 'The Mornings', 'count': '(14)', 'neighborhoods': []}, {'slug': 'loaloa', 'name': 'Loaloa', 'count': '(11)', 'neighborhoods': []}, {'slug': 'top-view', 'name': 'Top view', 'count': '(11)', 'neighborhoods': []}, {'slug': 'lotus-compound', 'name': 'Lotus Compound', 'count': '(9)', 'neighborhoods': []}, {'slug': 'prk-vie', 'name': 'Prk Vie', 'count': '(5)', 'neighborhoods': []}, {'slug': 'green-house', 'name': 'Green House', 'count': '(4)', 'neighborhoods': []}, {'slug': 'kemet', 'name': 'Kemet', 'count': '(3)', 'neighborhoods': []}]}

{locations: [{areas: [{count: (603), name: Privado, neighborhoods: [], slug: privado}],
      district: Madinaty, slug: madinaty}]}

In [38]:
def restructure_locations(flat_locations):
    """
    Restructure to have 'district' as a wrapper key
    """
    districts = {}
    
    for location in flat_locations:
        district_slug = location.get('slug')
        district_name = location.get('district')
        
        # Create district if doesn't exist
        if district_slug not in districts:
            districts[district_slug] = {
                'district': {  # ← 'district' as wrapper
                    'name': district_name,
                    'slug': district_slug,
                    'areas': []
                }
            }
        
        # Add areas to this district
        for area in location.get('areas', []):
            districts[district_slug]['district']['areas'].append({
                'name': area.get('name'),
                'slug': area.get('slug'),
                'count': area.get('count'),
                'neighborhoods': area.get('neighborhoods', [])
            })
    
    # Convert dict to list
    return [v for v in districts.values()]

# Usage
structured_data = restructure_locations(locations)

In [44]:
locations[locations.index(next(loc for loc in locations if loc['district'] == 'Zamelk'))]['areas']

StopIteration:

In [8]:
locations = config['locations']
loc = locations[1:3]
print("Data being written:")
print(yaml.dump({'locations': loc}, default_flow_style=False, allow_unicode=True, sort_keys=False))

Data being written:
locations:
- areas:
  - count: (603)
    name: Privado
    neighborhoods: []
    slug: privado
  district: Madinaty
  slug: madinaty
- areas:
  - count: (2475)
    name: Sarai
    neighborhoods: []
    slug: sarai
  - count: (841)
    name: Bloomfields
    neighborhoods: []
    slug: bloomfields
  - count: (365)
    name: L’Avenir
    neighborhoods: []
    slug: l-avenir
  - count: (215)
    name: Haptown
    neighborhoods: []
    slug: haptown
  - count: (200)
    name: Monte Napoleon
    neighborhoods: []
    slug: monte-napoleon
  - count: (199)
    name: Aliva mostakbal city
    neighborhoods: []
    slug: aliva-mostakbal-city
  - count: (196)
    name: Green Square
    neighborhoods: []
    slug: green-square
  - count: (186)
    name: Capital Gardens
    neighborhoods: []
    slug: capital-gardens
  - count: (166)
    name: The Butterfly
    neighborhoods: []
    slug: the-butterfly
  - count: (139)
    name: Park Central
    neighborhoods: []
    slug: park-central
  - count: (89)
    name: The Wonder MarQ
    neighborhoods: []
    slug: the-wonder-marq
  - count: (69)
    name: Zizinia El Mostakbal
    neighborhoods: []
    slug: zizinia-el-mostakbal
  - count: (68)
    name: La Mirada
    neighborhoods: []
    slug: la-mirada-2
  - count: (62)
    name: The Valleys
    neighborhoods: []
    slug: the-valleys
  - count: (55)
    name: East vale sodic
    neighborhoods: []
    slug: east-vale-sodic
  - count: (55)
    name: IL Bosco City
    neighborhoods: []
    slug: il-bosco-city
  - count: (54)
    name: Beta Greens
    neighborhoods: []
    slug: beta-greens
  - count: (40)
    name: Scenes
    neighborhoods: []
    slug: scenes
  - count: (40)
    name: CityZen
    neighborhoods: []
    slug: cityzen
  - count: (32)
    name: Mountain View
    neighborhoods: null
    slug: mountain-view-5
  - count: (30)
    name: Talda Mostakbal City
    neighborhoods: []
    slug: talda-mostakbal-city
  - count: (23)
    name: Neopolis
    neighborhoods: []
    slug: neopolis
  - count: (19)
    name: Rosail City
    neighborhoods: []
    slug: rosail-city
  - count: (18)
    name: At East
    neighborhoods: []
    slug: at-east
  - count: (16)
    name: Nyoum Mostakbal City
    neighborhoods: []
    slug: nyoum-mostakbal-city
  - count: (12)
    name: The 101
    neighborhoods: []
    slug: the-101
  - count: (11)
    name: Kukun
    neighborhoods: []
    slug: kukun
  - count: (10)
    name: Monark Residence
    neighborhoods: []
    slug: monark-residence
  - count: (8)
    name: Elaia
    neighborhoods: []
    slug: elaia
  - count: (7)
    name: Isola Quattro
    neighborhoods: []
    slug: isola-quattro
  - count: (7)
    name: Odyssia
    neighborhoods: []
    slug: odyssia
  - count: (6)
    name: Rare
    neighborhoods: []
    slug: rare
  - count: (5)
    name: Neo Gardens
    neighborhoods: []
    slug: neo-gardens
  - count: (4)
    name: Aria Compound
    neighborhoods: []
    slug: aria-2
  - count: (4)
    name: The Ridge
    neighborhoods: []
    slug: the-ridge
  - count: (3)
    name: Alaire
    neighborhoods: []
    slug: alaire
  - count: (2)
    name: Red
    neighborhoods: []
    slug: red
  - count: (1)
    name: The Marquette
    neighborhoods: []
    slug: the-marquette-mostakbal-city
  district: Mostakbal City
  slug: mostakbal-city

In [ ]:
import pickle 
with open('../locations_data.pkl', 'wb') as f:
    pickle.dump(locations, f)

KeyboardInterrupt:

In [ ]:
number_of_areas = 0
for location in locations:
   # print(f"{location['district']} has {len(location['areas'])} areas")
   print(f"district {location['district']} has {len(location['areas'])} areas")
   if len(location['areas']) == 40:
       
       print(location['areas'])

   number_of_areas += len(location['areas'])
#    print("--------------------")
print(f"Total number of areas: {number_of_areas}")

district New Cairo has 21 areas
district Madinaty has 1 areas
district Mostakbal City has 38 areas
district New Capital City has 40 areas
[{'slug': 'la-vista-city', 'name': 'La Vista City', 'count': '(735)', 'neighborhoods': None}, {'slug': 'al-maqsad', 'name': 'Al Maqsad', 'count': '(660)', 'neighborhoods': None}, {'slug': 'noor-city-2', 'name': 'Noor City', 'count': '(618)', 'neighborhoods': None}, {'slug': 'r8', 'name': 'R8', 'count': '(310)', 'neighborhoods': None}, {'slug': 'new-garden-city', 'name': 'New Garden City', 'count': '(243)', 'neighborhoods': None}, {'slug': 'il-bosco', 'name': 'IL Bosco', 'count': '(167)', 'neighborhoods': None}, {'slug': 'r3', 'name': 'R3', 'count': '(113)', 'neighborhoods': None}, {'slug': 'celia', 'name': 'Celia', 'count': '(108)', 'neighborhoods': None}, {'slug': 'r7', 'name': 'R7', 'count': '(96)', 'neighborhoods': None}, {'slug': 'r4', 'name': 'R4', 'count': '(91)', 'neighborhoods': None}, {'slug': 'taj-tower', 'name': 'Taj Tower', 'count': '(87)', 'neighborhoods': None}, {'slug': 'pyramids-mall', 'name': 'Pyramids Mall', 'count': '(63)', 'neighborhoods': None}, {'slug': 'de-joya', 'name': 'De Joya 1', 'count': '(62)', 'neighborhoods': None}, {'slug': 'granville', 'name': 'Granville', 'count': '(55)', 'neighborhoods': None}, {'slug': 'oia', 'name': 'OIA', 'count': '(54)', 'neighborhoods': None}, {'slug': 'sage-lakes', 'name': 'Sage Lakes', 'count': '(50)', 'neighborhoods': None}, {'slug': 'capital-gardens-2', 'name': 'Capital Gardens', 'count': '(43)', 'neighborhoods': None}, {'slug': 'blue-vert', 'name': 'Blue Vert', 'count': '(43)', 'neighborhoods': None}, {'slug': 'rivan', 'name': 'Rivan', 'count': '(43)', 'neighborhoods': None}, {'slug': 'armonia', 'name': 'Armonia', 'count': '(42)', 'neighborhoods': None}, {'slug': 'la-capital', 'name': 'La Capital', 'count': '(40)', 'neighborhoods': None}, {'slug': 'vinci', 'name': 'Vinci', 'count': '(39)', 'neighborhoods': None}, {'slug': 'financial-district', 'name': 'Financial District', 'count': '(36)', 'neighborhoods': None}, {'slug': 'mu23', 'name': 'MU23', 'count': '(31)', 'neighborhoods': None}, {'slug': 'mountain-view-3', 'name': 'Mountain View', 'count': '(30)', 'neighborhoods': None}, {'slug': 'hava', 'name': 'Hava', 'count': '(30)', 'neighborhoods': None}, {'slug': 'palm-hills-new-capital', 'name': 'Palm Hills New Capital', 'count': '(28)', 'neighborhoods': None}, {'slug': 'the-capital-way', 'name': 'The Capital Way', 'count': '(27)', 'neighborhoods': None}, {'slug': 'downtown-2', 'name': 'Downtown', 'count': '(26)', 'neighborhoods': None}, {'slug': 'midtown-sky', 'name': 'Midtown Sky', 'count': '(24)', 'neighborhoods': None}, {'slug': 'scenario', 'name': 'Scenario', 'count': '(24)', 'neighborhoods': None}, {'slug': 'golden-tower', 'name': 'Golden Tower', 'count': '(21)', 'neighborhoods': None}, {'slug': 'canyon-8', 'name': 'Canyon 8', 'count': '(17)', 'neighborhoods': None}, {'slug': 'midtown-condo', 'name': 'Midtown Condo', 'count': '(17)', 'neighborhoods': None}, {'slug': 'lumia-residence', 'name': 'Lumia Residence', 'count': '(16)', 'neighborhoods': None}, {'slug': 'scene-7', 'name': 'Scene 7', 'count': '(16)', 'neighborhoods': None}, {'slug': 'venia', 'name': 'Venia', 'count': '(16)', 'neighborhoods': None}, {'slug': 'government-district', 'name': 'Government District', 'count': '(15)', 'neighborhoods': None}, {'slug': 'la-reva', 'name': 'La Reva', 'count': '(15)', 'neighborhoods': None}, {'slug': 'catalan', 'name': 'Catalan', 'count': '(14)', 'neighborhoods': None}]
district Shorouk City has 40 areas
[{'slug': 'al-burouj', 'name': 'Al Burouj', 'count': '(1108)', 'neighborhoods': None}, {'slug': 'wesal', 'name': 'Wesal', 'count': '(508)', 'neighborhoods': None}, {'slug': 'maadi-view', 'name': 'Maadi View', 'count': '(252)', 'neighborhoods': None}, {'slug': 'el-patio-sola', 'name': 'El Patio Sola', 'count': '(119)', 'neighborhoods': None}, {'slug': 'el-patio-5', 'name': 'EL Patio 5', 'count': '(111)', 'neighborhoods': None}, {'slug': 'aljar-2', 'name': 'Aljar', 'count': '(90)', 'neighborhoods': None}, {'slug': 'el-patio-prime', 'name': 'EL Patio Prime', 'count': '(85)', 'neighborhoods': None}, {'slug': 'el-patio-casa', 'name': 'EL Patio Casa', 'count': '(78)', 'neighborhoods': None}, {'slug': 'divina-gardens', 'name': 'Divina Gardens', 'count': '(63)', 'neighborhoods': None}, {'slug': 'cleopatra-palace', 'name': 'Cleopatra Palace', 'count': '(55)', 'neighborhoods': None}, {'slug': 'el-shorouk-2000', 'name': 'El Shorouk 2000', 'count': '(52)', 'neighborhoods': None}, {'slug': 'palm-island', 'name': 'Palm Island', 'count': '(36)', 'neighborhoods': None}, {'slug': 'granda-alshorouk', 'name': 'Granda Alshorouk', 'count': '(27)', 'neighborhoods': None}, {'slug': 'palencia', 'name': 'Palencia', 'count': '(22)', 'neighborhoods': None}, {'slug': 'granda-life', 'name': 'Granda Life', 'count': '(22)', 'neighborhoods': None}, {'slug': 'town-center-el-shorouk-mall', 'name': 'Town Center El-Shorouk Mall', 'count': '(20)', 'neighborhoods': None}, {'slug': 'ivy-residence', 'name': 'Ivy Residence', 'count': '(19)', 'neighborhoods': None}, {'slug': 'palm-capital', 'name': 'Palm Capital', 'count': '(16)', 'neighborhoods': None}, {'slug': 'mercado-mall', 'name': 'Mercado Mall', 'count': '(13)', 'neighborhoods': None}, {'slug': 'el-shorouk-springs', 'name': 'El Shorouk Springs', 'count': '(13)', 'neighborhoods': None}, {'slug': 'shorouk-gardens', 'name': 'Shorouk Gardens', 'count': '(13)', 'neighborhoods': None}, {'slug': 'dar-misr-6', 'name': 'Dar Misr', 'count': '(12)', 'neighborhoods': None}, {'slug': 'panorama-el-shorouk', 'name': 'Panorama El Shorouk', 'count': '(11)', 'neighborhoods': None}, {'slug': 'arena-mall', 'name': 'Arena Mall', 'count': '(11)', 'neighborhoods': None}, {'slug': 'heliopolis-residence', 'name': 'Heliopolis Residence', 'count': '(10)', 'neighborhoods': None}, {'slug': 'moon-yard-mall', 'name': 'Moon Yard Mall', 'count': '(10)', 'neighborhoods': None}, {'slug': 'meraki-residence', 'name': 'Meraki Residence', 'count': '(9)', 'neighborhoods': None}, {'slug': 'may-fair-2', 'name': 'May Fair', 'count': '(9)', 'neighborhoods': None}, {'slug': 'el-shorouk-resort', 'name': 'El Shorouk Resort', 'count': '(8)', 'neighborhoods': None}, {'slug': 'beverly-hills-2', 'name': 'Beverly Hills', 'count': '(7)', 'neighborhoods': None}, {'slug': 'hayah-residence-2', 'name': 'Hayah Residence Compound', 'count': '(7)', 'neighborhoods': None}, {'slug': 'el-patio-4', 'name': 'EL Patio 4', 'count': '(6)', 'neighborhoods': None}, {'slug': 'stella-heliopolis', 'name': 'Stella Heliopolis', 'count': '(6)', 'neighborhoods': None}, {'slug': 'nakheel-residence', 'name': 'Nakheel Residence', 'count': '(5)', 'neighborhoods': None}, {'slug': 'janna-5', 'name': 'Janna', 'count': '(5)', 'neighborhoods': None}, {'slug': '1st-district-shorouk-city', 'name': '1st District', 'count': '(5)', 'neighborhoods': None}, {'slug': 'vivens', 'name': 'VIVENS', 'count': '(4)', 'neighborhoods': None}, {'slug': '5th-district-shorouk-city', 'name': '5th District', 'count': '(4)', 'neighborhoods': None}, {'slug': 'life-view', 'name': 'Life View', 'count': '(4)', 'neighborhoods': None}, {'slug': '6th-zone-shorouk-city', 'name': '6th Zone', 'count': '(3)', 'neighborhoods': None}]
district Nasr City has 25 areas
district Katameya has 18 areas
district New Heliopolis has 15 areas
district Maadi has 10 areas
district Sheraton has 8 areas
district Mokattam has 15 areas
district Zahraa Al Maadi has 30 areas
district Heliopolis has 6 areas
district Obour City has 16 areas
district Badr City has 5 areas
district El Fostat has 1 areas
district Zamalek has 0 areas
district New Nozha has 3 areas
district Ain Shams has 1 areas
district Al Manial has 1 areas
district Hadayeq El Zeitoun has 0 areas
district Hadayek al-Kobba has 3 areas
district Gesr Al Suez has 0 areas
district Downtown Cairo has 2 areas
district Almazah has 0 areas
district Helmeyat El Zaytoun has 0 areas
district Shubra has 1 areas
district Marg has 1 areas
district Helwan has 2 areas
district Nozha has 17 areas
district Hadayek Helwan has 0 areas
district Salam City has 1 areas
district Masr al-Kadema has 2 areas
district Abasiya has 1 areas
district 15 May City has 0 areas
district Matareya has 1 areas
district Boulaq Abo El Ela has 0 areas
district Garden City has 0 areas
district Rod al-Farag has 0 areas
district Basateen has 1 areas
Total number of areas: 326

In [54]:
for location in locations:
    print(f'{location["district"]} have {len(location["neighborhoods"])} neighborhoods')

KeyError: 'neighborhoods'

In [26]:
l = [{'slug': 'hyde-park-central', 'name': 'Hyde Park Central', 'count': '(193)'}, {'slug': '5th-settlement', 'name': '5th Settlement', 'count': '(43625)'}, {'slug': '1st-settlement', 'name': '1st Settlement', 'count': '(5744)'}, {'slug': 'rehab-city', 'name': 'Rehab City', 'count': '(5013)'}, {'slug': '6th-settlement', 'name': '6th Settlement', 'count': '(1598)'}, {'slug': '3rd-settlement', 'name': '3rd Settlement', 'count': '(371)'}, {'slug': 'ozone-medical-center', 'name': 'Ozone Medical Center', 'count': '(59)'}, {'slug': 'mohammed-naguib-axis', 'name': 'Mohammed Naguib Axis', 'count': '(55)'}, {'slug': 'gamal-abd-al-nasser-axis', 'name': 'Gamal Abd Al-Nasser Axis', 'count': '(41)'}, {'slug': 'el-patio-vida', 'name': 'El Patio Vida', 'count': '(27)'}, {'slug': 'mall-top-90', 'name': 'Mall Top 90', 'count': '(26)'}, {'slug': 'town-residence', 'name': 'Town Residence', 'count': '(21)'}, {'slug': 'dijar', 'name': 'Dijar', 'count': '(18)'}, {'slug': 'top-view', 'name': 'Top view', 'count': '(14)'}, {'slug': 'w-signature', 'name': 'W Signature', 'count': '(13)'}, {'slug': 'lotus-compound', 'name': 'Lotus Compound', 'count': '(10)'}, {'slug': 'loaloa', 'name': 'Loaloa', 'count': '(10)'}, {'slug': 'the-mornings', 'name': 'The Mornings', 'count': '(9)'}, {'slug': 'green-house', 'name': 'Green House', 'count': '(4)'}, {'slug': 'prk-vie', 'name': 'Prk Vie', 'count': '(4)'}, {'slug': 'kemet', 'name': 'Kemet', 'count': '(3)'}]
print(f"Total neighborhoods found: {len(l)}")

Total neighborhoods found: 21

In [11]:
print(districts_list)

[{'link': '/en/properties/new-cairo/', 'name': 'New Cairo', 'count': '(57478)'}, {'link': '/en/properties/madinaty/', 'name': 'Madinaty', 'count': '(11933)'}, {'link': '/en/properties/mostakbal-city/', 'name': 'Mostakbal City', 'count': '(5854)'}, {'link': '/en/properties/new-capital-city/', 'name': 'New Capital City', 'count': '(5108)'}, {'link': '/en/properties/shorouk-city/', 'name': 'Shorouk City', 'count': '(4491)'}, {'link': '/en/properties/nasr-city/', 'name': 'Nasr City', 'count': '(2756)'}, {'link': '/en/properties/katameya/', 'name': 'Katameya', 'count': '(1867)'}, {'link': '/en/properties/new-heliopolis/', 'name': 'New Heliopolis', 'count': '(1751)'}, {'link': '/en/properties/sheraton/', 'name': 'Sheraton', 'count': '(1559)'}, {'link': '/en/properties/maadi/', 'name': 'Maadi', 'count': '(1557)'}, {'link': '/en/properties/mokattam/', 'name': 'Mokattam', 'count': '(1426)'}, {'link': '/en/properties/zahraa-al-maadi/', 'name': 'Zahraa Al Maadi', 'count': '(1418)'}, {'link': '/en/properties/heliopolis/', 'name': 'Heliopolis', 'count': '(1411)'}, {'link': '/en/properties/obour-city/', 'name': 'Obour City', 'count': '(1095)'}, {'link': '/en/properties/badr-city/', 'name': 'Badr City', 'count': '(794)'}, {'link': '/en/properties/el-fostat/', 'name': 'El Fostat', 'count': '(149)'}, {'link': '/en/properties/zamalek/', 'name': 'Zamalek', 'count': '(135)'}, {'link': '/en/properties/new-nozha/', 'name': 'New Nozha', 'count': '(90)'}, {'link': '/en/properties/ain-shams/', 'name': 'Ain Shams', 'count': '(77)'}, {'link': '/en/properties/al-manial/', 'name': 'Al Manial', 'count': '(76)'}, {'link': '/en/properties/gesr-al-suez/', 'name': 'Gesr Al Suez', 'count': '(69)'}, {'link': '/en/properties/hadayeq-el-zeitoun/', 'name': 'Hadayeq El Zeitoun', 'count': '(68)'}, {'link': '/en/properties/hadayek-al-kobba/', 'name': 'Hadayek al-Kobba', 'count': '(66)'}, {'link': '/en/properties/downtown-cairo/', 'name': 'Downtown Cairo', 'count': '(66)'}, {'link': '/en/properties/almazah/', 'name': 'Almazah', 'count': '(57)'}, {'link': '/en/properties/shubra/', 'name': 'Shubra', 'count': '(48)'}, {'link': '/en/properties/helmeyat-el-zaytoun/', 'name': 'Helmeyat El Zaytoun', 'count': '(44)'}, {'link': '/en/properties/marg/', 'name': 'Marg', 'count': '(27)'}, {'link': '/en/properties/nozha/', 'name': 'Nozha', 'count': '(26)'}, {'link': '/en/properties/helwan/', 'name': 'Helwan', 'count': '(24)'}, {'link': '/en/properties/salam-city/', 'name': 'Salam City', 'count': '(21)'}, {'link': '/en/properties/hadayek-helwan/', 'name': 'Hadayek Helwan', 'count': '(20)'}, {'link': '/en/properties/abasiya/', 'name': 'Abasiya', 'count': '(18)'}, {'link': '/en/properties/matareya/', 'name': 'Matareya', 'count': '(15)'}, {'link': '/en/properties/masr-al-kadema/', 'name': 'Masr al-Kadema', 'count': '(15)'}, {'link': '/en/properties/15-may-city/', 'name': '15 May City', 'count': '(14)'}, {'link': '/en/properties/garden-city/', 'name': 'Garden City', 'count': '(11)'}, {'link': '/en/properties/boulaq-abo-el-ela/', 'name': 'Boulaq Abo El Ela', 'count': '(10)'}, {'link': '/en/properties/basateen/', 'name': 'Basateen', 'count': '(9)'}, {'link': '/en/properties/rod-al-farag/', 'name': 'Rod al-Farag', 'count': '(8)'}]

In [9]:
try:
    import lxml
    print("✅ lxml imported successfully!")
    print("Version:", lxml.__version__)
except ImportError as e:
    print("❌ Error:", e)

✅ lxml imported successfully!
Version: 6.0.2

In [12]:
import subprocess

# Use uv to install instead of pip
result = subprocess.run(
    ['uv', 'pip', 'install', '--reinstall', 'lxml'],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)

Using Python 3.9.2 environment at: D:\Marwan\Projects\cairo_real_state_intelligence_platform\.venv
Resolved 1 package in 651ms
Prepared 1 package in 0.83ms
Uninstalled 1 package in 27ms
warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 93ms
 ~ lxml==6.0.2

### This section is the basic logic implementation for how the whole the website will be scrapped 
we have 40 districts each district may have more than one area and each area may have more than one neighborhood. First there is multiple problem I have noticed when viewing the website we scrape the data in some areas that have neighborhoods there are properties that are listed at the area level but not assigned to any of the neighborhoods. this happens in the areas that have 1 to 4 neighborhoods and this also happens when the districts doesn't have alot of areas

In [7]:
locations = config['locations']
locations[0]['areas'][0]['neighborhoods']

[{'count': '(3463)',
  'name': 'Hyde Park New Cairo Compound',
  'slug': 'hyde-park-new-cairo-compound'},
 {'count': '(3280)', 'name': 'Mivida Compound', 'slug': 'mivida-compound'},
 {'count': '(2916)',
  'name': 'Mountain View iCity Compound',
  'slug': 'mountain-view-icity-compound'},
 {'count': '(1925)',
  'name': 'Palm Hills New Cairo Compound',
  'slug': 'palm-hills-new-cairo-compound'},
 {'count': '(1907)',
  'name': 'Fifth Square Compound',
  'slug': 'fifth-square-compound'},
 {'count': '(1323)',
  'name': 'Mountain View Hyde Park Compound',
  'slug': 'mountain-view-hyde-park-compound'},
 {'count': '(1293)', 'name': 'Eastown Compound', 'slug': 'eastown-compound'},
 {'count': '(1226)', 'name': 'Beit Al Watan', 'slug': 'beit-al-watan-6'},
 {'count': '(1192)',
  'name': 'City Gate Compound',
  'slug': 'city-gate-compound'},
 {'count': '(1162)',
  'name': 'Lake view Residence Compound',
  'slug': 'lake-view-residence-compound'},
 {'count': '(1100)',
  'name': 'EL Patio ORO Compound',
  'slug': 'el-patio-oro-compound'},
 {'count': '(1060)', 'name': 'Villette Compound', 'slug': 'villette-compound'},
 {'count': '(960)', 'name': 'El Lotus', 'slug': 'el-lotus-2'},
 {'count': '(838)',
  'name': 'The Address East Compound',
  'slug': 'the-address-east-compound'},
 {'count': '(773)', 'name': 'Al Andalous', 'slug': 'al-andalous-2'},
 {'count': '(759)',
  'name': 'Galleria Moon Valley Compound',
  'slug': 'galleria-moon-valley-compound'},
 {'count': '(685)',
  'name': 'Cairo Festival City',
  'slug': 'cairo-festival-city-3'},
 {'count': '(662)',
  'name': 'Mountain View 1.1',
  'slug': 'mountain-view-1-1-2'},
 {'count': '(646)', 'name': 'Al Narges', 'slug': 'al-narges-2'},
 {'count': '(644)',
  'name': 'Creek Town Compound',
  'slug': 'creek-town-compound'},
 {'count': '(586)',
  'name': 'District 5 Compound',
  'slug': 'district-5-compound-compound'},
 {'count': '(447)', 'name': 'North 90 Street', 'slug': 'north-90-street-2'},
 {'count': '(402)', 'name': 'Azzar Compound', 'slug': 'azzar-compound'},
 {'count': '(385)', 'name': 'South 90 Street', 'slug': 'south-90-street-2'},
 {'count': '(383)',
  'name': '90 Avenue Compound',
  'slug': '90-avenue-compound'},
 {'count': '(376)',
  'name': 'Lake View Residence 2',
  'slug': 'lake-view-residence-2-2'},
 {'count': '(337)',
  'name': 'The Square Compound',
  'slug': 'the-square-compound'},
 {'count': '(296)', 'name': 'South of Academy', 'slug': 'south-of-academy-2'},
 {'count': '(294)',
  'name': 'Katameya Dunes Compound',
  'slug': 'katameya-dunes-compound'},
 {'count': '(289)',
  'name': 'The Icon Residence Compound',
  'slug': 'the-icon-residence-compound'},
 {'count': '(278)',
  'name': 'Palm Hills Katameya Compound',
  'slug': 'palm-hills-katameya-compound'},
 {'count': '(278)',
  'name': 'The Waterway Compound',
  'slug': 'the-waterway-compound-2'},
 {'count': '(276)',
  'name': 'Village Gate Compound',
  'slug': 'village-gate-compound'},
 {'count': '(274)', 'name': 'Banafsag Omarat', 'slug': 'banafsag-omarat-2'},
 {'count': '(265)', 'name': 'layan Compound', 'slug': 'layan-compound'},
 {'count': '(265)', 'name': 'New Narges', 'slug': 'new-narges-2'},
 {'count': '(237)',
  'name': 'Lake View Compound',
  'slug': 'lake-view-compound'},
 {'count': '(237)',
  'name': 'The Village Compound',
  'slug': 'the-village-compound'},
 {'count': '(230)', 'name': 'AZAD Compound', 'slug': 'azad-compound'},
 {'count': '(230)', 'name': 'South Investors', 'slug': 'south-investors-2'}]

In [5]:
# let's start building the code
locations = config['locations']
empty_pd = []

for property_type in config['data_source']['realstate_website']['property_types']:
        no_dis = 0
        parts = property_type.split('-')
        type_ = parts[0]
        sale_or_rent = parts[-1]
        logs = []
        for location in locations:
            district_slug = location['slug']
            if len(location['areas']) == 0:
                url = f"{config['data_source']['realstate_website']['base_url']}{property_type}/{district_slug}/"
                empty_pd.append({'property_type': type_, 'sale/rent': sale_or_rent, 'city': 'Cairo', 'district': location['district'], 'area': None, 'neighborhood': None, 'link': url})
                logs.append(url)
                continue
            elif len(location['areas']) < 3:
                no_dis += 1
                url = f"{config['data_source']['realstate_website']['base_url']}{property_type}/{district_slug}/"
                empty_pd.append({'property_type': type_, 'sale/rent': sale_or_rent, 'city': 'Cairo', 'district': location['district'], 'area': None, 'neighborhood': None, 'link': url})
                logs.append(url)
            for area in location['areas']:
               
                area_slug = area['slug']
                
                     
                if len(area['neighborhoods']) == 0:
                    url = f"{config['data_source']['realstate_website']['base_url']}{property_type}/{area_slug}/"
                    empty_pd.append({'property_type': type_, 'sale/rent': sale_or_rent, 'city': 'Cairo', 'district': location['district'], 'area': area['name'], 'neighborhood': None, 'link': url})
                    logs.append(url)
                    continue
             
                 
                for neighborhood in area['neighborhoods']:
                    neighborhood_slug = neighborhood['slug']
                    url = f"{config['data_source']['realstate_website']['base_url']}{property_type}/{neighborhood_slug}/"
                    empty_pd.append({'property_type': type_, 'sale/rent': sale_or_rent, 'city': 'Cairo', 'district': location['district'], 'area': area['name'], 'neighborhood': neighborhood['name'], 'link': url})
                    logs.append(url)
            # print(f"Finished constructing URLs for district {location['district']} with {len(logs)} URLS")
        print(f"Total URLs constructed for {property_type}: {len(logs)}")
        print(f"district with less than 3 areas: {no_dis}")

Total URLs constructed for apartments-duplex-for-sale: 456
district with less than 3 areas: 13
Total URLs constructed for apartments-duplex-for-rent: 456
district with less than 3 areas: 13
Total URLs constructed for villas-for-sale: 456
district with less than 3 areas: 13
Total URLs constructed for villas-for-rent: 456
district with less than 3 areas: 13

In [6]:
base_link_df = pd.DataFrame(empty_pd)

In [11]:
base_link_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1824 entries, 0 to 1823
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  1824 non-null   object
 1   sale/rent      1824 non-null   object
 2   city           1824 non-null   object
 3   district       1824 non-null   object
 4   area           1732 non-null   object
 5   neighborhood   488 non-null    object
 6   link           1824 non-null   object
dtypes: object(7)
memory usage: 99.9+ KB

In [7]:
base_link_df.head()

,property_type,sale/rent,city,district,area,neighborhood,link
0,apartments,sale,Cairo,New Cairo,5th Settlement,Hyde Park New Cairo Compound,https://www.dubizzle.com.eg/en/properties/apar...
1,apartments,sale,Cairo,New Cairo,5th Settlement,Mivida Compound,https://www.dubizzle.com.eg/en/properties/apar...
2,apartments,sale,Cairo,New Cairo,5th Settlement,Mountain View iCity Compound,https://www.dubizzle.com.eg/en/properties/apar...
3,apartments,sale,Cairo,New Cairo,5th Settlement,Palm Hills New Cairo Compound,https://www.dubizzle.com.eg/en/properties/apar...
4,apartments,sale,Cairo,New Cairo,5th Settlement,Fifth Square Compound,https://www.dubizzle.com.eg/en/properties/apar...

In [8]:
base_link_df.describe()

,property_type,sale/rent,city,district,area,neighborhood,link
count,1772,1772,1772,1772,1732,488,1772
unique,2,2,1,40,318,122,1772
top,apartments,sale,Cairo,New Cairo,1st Settlement,Hyde Park New Cairo Compound,https://www.dubizzle.com.eg/en/properties/vill...
freq,886,886,1772,472,160,4,1

In [10]:
base_link_df['link'][0]

'https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/'

In [23]:
test2_main_page = base_link_df['link'][0]

In [24]:
tagmo3_test_page = get_page_data(test2_main_page)

Trying fast approach (requests)...
Response status: 200, length: 5165256
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/

In [13]:
test_main_page = 'https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/al-manial/'
manial_test_page = get_page_data(test_main_page)

Trying fast approach (requests)...
Response status: 200, length: 5036331
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/al-manial/

In [25]:
properties_list_div = tagmo3_test_page.select_one(config['data_source']['realstate_website']['main_page_selectors']['properties_div'])

In [26]:
properties_unordered_lists = properties_list_div.find_all('ul', recursive=False)

In [28]:
number_of_properties = 0
for ul in properties_unordered_lists:
    next_div = ul.find_next('div')
    listed_items = ul.find_all('li')
    next_div_text = next_div.span.text if next_div and next_div.span else "No class found"
    if next_div_text == 'Results from other locations':
        print("Reached the end of listings for this location, stopping extraction")
        break
    number_of_properties += len(listed_items)
    for item in listed_items:
        try:
            link = item.find('a')['href']
            # print(link)
        except Exception as e:
            print(f"This div doesn't contain a listing")
print(f"Total number of properties found: {number_of_properties}")

This div doesn't contain a listing
Total number of properties found: 46

In [34]:
tagmo3_df = base_link_df[base_link_df['district'] == 'New Cairo']

In [35]:
tagmo3_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 472 entries, 0 to 1446
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  472 non-null    object
 1   sale/rent      472 non-null    object
 2   city           472 non-null    object
 3   district       472 non-null    object
 4   area           472 non-null    object
 5   neighborhood   408 non-null    object
 6   link           472 non-null    object
dtypes: object(7)
memory usage: 29.5+ KB

### I'm now in the phase of I have each location URL and the scrapping is going to go through this phases:

1. I have 2 property types (apartment and villa) and 2 sale/rent types (sale and rent) so I will loop through each combination of these types and for each combination I will loop through the locations and construct the URL for each location.
   
2. Each location have more the one property maybe in one page or more in the first phase I want to extract the links for each property and save it in the dataframe with the already known information about this property.
   
3. Phase one is completed after i have links for all of the properties then I will go for each link and extract the property actuall data.

{'title': None, 'property_type': None, 'sale/rent': None, 'city': None, 'district': None, 'area': None, 'neighborhood': None, 'property_subtype': None, 'ownership': None, 'electricity meter': None, 'water meter': None, 'covered parking': None, 'natural gas': None, 'security': None, 'pets allowed': None, 'balcony': None, 'private garden': None, 'pool': None, 'landline': None, 'maid room': None, 'built in kitchen': None, 'elevator': None, 'central a/c & heating': None, 'furnished': None, 'level': None, 'bedrooms': None, 'bathrooms': None, 'payment option': None, 'delivery time': None, 'price': None, 'seller_name': None, 'area (mÂ²)': None, 'link': None}

In [7]:
def extract_properties_links(main_page_url, property_schema):
    try:
        page_soup = get_page_data(main_page_url)    
        properties_list_div = page_soup.select_one(config['data_source']['realstate_website']['main_page_selectors']['properties_div'])
    
        stop_pagenation_selector = page_soup.select_one(config['data_source']['realstate_website']['selectors']['stop_pagenation'])
        if stop_pagenation_selector and "Unfortunately we haven't found anything" in stop_pagenation_selector.text:
            print(f"No properties div found for {main_page_url}, skipping extraction")
            return []
        
        properties_unordered_lists = properties_list_div.find_all('ul', recursive=False)
        links = []
        for ul in properties_unordered_lists:
            next_div = ul.find_next('div')
            listed_items = ul.find_all('li')
            next_div_text = next_div.span.text if next_div and next_div.span else "No class found"
            if next_div_text == 'Results from other locations':
                print("Reached the end of listings for this location, stopping extraction")
                break
            for item in listed_items:
                link_container = item.find('a', href=True)
                
                if not link_container:  # expected case — just skip
                    continue
                
                link = link_container['href']
                title = link_container.get('title', 'No title found')
                
                if not link.startswith('/en/ad'):  # filter non-property links
                    continue
                
                try:
                    # keep try/except only for truly unexpected failures
                    prop = property_schema.copy()
                    prop['link'] = link
                    prop['title'] = title
                    links.append(prop)
                except Exception as e:
                    print(f"Unexpected error processing item: {e}")
                    print(f"Problematic item: {item}")  # print the actual HTML so you can debug
        
        return links
    except Exception as e:      
        print(f"Unexpected error occurred: {e}")
        return []

In [30]:
base_link_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1824 entries, 0 to 1823
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   property_type  1824 non-null   object
 1   sale/rent      1824 non-null   object
 2   city           1824 non-null   object
 3   district       1824 non-null   object
 4   area           1732 non-null   object
 5   neighborhood   488 non-null    object
 6   link           1824 non-null   object
dtypes: object(7)
memory usage: 99.9+ KB

In [8]:
def property_coordinator(df, property_schema):
    all_properties = []
    try:
        
        for location in df.itertuples():
            max_number_of_pages = config['data_source']['realstate_website']['selectors']['max_page_number']
            for i in range(1, max_number_of_pages):
                url =location.link + f"?page={i}"
                properties = extract_properties_links(url, property_schema)
                if not properties:
                    print(f"No properties found on page {url}")
                    break

                for prop in properties:
                    prop['property_type'] = location.property_type
                    prop['sale/rent'] = location._2
                    prop['city'] = location.city
                    prop['district'] = location.district
                    prop['area'] = location.area
                    prop['neighborhood'] = location.neighborhood
                all_properties.extend(properties)

            
        return pd.DataFrame(all_properties)
    except Exception as e:
        print(f"Error in property coordinator: {e}")
        return pd.DataFrame(all_properties)

In [19]:
x = base_link_df['link'].unique()
len(x)
for l in x:
    if 'true' in l:
        print(l)

https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/true
https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-rent/true
https://www.dubizzle.com.eg/en/properties/villas-for-sale/true
https://www.dubizzle.com.eg/en/properties/villas-for-rent/true

In [9]:
fields = config['data_source']['realstate_website']['fields']
fields.append('link')
property_schema = {field: None for field in fields}
properties_df = property_coordinator(base_link_df, property_schema)

Trying fast approach (requests)...
Response status: 200, length: 5526299
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=1
Trying fast approach (requests)...
Response status: 200, length: 5515421
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=2
Trying fast approach (requests)...
Response status: 200, length: 5505239
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=3
Trying fast approach (requests)...
Response status: 200, length: 5506975
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=4
Trying fast approach (requests)...
Response status: 200, length: 5493318
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=5
Trying fast approach (requests)...
Response status: 200, length: 5500016
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=6
Trying fast approach (requests)...
Response status: 200, length: 5497644
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=7
Trying fast approach (requests)...
Response status: 200, length: 5520685
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=8
Trying fast approach (requests)...
Response status: 200, length: 5504379
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=9
Trying fast approach (requests)...
Response status: 200, length: 5501322
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=10
Trying fast approach (requests)...
Response status: 200, length: 5501719
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=11
Trying fast approach (requests)...
Response status: 200, length: 5502125
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=12
Trying fast approach (requests)...
Response status: 200, length: 5492467
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=13
Trying fast approach (requests)...
Response status: 200, length: 5492856
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=14
Trying fast approach (requests)...
Response status: 200, length: 5516788
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=15
Trying fast approach (requests)...
Response status: 200, length: 5507756
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=16
Trying fast approach (requests)...
Response status: 200, length: 5511627
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=17
Trying fast approach (requests)...
Response status: 200, length: 5510685
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=18
Trying fast approach (requests)...
Response status: 200, length: 5520471
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=19
Trying fast approach (requests)...
Response status: 200, length: 5505297
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=20
Trying fast approach (requests)...
Response status: 200, length: 5542339
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=21
Trying fast approach (requests)...
Response status: 200, length: 5508169
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=22
Trying fast approach (requests)...
Response status: 200, length: 5521834
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=23
Trying fast approach (requests)...
Response status: 200, length: 5512746
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=24
Trying fast approach (requests)...
Response status: 200, length: 5504657
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=25
Trying fast approach (requests)...
Response status: 200, length: 5496999
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=26
Trying fast approach (requests)...
Response status: 200, length: 5509974
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=27
Trying fast approach (requests)...
Response status: 200, length: 5508712
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=28
Trying fast approach (requests)...
Response status: 200, length: 5508211
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=29
Trying fast approach (requests)...
Response status: 200, length: 5493899
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=30
Reached the end of listings for this location, stopping extraction
Trying fast approach (requests)...
Response status: 200, length: 5480902
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=31
No properties div found for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=31, skipping extraction
No properties found on page https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/?page=31
Trying fast approach (requests)...
Response status: 200, length: 5508207
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=1
Trying fast approach (requests)...
Response status: 200, length: 5512910
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=2
Trying fast approach (requests)...
Response status: 200, length: 5478289
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=3
Trying fast approach (requests)...
Response status: 200, length: 5499423
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=4
Trying fast approach (requests)...
Response status: 200, length: 5495211
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=5
Trying fast approach (requests)...
Response status: 200, length: 5481540
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=6
Trying fast approach (requests)...
Response status: 200, length: 5501224
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=7
Trying fast approach (requests)...
Response status: 200, length: 5488854
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=8
Trying fast approach (requests)...
Response status: 200, length: 5498300
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=9
Trying fast approach (requests)...
Response status: 200, length: 5495143
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=10
Trying fast approach (requests)...
Response status: 200, length: 5488327
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=11
Trying fast approach (requests)...
Response status: 200, length: 5485725
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=12
Trying fast approach (requests)...
Response status: 200, length: 5482665
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=13
Reached the end of listings for this location, stopping extraction
Trying fast approach (requests)...
Response status: 200, length: 5474600
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=14
No properties div found for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=14, skipping extraction
No properties found on page https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mivida-compound/?page=14
Trying fast approach (requests)...
Response status: 200, length: 5535840
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=1
Trying fast approach (requests)...
Response status: 200, length: 5586565
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=2
Trying fast approach (requests)...
Response status: 200, length: 5540204
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=3
Trying fast approach (requests)...
Response status: 200, length: 5507601
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=4
Trying fast approach (requests)...
Response status: 200, length: 5521643
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=5
Trying fast approach (requests)...
Response status: 200, length: 5663214
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=6
Trying fast approach (requests)...
Response status: 200, length: 5793087
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=7
Trying fast approach (requests)...
Response status: 200, length: 5602139
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=8
Trying fast approach (requests)...
Response status: 200, length: 5560552
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=9
Trying fast approach (requests)...
Response status: 200, length: 5550336
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=10
Trying fast approach (requests)...
Response status: 200, length: 5518579
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=11
Trying fast approach (requests)...
Response status: 200, length: 5537614
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=12
Trying fast approach (requests)...
Response status: 200, length: 5597685
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=13
Trying fast approach (requests)...
Response status: 200, length: 5521498
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=14
Trying fast approach (requests)...
Response status: 200, length: 5595662
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=15
Trying fast approach (requests)...
Response status: 200, length: 5551597
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=16
Trying fast approach (requests)...
Response status: 200, length: 5552255
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=17
Trying fast approach (requests)...
Response status: 200, length: 5511536
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=18
Trying fast approach (requests)...
Response status: 200, length: 5707170
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=19
Trying fast approach (requests)...
Response status: 200, length: 5577424
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=20
Trying fast approach (requests)...
Response status: 200, length: 5514454
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=21
Trying fast approach (requests)...
Response status: 200, length: 5532482
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=22
Trying fast approach (requests)...
Response status: 200, length: 5538498
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=23
Trying fast approach (requests)...
Response status: 200, length: 5522689
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=24
Trying fast approach (requests)...
Response status: 200, length: 5531067
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=25
Trying fast approach (requests)...
Response status: 200, length: 5537543
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=26
Trying fast approach (requests)...
Response status: 200, length: 5545282
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=27
Trying fast approach (requests)...
Response status: 200, length: 5515468
Content looks valid, using requests response
Success with requests!
Data extracted for https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/mountain-view-icity-compound/?page=28

In [10]:
properties_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70565 entries, 0 to 70564
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   title                  70565 non-null  object
 1   property_type          70565 non-null  object
 2   sale/rent              70565 non-null  object
 3   city                   70565 non-null  object
 4   district               70565 non-null  object
 5   area                   63968 non-null  object
 6   neighborhood           40720 non-null  object
 7   property_subtype       0 non-null      object
 8   ownership              0 non-null      object
 9   electricity meter      0 non-null      object
 10  water meter            0 non-null      object
 11  covered parking        0 non-null      object
 12  natural gas            0 non-null      object
 13  security               0 non-null      object
 14  pets allowed           0 non-null      object
 15  balcony                0 non-null      object
 16  private garden         0 non-null      object
 17  pool                   0 non-null      object
 18  landline               0 non-null      object
 19  maid room              0 non-null      object
 20  built in kitchen       0 non-null      object
 21  elevator               0 non-null      object
 22  central a/c & heating  0 non-null      object
 23  furnished              0 non-null      object
 24  level                  0 non-null      object
 25  bedrooms               0 non-null      object
 26  bathrooms              0 non-null      object
 27  payment option         0 non-null      object
 28  delivery time          0 non-null      object
 29  price                  0 non-null      object
 30  seller_name            0 non-null      object
 31  area (mÂ²)             0 non-null      object
 32  link                   70565 non-null  object
dtypes: object(33)
memory usage: 17.8+ MB

In [14]:
properties_df.to_csv('../data/properties_version1.csv', index=False)

In [ ]:
# locations = config['locations']
# property_types = config['data_source']['realstate_website']['property_types']
# for property_type in property_types:
#     base_link = config['data_source']['realstate_website']['base_url'] + property_type + '/'
#     urls = []
#     for location in locations:
#         if len(location['areas']) > 0:
#             for area in location['areas']:
#                 if len(area['neighborhoods']) > 0:
#                     for neighborhood in area['neighborhoods']:
#                         # Here for the locations that have neigbhorhoods
#                         url = f"{base_link}{neighborhood['slug']}/"
#                         coordinate_extractor(url, {
#                             'property_type': property_type.split('-')[0],
#                             'sale_or_rent': property_type.split('-')[-1],
#                             'city': 'Cairo',
#                             'district': location['district'],
#                             'area': area['name'],
#                             'neighborhood': neighborhood['name']
#                         })

#                 else:
#                     # Here for that are one the area level
#                     url = f"{base_link}{area['slug']}/"
#                     coordinate_extractor(url, {
#                         'property_type': property_type.split('-')[0],
#                         'sale_or_rent': property_type.split('-')[-1],
#                         'city': 'Cairo',
#                         'district': location['district'],
#                         'area': area['name'],
#                         'neighborhood': None
#                     })

#         else:
#             # Herer for the case of locations that only have a district
#             url = f"{base_link}{location['slug']}/"
#             coordinate_extractor(url, {
#                     'property_type': property_type.split('-')[0],
#                     'sale_or_rent': property_type.split('-')[-1],
#                     'city': 'Cairo',
#                     'district': location['district'],
#                     'area': None,
#                     'neighborhood': None
#                 })

https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/hyde-park-new-cairo-compound/
https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/alba-aliyah-uptown-cairo/
https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/saint-teresa-el-sahel/
https://www.dubizzle.com.eg/en/properties/apartments-duplex-for-sale/6-october-st-kafr-abu-seer/

In [22]:
locations = config['locations']
num1 = 0
num2 = 0
for location in locations:
    if len(location['areas']) == 0:
        num1 += 1
    for area in location['areas']:
        if len(area['neighborhoods']) == 0:
            num2 += 1
print(f"Number of districts with no areas: {num1}")
print(f"Number of areas with no neighborhoods: {num2}")

Number of districts with no areas: 10
Number of areas with no neighborhoods: 311